In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

# Setting up environment

In [ ]:

import pandas as pd
import geopandas as gpd
from getpass import getpass
from google.colab import files
import plotly.express as px
import requests
import warnings

pd.set_option('display.max_columns', None) # show all columns
warnings.filterwarnings("ignore") # suppress warnings

# Get the census api key

get the key from here --> https://api.census.gov/data/key_signup.html

In [ ]:
census_api_key = getpass('Enter the api key: ') #6205ccd0c7ea6bc443d4305fa21e429e938a576e

Enter the api key: ··········

In [ ]:
def json_to_dataframe(response):
    """
    Convert response to dataframe
    """
    return pd.DataFrame(response.json()[1:], columns=response.json()[0])

# test run (you can ignore this part)

In [ ]:
# population united states
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S1901)&ucgid=860Z200US10001,860Z200US10002"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
response

In [ ]:
response.text

'[["GEO_ID","NAME","S1901_C01_001E","S1901_C01_001EA","S1901_C01_001M","S1901_C01_001MA","S1901_C01_002E","S1901_C01_002EA","S1901_C01_002M","S1901_C01_002MA","S1901_C01_003E","S1901_C01_003EA","S1901_C01_003M","S1901_C01_003MA","S1901_C01_004E","S1901_C01_004EA","S1901_C01_004M","S1901_C01_004MA","S1901_C01_005E","S1901_C01_005EA","S1901_C01_005M","S1901_C01_005MA","S1901_C01_006E","S1901_C01_006EA","S1901_C01_006M","S1901_C01_006MA","S1901_C01_007E","S1901_C01_007EA","S1901_C01_007M","S1901_C01_007MA","S1901_C01_008E","S1901_C01_008EA","S1901_C01_008M","S1901_C01_008MA","S1901_C01_009E","S1901_C01_009EA","S1901_C01_009M","S1901_C01_009MA","S1901_C01_010E","S1901_C01_010EA","S1901_C01_010M","S1901_C01_010MA","S1901_C01_011E","S1901_C01_011EA","S1901_C01_011M","S1901_C01_011MA","S1901_C01_012E","S1901_C01_012EA","S1901_C01_012M","S1901_C01_012MA","S1901_C01_013E","S1901_C01_013EA","S1901_C01_013M","S1901_C01_013MA","S1901_C01_014E","S1901_C01_014EA","S1901_C01_014M","S1901_C01_014MA","S1901_C01_015E","S1901_C01_015EA","S1901_C01_015M","S1901_C01_015MA","S1901_C01_016E","S1901_C01_016EA","S1901_C01_016M","S1901_C01_016MA","S1901_C02_001E","S1901_C02_001EA","S1901_C02_001M","S1901_C02_001MA","S1901_C02_002E","S1901_C02_002EA","S1901_C02_002M","S1901_C02_002MA","S1901_C02_003E","S1901_C02_003EA","S1901_C02_003M","S1901_C02_003MA","S1901_C02_004E","S1901_C02_004EA","S1901_C02_004M","S1901_C02_004MA","S1901_C02_005E","S1901_C02_005EA","S1901_C02_005M","S1901_C02_005MA","S1901_C02_006E","S1901_C02_006EA","S1901_C02_006M","S1901_C02_006MA","S1901_C02_007E","S1901_C02_007EA","S1901_C02_007M","S1901_C02_007MA","S1901_C02_008E","S1901_C02_008EA","S1901_C02_008M","S1901_C02_008MA","S1901_C02_009E","S1901_C02_009EA","S1901_C02_009M","S1901_C02_009MA","S1901_C02_010E","S1901_C02_010EA","S1901_C02_010M","S1901_C02_010MA","S1901_C02_011E","S1901_C02_011EA","S1901_C02_011M","S1901_C02_011MA","S1901_C02_012E","S1901_C02_012EA","S1901_C02_012M","S1901_C02_012MA","S1901_C02_013E","S1901_C02_013EA","S1901_C02_013M","S1901_C02_013MA","S1901_C02_014E","S1901_C02_014EA","S1901_C02_014M","S1901_C02_014MA","S1901_C02_015E","S1901_C02_015EA","S1901_C02_015M","S1901_C02_015MA","S1901_C02_016E","S1901_C02_016EA","S1901_C02_016M","S1901_C02_016MA","S1901_C03_001E","S1901_C03_001EA","S1901_C03_001M","S1901_C03_001MA","S1901_C03_002E","S1901_C03_002EA","S1901_C03_002M","S1901_C03_002MA","S1901_C03_003E","S1901_C03_003EA","S1901_C03_003M","S1901_C03_003MA","S1901_C03_004E","S1901_C03_004EA","S1901_C03_004M","S1901_C03_004MA","S1901_C03_005E","S1901_C03_005EA","S1901_C03_005M","S1901_C03_005MA","S1901_C03_006E","S1901_C03_006EA","S1901_C03_006M","S1901_C03_006MA","S1901_C03_007E","S1901_C03_007EA","S1901_C03_007M","S1901_C03_007MA","S1901_C03_008E","S1901_C03_008EA","S1901_C03_008M","S1901_C03_008MA","S1901_C03_009E","S1901_C03_009EA","S1901_C03_009M","S1901_C03_009MA","S1901_C03_010E","S1901_C03_010EA","S1901_C03_010M","S1901_C03_010MA","S1901_C03_011E","S1901_C03_011EA","S1901_C03_011M","S1901_C03_011MA","S1901_C03_012E","S1901_C03_012EA","S1901_C03_012M","S1901_C03_012MA","S1901_C03_013E","S1901_C03_013EA","S1901_C03_013M","S1901_C03_013MA","S1901_C03_014E","S1901_C03_014EA","S1901_C03_014M","S1901_C03_014MA","S1901_C03_015E","S1901_C03_015EA","S1901_C03_015M","S1901_C03_015MA","S1901_C03_016E","S1901_C03_016EA","S1901_C03_016M","S1901_C03_016MA","S1901_C04_001E","S1901_C04_001EA","S1901_C04_001M","S1901_C04_001MA","S1901_C04_002E","S1901_C04_002EA","S1901_C04_002M","S1901_C04_002MA","S1901_C04_003E","S1901_C04_003EA","S1901_C04_003M","S1901_C04_003MA","S1901_C04_004E","S1901_C04_004EA","S1901_C04_004M","S1901_C04_004MA","S1901_C04_005E","S1901_C04_005EA","S1901_C04_005M","S1901_C04_005MA","S1901_C04_006E","S1901_C04_006EA","S1901_C04_006M","S1901_C04_006MA","S1901_C04_007E","S1901_C04_007EA","S1901_C04_007M","S1901_C04_007MA","S1901_C04_008E","S1901_C04_008EA","S1901_C04_008M","S1901_C04_008MA","S1901_C04_009E","S1901_C04_009EA","S1901_C04_009M","S1901_C04_009MA","S1901_C04_010E","S1901_C04_010EA","S1901_C04_010M","S1901_C04_010MA","S1901_C04_011E","S1901_C04_011EA","S1901_C04_011M","S1901_C04_011MA","S1901_C04_012E","S1901_C04_012EA","S1901_C04_012M","S1901_C04_012MA","S1901_C04_013E","S1901_C04_013EA","S1901_C04_013M","S1901_C04_013MA","S1901_C04_014E","S1901_C04_014EA","S1901_C04_014M","S1901_C04_014MA","S1901_C04_015E","S1901_C04_015EA","S1901_C04_015M","S1901_C04_015MA","S1901_C04_016E","S1901_C04_016EA","S1901_C04_016M","S1901_C04_016MA","ucgid"],\n["860Z200US10001","ZCTA5 10001","15097",null,"796",null,"4.7",null,"1.4",null,"4.6",null,"1.8",null,"4.5",null,"1.6",null,"4.2",null,"1.8",null,"6.5",null,"2.0",null,"10.0",null,"2.7",null,"8.3",null,"2.1",null,"11.4",null,"2.0",null,"11.3",null,"2.6",null,"34.5",null,"3.5",null,"123393",null,"22852",null,"205444",null,"18473",null,"22.0",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","4715",null,"650",null,"4.1",null,"2.7",null,"3.0",null,"2.2",null,"5.0",null,"3.6",null,"3.9",null,"3.0",null,"4.8",null,"3.4",null,"7.7",null,"4.5",null,"8.1",null,"4.5",null,"5.8",null,"3.4",null,"9.4",null,"4.2",null,"48.2",null,"6.7",null,"182117",null,"44151",null,"269616",null,"35285",null,"-888888888","(X)","-888888888","(X)","26.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","3291",null,"544",null,"0.6",null,"1.1",null,"0.0",null,"1.2",null,"6.3",null,"5.2",null,"0.9",null,"1.1",null,"5.5",null,"4.6",null,"3.1",null,"2.7",null,"4.2",null,"3.1",null,"7.2",null,"4.5",null,"13.0",null,"5.8",null,"59.4",null,"8.4",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10382",null,"864",null,"5.2",null,"1.8",null,"5.6",null,"2.3",null,"4.4",null,"1.7",null,"4.3",null,"2.1",null,"6.9",null,"2.2",null,"10.8",null,"3.3",null,"8.8",null,"2.3",null,"13.6",null,"2.5",null,"12.0",null,"3.0",null,"28.3",null,"4.1",null,"105801",null,"9254",null,"175089",null,"21182",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","20.0",null,"-888888888.0","(X)","860Z200US10001"],\n["860Z200US10002","ZCTA5 10002","35771",null,"1265",null,"9.5",null,"1.9",null,"10.9",null,"2.1",null,"11.8",null,"1.9",null,"9.0",null,"2.2",null,"11.0",null,"2.0",null,"9.8",null,"1.8",null,"8.6",null,"1.6",null,"11.9",null,"1.9",null,"5.6",null,"1.3",null,"11.8",null,"1.2",null,"46525",null,"5561",null,"93314",null,"6116",null,"42.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","16924",null,"978",null,"6.2",null,"1.9",null,"6.5",null,"3.6",null,"12.0",null,"2.9",null,"12.0",null,"4.2",null,"12.9",null,"3.1",null,"12.2",null,"2.8",null,"8.7",null,"2.1",null,"11.1",null,"2.6",null,"5.6",null,"1.8",null,"12.7",null,"2.1",null,"51093",null,"8077",null,"98795",null,"8346",null,"-888888888","(X)","-888888888","(X)","45.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","9848",null,"866",null,"1.9",null,"1.3",null,"7.4",null,"6.1",null,"11.7",null,"3.9",null,"11.9",null,"6.8",null,"8.8",null,"3.1",null,"9.0",null,"2.7",null,"9.5",null,"2.8",null,"14.1",null,"3.4",null,"7.6",null,"2.7",null,"18.0",null,"3.2",null,"71682",null,"16972",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","18847",null,"952",null,"12.9",null,"3.0",null,"14.8",null,"3.0",null,"11.6",null,"3.0",null,"6.0",null,"1.6",null,"9.5",null,"2.6",null,"7.5",null,"2.1",null,"8.9",null,"2.1",null,"12.6",null,"2.8",null,"5.6",null,"1.6",null,"10.8",null,"1.8",null,"41294",null,"6161",null,"87485",null,"8499",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","40.2",null,"-888888888.0","(X)","860Z200US10002"]]'

In [ ]:

df_test = json_to_dataframe(response)

In [ ]:
selected_columns = df_test[['ucgid','S1901_C01_012E', 'S1901_C01_013E']]
selected_columns

            ucgid S1901_C01_012E S1901_C01_013E
0  860Z200US10001         123393         205444
1  860Z200US10002          46525          93314

In [ ]:
# prompt: get only S1901_C01_012E, S1901_C01_013E columns

# Assuming 'df' is the DataFrame created from the API response in the previous code.
# If not, replace 'df' with the actual DataFrame variable name.

selected_columns = df[['S1901_C01_012E', 'S1901_C01_013E']]
selected_columns

# Useful variables, columns

from S1901:\
S1901_C01_001E = number of household \
S1901_C01_012E = household median income (1year estimate) \
S1901_C01_013E = household mean income (1year estimate) \

# Get NYC zip code (ZCTA)

In [ ]:
# prompt: i want to read xlsx file from google drive

import pandas as pd
# Specify the path to your XLSX file in Google Drive
file_path = '/content/drive/MyDrive/MLC_Final_Project/Data/NYC_ZCTA.csv'  # Replace 'your_excel_file.xlsx' with the actual file name

try:
  # Read the XLSX file into a pandas DataFrame
  nyc_zcta = pd.read_csv(file_path)

  # Now you can work with the DataFrame 'df'
  print(df.head())  # Print the first few rows of the DataFrame

except FileNotFoundError:
  print(f"Error: File not found at {file_path}")
except Exception as e:
  print(f"An error occurred: {e}")

    ZCTA  MODZCTA  UHFCODE                         UHFNAME    BOROUGH  \
0  10001    10001      306               Chelsea - Clinton  Manhattan
1  10002    10002      309  Union Square - Lower East Side  Manhattan
2  10003    10003      309  Union Square - Lower East Side  Manhattan
3  10004    10004      310                 Lower Manhattan  Manhattan
4  10005    10005      310                 Lower Manhattan  Manhattan

  Unnamed: 5
0       True
1       True
2       True
3       True
4       True

In [ ]:
# prompt: take each element from 'ZCTA' column from 'nyc_zcta' and turn it into '860Z200US10001' which is '860Z200US' joined by '10001'

# Assuming 'nyc_zcta' DataFrame is already loaded as shown in the provided code.

nyc_zcta['ucgid'] = '860Z200US' + nyc_zcta['ZCTA'].astype(str)
print(nyc_zcta.head())

    ZCTA  MODZCTA  UHFCODE                         UHFNAME    BOROUGH  \
0  10001    10001      306               Chelsea - Clinton  Manhattan
1  10002    10002      309  Union Square - Lower East Side  Manhattan
2  10003    10003      309  Union Square - Lower East Side  Manhattan
3  10004    10004      310                 Lower Manhattan  Manhattan
4  10005    10005      310                 Lower Manhattan  Manhattan

  Unnamed: 5           ucgid
0       True  860Z200US10001
1       True  860Z200US10002
2       True  860Z200US10003
3       True  860Z200US10004
4       True  860Z200US10005

In [ ]:
# prompt: take '860Z200US10001' and change to '8600000US10001' which is joined by 8600000US + 10001

# ... (Your existing code)

# Modify the 'ucgid' column
nyc_zcta['ucgid_2'] = '8600000US' + nyc_zcta['ZCTA'].astype(str)
print(nyc_zcta.head())

    ZCTA  MODZCTA  UHFCODE                         UHFNAME    BOROUGH  \
0  10001    10001      306               Chelsea - Clinton  Manhattan
1  10002    10002      309  Union Square - Lower East Side  Manhattan
2  10003    10003      309  Union Square - Lower East Side  Manhattan
3  10004    10004      310                 Lower Manhattan  Manhattan
4  10005    10005      310                 Lower Manhattan  Manhattan

  Unnamed: 5           ucgid         ucgid_2
0       True  860Z200US10001  8600000US10001
1       True  860Z200US10002  8600000US10002
2       True  860Z200US10003  8600000US10003
3       True  860Z200US10004  8600000US10004
4       True  860Z200US10005  8600000US10005

In [ ]:
# prompt: take all rows from 'ucgid' and put it in this format '860Z200US10001,860Z200US10002'

# Assuming 'nyc_zcta' DataFrame is already loaded as shown in the provided code.
# and it contains a column 'ucgid'

# Convert the 'ucgid' column to a string if it is not already a string
nyc_zcta['ucgid'] = nyc_zcta['ucgid'].astype(str)

# Combine all ucgid values into a single string, separated by commas
ucgid_string = ','.join(nyc_zcta['ucgid'].tolist())

ucgid_string

'860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999'

In [ ]:
# Convert the 'ucgid' column to a string if it is not already a string
nyc_zcta['ucgid'] = nyc_zcta['ucgid'].astype(str)

# Combine all ucgid values into a single string, separated by commas
ucgid_string_2 = ','.join(nyc_zcta['ucgid_2'].tolist())

ucgid_string_2

'8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999'

# Get ACS household median and mean income (1 year estimate)

## 2023

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S1901)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
response.text

'[["GEO_ID","NAME","S1901_C01_001E","S1901_C01_001EA","S1901_C01_001M","S1901_C01_001MA","S1901_C01_002E","S1901_C01_002EA","S1901_C01_002M","S1901_C01_002MA","S1901_C01_003E","S1901_C01_003EA","S1901_C01_003M","S1901_C01_003MA","S1901_C01_004E","S1901_C01_004EA","S1901_C01_004M","S1901_C01_004MA","S1901_C01_005E","S1901_C01_005EA","S1901_C01_005M","S1901_C01_005MA","S1901_C01_006E","S1901_C01_006EA","S1901_C01_006M","S1901_C01_006MA","S1901_C01_007E","S1901_C01_007EA","S1901_C01_007M","S1901_C01_007MA","S1901_C01_008E","S1901_C01_008EA","S1901_C01_008M","S1901_C01_008MA","S1901_C01_009E","S1901_C01_009EA","S1901_C01_009M","S1901_C01_009MA","S1901_C01_010E","S1901_C01_010EA","S1901_C01_010M","S1901_C01_010MA","S1901_C01_011E","S1901_C01_011EA","S1901_C01_011M","S1901_C01_011MA","S1901_C01_012E","S1901_C01_012EA","S1901_C01_012M","S1901_C01_012MA","S1901_C01_013E","S1901_C01_013EA","S1901_C01_013M","S1901_C01_013MA","S1901_C01_014E","S1901_C01_014EA","S1901_C01_014M","S1901_C01_014MA","S1901_C01_015E","S1901_C01_015EA","S1901_C01_015M","S1901_C01_015MA","S1901_C01_016E","S1901_C01_016EA","S1901_C01_016M","S1901_C01_016MA","S1901_C02_001E","S1901_C02_001EA","S1901_C02_001M","S1901_C02_001MA","S1901_C02_002E","S1901_C02_002EA","S1901_C02_002M","S1901_C02_002MA","S1901_C02_003E","S1901_C02_003EA","S1901_C02_003M","S1901_C02_003MA","S1901_C02_004E","S1901_C02_004EA","S1901_C02_004M","S1901_C02_004MA","S1901_C02_005E","S1901_C02_005EA","S1901_C02_005M","S1901_C02_005MA","S1901_C02_006E","S1901_C02_006EA","S1901_C02_006M","S1901_C02_006MA","S1901_C02_007E","S1901_C02_007EA","S1901_C02_007M","S1901_C02_007MA","S1901_C02_008E","S1901_C02_008EA","S1901_C02_008M","S1901_C02_008MA","S1901_C02_009E","S1901_C02_009EA","S1901_C02_009M","S1901_C02_009MA","S1901_C02_010E","S1901_C02_010EA","S1901_C02_010M","S1901_C02_010MA","S1901_C02_011E","S1901_C02_011EA","S1901_C02_011M","S1901_C02_011MA","S1901_C02_012E","S1901_C02_012EA","S1901_C02_012M","S1901_C02_012MA","S1901_C02_013E","S1901_C02_013EA","S1901_C02_013M","S1901_C02_013MA","S1901_C02_014E","S1901_C02_014EA","S1901_C02_014M","S1901_C02_014MA","S1901_C02_015E","S1901_C02_015EA","S1901_C02_015M","S1901_C02_015MA","S1901_C02_016E","S1901_C02_016EA","S1901_C02_016M","S1901_C02_016MA","S1901_C03_001E","S1901_C03_001EA","S1901_C03_001M","S1901_C03_001MA","S1901_C03_002E","S1901_C03_002EA","S1901_C03_002M","S1901_C03_002MA","S1901_C03_003E","S1901_C03_003EA","S1901_C03_003M","S1901_C03_003MA","S1901_C03_004E","S1901_C03_004EA","S1901_C03_004M","S1901_C03_004MA","S1901_C03_005E","S1901_C03_005EA","S1901_C03_005M","S1901_C03_005MA","S1901_C03_006E","S1901_C03_006EA","S1901_C03_006M","S1901_C03_006MA","S1901_C03_007E","S1901_C03_007EA","S1901_C03_007M","S1901_C03_007MA","S1901_C03_008E","S1901_C03_008EA","S1901_C03_008M","S1901_C03_008MA","S1901_C03_009E","S1901_C03_009EA","S1901_C03_009M","S1901_C03_009MA","S1901_C03_010E","S1901_C03_010EA","S1901_C03_010M","S1901_C03_010MA","S1901_C03_011E","S1901_C03_011EA","S1901_C03_011M","S1901_C03_011MA","S1901_C03_012E","S1901_C03_012EA","S1901_C03_012M","S1901_C03_012MA","S1901_C03_013E","S1901_C03_013EA","S1901_C03_013M","S1901_C03_013MA","S1901_C03_014E","S1901_C03_014EA","S1901_C03_014M","S1901_C03_014MA","S1901_C03_015E","S1901_C03_015EA","S1901_C03_015M","S1901_C03_015MA","S1901_C03_016E","S1901_C03_016EA","S1901_C03_016M","S1901_C03_016MA","S1901_C04_001E","S1901_C04_001EA","S1901_C04_001M","S1901_C04_001MA","S1901_C04_002E","S1901_C04_002EA","S1901_C04_002M","S1901_C04_002MA","S1901_C04_003E","S1901_C04_003EA","S1901_C04_003M","S1901_C04_003MA","S1901_C04_004E","S1901_C04_004EA","S1901_C04_004M","S1901_C04_004MA","S1901_C04_005E","S1901_C04_005EA","S1901_C04_005M","S1901_C04_005MA","S1901_C04_006E","S1901_C04_006EA","S1901_C04_006M","S1901_C04_006MA","S1901_C04_007E","S1901_C04_007EA","S1901_C04_007M","S1901_C04_007MA","S1901_C04_008E","S1901_C04_008EA","S1901_C04_008M","S1901_C04_008MA","S1901_C04_009E","S1901_C04_009EA","S1901_C04_009M","S1901_C04_009MA","S1901_C04_010E","S1901_C04_010EA","S1901_C04_010M","S1901_C04_010MA","S1901_C04_011E","S1901_C04_011EA","S1901_C04_011M","S1901_C04_011MA","S1901_C04_012E","S1901_C04_012EA","S1901_C04_012M","S1901_C04_012MA","S1901_C04_013E","S1901_C04_013EA","S1901_C04_013M","S1901_C04_013MA","S1901_C04_014E","S1901_C04_014EA","S1901_C04_014M","S1901_C04_014MA","S1901_C04_015E","S1901_C04_015EA","S1901_C04_015M","S1901_C04_015MA","S1901_C04_016E","S1901_C04_016EA","S1901_C04_016M","S1901_C04_016MA","ucgid"],\n["860Z200US10001","ZCTA5 10001","15097",null,"796",null,"4.7",null,"1.4",null,"4.6",null,"1.8",null,"4.5",null,"1.6",null,"4.2",null,"1.8",null,"6.5",null,"2.0",null,"10.0",null,"2.7",null,"8.3",null,"2.1",null,"11.4",null,"2.0",null,"11.3",null,"2.6",null,"34.5",null,"3.5",null,"123393",null,"22852",null,"205444",null,"18473",null,"22.0",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","4715",null,"650",null,"4.1",null,"2.7",null,"3.0",null,"2.2",null,"5.0",null,"3.6",null,"3.9",null,"3.0",null,"4.8",null,"3.4",null,"7.7",null,"4.5",null,"8.1",null,"4.5",null,"5.8",null,"3.4",null,"9.4",null,"4.2",null,"48.2",null,"6.7",null,"182117",null,"44151",null,"269616",null,"35285",null,"-888888888","(X)","-888888888","(X)","26.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","3291",null,"544",null,"0.6",null,"1.1",null,"0.0",null,"1.2",null,"6.3",null,"5.2",null,"0.9",null,"1.1",null,"5.5",null,"4.6",null,"3.1",null,"2.7",null,"4.2",null,"3.1",null,"7.2",null,"4.5",null,"13.0",null,"5.8",null,"59.4",null,"8.4",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10382",null,"864",null,"5.2",null,"1.8",null,"5.6",null,"2.3",null,"4.4",null,"1.7",null,"4.3",null,"2.1",null,"6.9",null,"2.2",null,"10.8",null,"3.3",null,"8.8",null,"2.3",null,"13.6",null,"2.5",null,"12.0",null,"3.0",null,"28.3",null,"4.1",null,"105801",null,"9254",null,"175089",null,"21182",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","20.0",null,"-888888888.0","(X)","860Z200US10001"],\n["860Z200US10002","ZCTA5 10002","35771",null,"1265",null,"9.5",null,"1.9",null,"10.9",null,"2.1",null,"11.8",null,"1.9",null,"9.0",null,"2.2",null,"11.0",null,"2.0",null,"9.8",null,"1.8",null,"8.6",null,"1.6",null,"11.9",null,"1.9",null,"5.6",null,"1.3",null,"11.8",null,"1.2",null,"46525",null,"5561",null,"93314",null,"6116",null,"42.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","16924",null,"978",null,"6.2",null,"1.9",null,"6.5",null,"3.6",null,"12.0",null,"2.9",null,"12.0",null,"4.2",null,"12.9",null,"3.1",null,"12.2",null,"2.8",null,"8.7",null,"2.1",null,"11.1",null,"2.6",null,"5.6",null,"1.8",null,"12.7",null,"2.1",null,"51093",null,"8077",null,"98795",null,"8346",null,"-888888888","(X)","-888888888","(X)","45.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","9848",null,"866",null,"1.9",null,"1.3",null,"7.4",null,"6.1",null,"11.7",null,"3.9",null,"11.9",null,"6.8",null,"8.8",null,"3.1",null,"9.0",null,"2.7",null,"9.5",null,"2.8",null,"14.1",null,"3.4",null,"7.6",null,"2.7",null,"18.0",null,"3.2",null,"71682",null,"16972",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","18847",null,"952",null,"12.9",null,"3.0",null,"14.8",null,"3.0",null,"11.6",null,"3.0",null,"6.0",null,"1.6",null,"9.5",null,"2.6",null,"7.5",null,"2.1",null,"8.9",null,"2.1",null,"12.6",null,"2.8",null,"5.6",null,"1.6",null,"10.8",null,"1.8",null,"41294",null,"6161",null,"87485",null,"8499",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","40.2",null,"-888888888.0","(X)","860Z200US10002"],\n["860Z200US10003","ZCTA5 10003","25080",null,"1152",null,"7.5",null,"1.8",null,"3.3",null,"1.5",null,"3.3",null,"1.0",null,"2.3",null,"0.8",null,"4.6",null,"1.2",null,"8.9",null,"2.3",null,"7.2",null,"1.5",null,"12.1",null,"1.6",null,"11.7",null,"1.8",null,"39.1",null,"3.5",null,"153750",null,"11191",null,"248577",null,"23076",null,"31.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","6847",null,"630",null,"0.5",null,"0.6",null,"2.1",null,"1.9",null,"1.1",null,"1.1",null,"0.9",null,"0.7",null,"3.1",null,"2.1",null,"3.3",null,"1.7",null,"3.9",null,"1.8",null,"8.3",null,"2.8",null,"13.6",null,"3.2",null,"63.2",null,"4.9",null,"250001","250,000+","-333333333","***","416996",null,"52091",null,"-888888888","(X)","-888888888","(X)","39.2",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","5896",null,"578",null,"0.4",null,"0.5",null,"0.7",null,"0.9",null,"0.9",null,"1.1",null,"0.6",null,"0.6",null,"2.9",null,"2.4",null,"2.5",null,"1.7",null,"3.6",null,"1.8",null,"7.8",null,"3.0",null,"13.3",null,"3.3",null,"67.4",null,"5.1",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","18233",null,"1077",null,"10.2",null,"2.4",null,"3.8",null,"2.0",null,"4.2",null,"1.4",null,"2.8",null,"1.1",null,"5.1",null,"1.5",null,"11.0",null,"3.0",null,"8.4",null,"2.0",null,"14.0",null,"1.9",null,"11.0",null,"2.3",null,"29.5",null,"4.2",null,"117570",null,"9771",null,"184364",null,"26945",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","28.4",null,"-888888888.0","(X)","860Z200US10003"],\n["860Z200US10004","ZCTA5 10004","1775",null,"384",null,"2.3",null,"1.6",null,"0.0",null,"2.2",null,"0.3",null,"0.5",null,"0.3",null,"0.5",null,"0.3",null,"0.5",null,"4.6",null,"4.9",null,"9.9",null,"7.5",null,"14.1",null,"7.8",null,"13.4",null,"10.1",null,"54.8",null,"11.5",null,"220592",null,"53147",null,"309645",null,"70590",null,"42.9",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","799",null,"205",null,"1.9",null,"2.8",null,"0.0",null,"4.9",null,"0.8",null,"1.1",null,"0.0",null,"4.9",null,"0.0",null,"4.9",null,"0.5",null,"0.8",null,"3.1",null,"3.5",null,"11.6",null,"10.1",null,"8.1",null,"7.1",null,"74.0",null,"13.2",null,"250001","250,000+","-333333333","***","394971",null,"85515",null,"-888888888","(X)","-888888888","(X)","51.2",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","761",null,"209",null,"2.0",null,"2.9",null,"0.0",null,"5.1",null,"0.8",null,"1.2",null,"0.0",null,"5.1",null,"0.0",null,"5.1",null,"0.5",null,"0.8",null,"2.6",null,"3.5",null,"12.2",null,"10.4",null,"5.0",null,"4.3",null,"76.9",null,"13.4",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","976",null,"287",null,"2.6",null,"1.9",null,"0.0",null,"4.0",null,"0.0",null,"4.0",null,"0.5",null,"0.9",null,"0.6",null,"0.9",null,"8.0",null,"8.6",null,"16.0",null,"13.3",null,"15.7",null,"11.3",null,"18.1",null,"17.4",null,"38.5",null,"15.9",null,"178034",null,"46920",null,"238825",null,"102272",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","36.2",null,"-888888888.0","(X)","860Z200US10004"],\n["860Z200US10005","ZCTA5 10005","5156",null,"588",null,"0.4",null,"0.6",null,"1.6",null,"1.6",null,"0.2",null,"0.2",null,"2.5",null,"2.3",null,"5.1",null,"3.5",null,"4.2",null,"2.9",null,"7.9",null,"4.3",null,"12.7",null,"4.8",null,"13.9",null,"5.0",null,"51.7",null,"7.2",null,"211810",null,"29291",null,"279387",null,"30910",null,"24.7",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1432",null,"348",null,"0.0",null,"2.8",null,"0.0",null,"2.8",null,"2.7",null,"5.7",null,"2.9",null,"4.4",null,"0.0",null,"2.8",null,"0.6",null,"1.0",null,"4.7",null,"5.0",null,"8.9",null,"7.1",null,"11.5",null,"8.4",null,"68.6",null,"12.8",null,"250001","250,000+","-333333333","***","391858",null,"82109",null,"-888888888","(X)","-888888888","(X)","24.6",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1321",null,"346",null,"0.0",null,"3.0",null,"0.0",null,"3.0",null,"0.0",null,"3.0",null,"3.2",null,"4.7",null,"0.0",null,"3.0",null,"0.7",null,"1.0",null,"4.8",null,"5.5",null,"7.6",null,"6.7",null,"12.4",null,"8.9",null,"71.2",null,"12.3",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","3724",null,"587",null,"0.5",null,"0.9",null,"2.1",null,"2.2",null,"0.2",null,"0.3",null,"2.3",null,"2.7",null,"6.0",null,"4.2",null,"5.6",null,"4.0",null,"9.0",null,"5.5",null,"14.1",null,"6.2",null,"14.8",null,"6.7",null,"45.2",null,"8.8",null,"191394",null,"32759",null,"235868",null,"32534",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","24.8",null,"-888888888.0","(X)","860Z200US10005"],\n["860Z200US10006","ZCTA5 10006","2305",null,"270",null,"3.0",null,"2.1",null,"0.0",null,"1.7",null,"2.1",null,"3.4",null,"2.8",null,"3.2",null,"7.6",null,"5.7",null,"7.4",null,"4.6",null,"5.4",null,"4.2",null,"10.3",null,"4.8",null,"8.9",null,"5.0",null,"52.5",null,"9.6",null,"209972",null,"43452",null,"235292",null,"31362",null,"33.9",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","792",null,"262",null,"1.6",null,"2.4",null,"0.0",null,"4.9",null,"6.2",null,"9.4",null,"0.0",null,"4.9",null,"1.4",null,"2.2",null,"0.0",null,"4.9",null,"2.3",null,"3.9",null,"6.4",null,"7.9",null,"9.5",null,"11.2",null,"72.6",null,"15.8",null,"250001","250,000+","-333333333","***","329790",null,"64126",null,"-888888888","(X)","-888888888","(X)","29.4",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","632",null,"249",null,"0.0",null,"6.1",null,"0.0",null,"6.1",null,"0.0",null,"6.1",null,"0.0",null,"6.1",null,"1.7",null,"2.8",null,"0.0",null,"6.1",null,"2.8",null,"5.1",null,"4.4",null,"7.1",null,"3.6",null,"5.8",null,"87.3",null,"10.3",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1513",null,"261",null,"3.6",null,"3.1",null,"0.0",null,"2.6",null,"0.0",null,"2.6",null,"4.2",null,"4.8",null,"10.9",null,"8.3",null,"11.2",null,"6.4",null,"7.1",null,"6.1",null,"12.3",null,"7.0",null,"8.6",null,"5.5",null,"42.0",null,"12.7",null,"150609",null,"52306",null,"185827",null,"37460",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","36.2",null,"-888888888.0","(X)","860Z200US10006"],\n["860Z200US10007","ZCTA5 10007","3309",null,"472",null,"4.8",null,"3.0",null,"1.4",null,"2.2",null,"0.0",null,"1.2",null,"1.6",null,"2.1",null,"1.1",null,"1.5",null,"2.4",null,"2.6",null,"3.1",null,"3.5",null,"4.4",null,"3.9",null,"14.3",null,"7.1",null,"66.8",null,"7.7",null,"250001","250,000+","-333333333","***","512350",null,"113482",null,"33.7",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1690",null,"407",null,"0.8",null,"1.4",null,"0.0",null,"2.3",null,"0.0",null,"2.3",null,"0.0",null,"2.3",null,"0.9",null,"1.7",null,"0.5",null,"1.0",null,"5.1",null,"6.4",null,"3.8",null,"5.7",null,"6.3",null,"6.1",null,"82.5",null,"8.8",null,"250001","250,000+","-333333333","***","725328",null,"185795",null,"-888888888","(X)","-888888888","(X)","30.4",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1516",null,"400",null,"0.9",null,"1.6",null,"0.0",null,"2.6",null,"0.0",null,"2.6",null,"0.0",null,"2.6",null,"1.1",null,"1.8",null,"0.0",null,"2.6",null,"5.7",null,"6.9",null,"0.0",null,"2.6",null,"6.0",null,"6.5",null,"86.4",null,"9.3",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1619",null,"292",null,"9.0",null,"6.0",null,"2.9",null,"4.5",null,"0.0",null,"2.4",null,"3.3",null,"4.3",null,"1.3",null,"2.2",null,"4.3",null,"5.3",null,"1.1",null,"1.8",null,"4.9",null,"5.4",null,"22.6",null,"12.7",null,"50.5",null,"11.7",null,"210343",null,"27230",null,"282549",null,"70302",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","37.2",null,"-888888888.0","(X)","860Z200US10007"],\n["860Z200US10009","ZCTA5 10009","30025",null,"1230",null,"10.5",null,"2.0",null,"6.2",null,"1.5",null,"7.1",null,"1.3",null,"3.7",null,"1.1",null,"5.4",null,"1.4",null,"11.8",null,"2.1",null,"9.5",null,"1.9",null,"14.5",null,"2.8",null,"11.1",null,"2.4",null,"20.2",null,"2.7",null,"87963",null,"9219",null,"134024",null,"10212",null,"30.7",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10493",null,"957",null,"8.2",null,"2.3",null,"3.0",null,"2.7",null,"7.6",null,"2.3",null,"3.7",null,"1.5",null,"9.6",null,"2.9",null,"13.2",null,"3.9",null,"7.0",null,"3.1",null,"9.3",null,"3.5",null,"9.3",null,"3.9",null,"29.0",null,"5.8",null,"88469",null,"24027",null,"169783",null,"24206",null,"-888888888","(X)","-888888888","(X)","35.7",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","6210",null,"919",null,"3.9",null,"2.2",null,"3.5",null,"4.3",null,"5.7",null,"2.8",null,"2.9",null,"1.5",null,"5.4",null,"2.5",null,"10.8",null,"5.6",null,"3.0",null,"2.2",null,"10.4",null,"5.1",null,"14.5",null,"6.4",null,"39.8",null,"8.8",null,"159158",null,"21915",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","19532",null,"1245",null,"12.0",null,"3.0",null,"8.5",null,"2.2",null,"6.9",null,"1.6",null,"3.7",null,"1.3",null,"3.5",null,"1.3",null,"10.3",null,"2.2",null,"11.1",null,"2.6",null,"17.2",null,"3.8",null,"11.9",null,"3.0",null,"14.9",null,"3.2",null,"85953",null,"8240",null,"109268",null,"8456",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","27.6",null,"-888888888.0","(X)","860Z200US10009"],\n["860Z200US10010","ZCTA5 10010","16192",null,"1320",null,"4.9",null,"1.5",null,"2.8",null,"2.4",null,"4.2",null,"2.5",null,"4.2",null,"1.6",null,"2.8",null,"1.2",null,"6.7",null,"2.0",null,"6.2",null,"1.8",null,"14.8",null,"3.2",null,"11.1",null,"2.5",null,"42.1",null,"4.0",null,"156127",null,"11635",null,"253684",null,"32816",null,"33.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","6113",null,"859",null,"0.8",null,"1.2",null,"0.0",null,"0.7",null,"4.2",null,"5.2",null,"0.9",null,"0.9",null,"2.4",null,"2.1",null,"5.1",null,"2.9",null,"4.1",null,"2.4",null,"11.7",null,"4.6",null,"11.3",null,"3.5",null,"59.4",null,"7.9",null,"224893",null,"36165",null,"354599",null,"70019",null,"-888888888","(X)","-888888888","(X)","39.8",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","4728",null,"823",null,"0.0",null,"0.8",null,"0.0",null,"0.8",null,"1.2",null,"1.4",null,"1.2",null,"1.2",null,"2.2",null,"2.5",null,"0.9",null,"1.1",null,"4.6",null,"2.7",null,"12.9",null,"5.8",null,"7.2",null,"3.6",null,"69.9",null,"8.0",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10079",null,"914",null,"7.4",null,"2.4",null,"4.6",null,"3.8",null,"4.3",null,"2.2",null,"6.3",null,"2.6",null,"3.1",null,"1.5",null,"8.0",null,"2.8",null,"7.7",null,"2.8",null,"16.4",null,"3.8",null,"10.8",null,"3.3",null,"31.6",null,"4.9",null,"118003",null,"13128",null,"191753",null,"27582",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","29.0",null,"-888888888.0","(X)","860Z200US10010"],\n["860Z200US10011","ZCTA

In [ ]:
df_test = json_to_dataframe(response)
df_test

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001EA,S1901_C01_001M,S1901_C01_001MA,S1901_C01_002E,S1901_C01_002EA,S1901_C01_002M,S1901_C01_002MA,S1901_C01_003E,S1901_C01_003EA,S1901_C01_003M,S1901_C01_003MA,S1901_C01_004E,S1901_C01_004EA,S1901_C01_004M,S1901_C01_004MA,S1901_C01_005E,S1901_C01_005EA,S1901_C01_005M,S1901_C01_005MA,S1901_C01_006E,S1901_C01_006EA,S1901_C01_006M,S1901_C01_006MA,S1901_C01_007E,S1901_C01_007EA,S1901_C01_007M,S1901_C01_007MA,S1901_C01_008E,S1901_C01_008EA,S1901_C01_008M,S1901_C01_008MA,S1901_C01_009E,S1901_C01_009EA,S1901_C01_009M,S1901_C01_009MA,S1901_C01_010E,S1901_C01_010EA,S1901_C01_010M,S1901_C01_010MA,S1901_C01_011E,S1901_C01_011EA,S1901_C01_011M,S1901_C01_011MA,S1901_C01_012E,S1901_C01_012EA,S1901_C01_012M,S1901_C01_012MA,S1901_C01_013E,S1901_C01_013EA,S1901_C01_013M,S1901_C01_013MA,S1901_C01_014E,S1901_C01_014EA,S1901_C01_014M,S1901_C01_014MA,S1901_C01_015E,S1901_C01_015EA,S1901_C01_015M,S1901_C01_015MA,S1901_C01_016E,S1901_C01_016EA,S1901_C01_016M,S1901_C01_016MA,S1901_C02_001E,S1901_C02_001EA,S1901_C02_001M,S1901_C02_001MA,S1901_C02_002E,S1901_C02_002EA,S1901_C02_002M,S1901_C02_002MA,S1901_C02_003E,S1901_C02_003EA,S1901_C02_003M,S1901_C02_003MA,S1901_C02_004E,S1901_C02_004EA,S1901_C02_004M,S1901_C02_004MA,S1901_C02_005E,S1901_C02_005EA,S1901_C02_005M,S1901_C02_005MA,S1901_C02_006E,S1901_C02_006EA,S1901_C02_006M,S1901_C02_006MA,S1901_C02_007E,S1901_C02_007EA,S1901_C02_007M,S1901_C02_007MA,S1901_C02_008E,S1901_C02_008EA,S1901_C02_008M,S1901_C02_008MA,S1901_C02_009E,S1901_C02_009EA,S1901_C02_009M,S1901_C02_009MA,S1901_C02_010E,S1901_C02_010EA,S1901_C02_010M,S1901_C02_010MA,S1901_C02_011E,S1901_C02_011EA,S1901_C02_011M,S1901_C02_011MA,S1901_C02_012E,S1901_C02_012EA,S1901_C02_012M,S1901_C02_012MA,S1901_C02_013E,S1901_C02_013EA,S1901_C02_013M,S1901_C02_013MA,S1901_C02_014E,S1901_C02_014EA,S1901_C02_014M,S1901_C02_014MA,S1901_C02_015E,S1901_C02_015EA,S1901_C02_015M,S1901_C02_015MA,S1901_C02_016E,S1901_C02_016EA,S1901_C02_016M,S1901_C02_016MA,S1901_C03_001E,S1901_C03_001EA,S1901_C03_001M,S1901_C03_001MA,S1901_C03_002E,S1901_C03_002EA,S1901_C03_002M,S1901_C03_002MA,S1901_C03_003E,S1901_C03_003EA,S1901_C03_003M,S1901_C03_003MA,S1901_C03_004E,S1901_C03_004EA,S1901_C03_004M,S1901_C03_004MA,S1901_C03_005E,S1901_C03_005EA,S1901_C03_005M,S1901_C03_005MA,S1901_C03_006E,S1901_C03_006EA,S1901_C03_006M,S1901_C03_006MA,S1901_C03_007E,S1901_C03_007EA,S1901_C03_007M,S1901_C03_007MA,S1901_C03_008E,S1901_C03_008EA,S1901_C03_008M,S1901_C03_008MA,S1901_C03_009E,S1901_C03_009EA,S1901_C03_009M,S1901_C03_009MA,S1901_C03_010E,S1901_C03_010EA,S1901_C03_010M,S1901_C03_010MA,S1901_C03_011E,S1901_C03_011EA,S1901_C03_011M,S1901_C03_011MA,S1901_C03_012E,S1901_C03_012EA,S1901_C03_012M,S1901_C03_012MA,S1901_C03_013E,S1901_C03_013EA,S1901_C03_013M,S1901_C03_013MA,S1901_C03_014E,S1901_C03_014EA,S1901_C03_014M,S1901_C03_014MA,S1901_C03_015E,S1901_C03_015EA,S1901_C03_015M,S1901_C03_015MA,S1901_C03_016E,S1901_C03_016EA,S1901_C03_016M,S1901_C03_016MA,S1901_C04_001E,S1901_C04_001EA,S1901_C04_001M,S1901_C04_001MA,S1901_C04_002E,S1901_C04_002EA,S1901_C04_002M,S1901_C04_002MA,S1901_C04_003E,S1901_C04_003EA,S1901_C04_003M,S1901_C04_003MA,S1901_C04_004E,S1901_C04_004EA,S1901_C04_004M,S1901_C04_004MA,S1901_C04_005E,S1901_C04_005EA,S1901_C04_005M,S1901_C04_005MA,S1901_C04_006E,S1901_C04_006EA,S1901_C04_006M,S1901_C04_006MA,S1901_C04_007E,S1901_C04_007EA,S1901_C04_007M,S1901_C04_007MA,S1901_C04_008E,S1901_C04_008EA,S1901_C04_008M,S1901_C04_008MA,S1901_C04_009E,S1901_C04_009EA,S1901_C04_009M,S1901_C04_009MA,S1901_C04_010E,S1901_C04_010EA,S1901_C04_010M,S1901_C04_010MA,S1901_C04_011E,S1901_C04_011EA,S1901_C04_011M,S1901_C04_011MA,S1901_C04_012E,S1901_C04_012EA,S1901_C04_012M,S1901_C04_012MA,S1901_C04_013E,S1901_C04_013EA,S1901_C04_013M,S1901_C04_013MA,S1901_C04_014E,S1901_C04_014EA,S1901_C04_014M,S1901_C04_014MA,S1901_C04_015E,S1901_C04_015EA,S1901_C04_015M,S1901_C04_015MA,S1901_C04_016E,S1901_C04_016EA,S1901_C04_016M,S1901_C04_016MA,ucgid
0,860Z200US10001,ZCTA5 10001,15097,None,796,None,4.7,None,1.4,None,4.6,None,1.8,None,4.5,None,1.6,None,4.2,None,1.8,None,6.5,None,2.0,None,10.0,None,2.7,None,8.3,None,2.1,None,11.4,None,2.0,None,11.3,None,2.6,None,34.5,None,3.5,None,123393,None,22852,None,205444,None,18473,None,22.0,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),4715,None,650,None,4.1,None,2.7,None,3.0,None,2.2,None,5.0,None,3.6,None,3.9,None,3.0,None,4.8,None,3.4,None,7.7,None,4.5,None,8.1,None,4.5,None,5.8,None,3.4,None,9.4,None,4.2,None,48.2,None,6.7,None,182117,None,44151,None,269616,None,35285,None,-888888888,(X),-888888888,(X),26.5,None,-888888888.0,(X),-888888888,(X),-888888888,(X),3291,None,544,None,0.6,None,1.1,None,0.0,None,1.2,None,6.3,None,5.2,None,0.9,None,1.1,None,5.5,None,4.6,None,3.1,None,2.7,None,4.2,None,3.1,None,7.2,None,4.5,None,13.0,None,5.8,None,59.4,None,8.4,None,250001,"250,000+",-333333333,***,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),10382,None,864,None,5.2,None,1.8,None,5.6,None,2.3,None,4.4,None,1.7,None,4.3,None,2.1,None,6.9,None,2.2,None,10.8,None,3.3,None,8.8,None,2.3,None,13.6,None,2.5,None,12.0,None,3.0,None,28.3,None,4.1,None,105801,None,9254,None,175089,None,21182,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),20.0,None,-888888888.0,(X),860Z200US10001
1,860Z200US10002,ZCTA5 10002,35771,None,1265,None,9.5,None,1.9,None,10.9,None,2.1,None,11.8,None,1.9,None,9.0,None,2.2,None,11.0,None,2.0,None,9.8,None,1.8,None,8.6,None,1.6,None,11.9,None,1.9,None,5.6,None,1.3,None,11.8,None,1.2,None,46525,None,5561,None,93314,None,6116,None,42.5,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),16924,None,978,None,6.2,None,1.9,None,6.5,None,3.6,None,12.0,None,2.9,None,12.0,None,4.2,None,12.9,None,3.1,None,12.2,None,2.8,None,8.7,None,2.1,None,11.1,None,2.6,None,5.6,None,1.8,None,12.7,None,2.1,None,51093,None,8077,None,98795,None,8346,None,-888888888,(X),-888888888,(X),45.1,None,-888888888.0,(X),-888888888,(X),-888888888,(X),9848,None,866,None,1.9,None,1.3,None,7.4,None,6.1,None,11.7,None,3.9,None,11.9,None,6.8,None,8.8,None,3.1,None,9.0,None,2.7,None,9.5,None,2.8,None,14.1,None,3.4,None,7.6,None,2.7,None,18.0,None,3.2,None,71682,None,16972,None,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),18847,None,952,None,12.9,None,3.0,None,14.8,None,3.0,None,11.6,None,3.0,None,6.0,None,1.6,None,9.5,None,2.6,None,7.5,None,2.1,None,8.9,None,2.1,None,12.6,None,2.8,None,5.6,None,1.6,None,10.8,None,1.8,None,41294,None,6161,None,87485,None,8499,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),40.2,None,-888888888.0,(X),860Z200US10002
2,860Z200US10003,ZCTA5 10003,25080,None,1152,None,7.5,None,1.8,None,3.3,None,1.5,None,3.3,None,1.0,None,2.3,None,0.8,None,4.6,None,1.2,None,8.9,None,2.3,None,7.2,None,1.5,None,12.1,None,1.6,None,11.7,None,1.8,None,39.1,None,3.5,None,153750,None,11191,None,248577,None,23076,None,31.5,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),6847,None,630,None,0.5,None,0.6,None,2.1,None,1.9,None,1.1,None,1.1,None,0.9,None,0.7,None,3.1,None,2.1,None,3.3,None,1.7,None,3.9,None,1.8,None,8.3,None,2.8,None,13.6,None,3.2,None,63.2,None,4.9,None,250001,"250,000+",-333333333,***,416996,None,52091,None,-888888888,(X),-888888888,(X),39.2,None,-888888888.0,(X),-888888888,(X),-888888888,(X),5896,None,578,None,0.4,None,0.5,None,0.7,None,0.9,None,0.9,None,1.1,None,0.6,None,0.6,None,2.9,None,2.4,None,2.5,None,1.7,None,3.6,None,1.8,None,7.8,None,3.0,None,13.3,None,3.3,None,67.4,None,5.1,None,250001,"250,000+",-333333333,***,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),18233,None,1077,None,10.2,None,2.4,None,3.8,None,2.0,None,4.2,None,1.4,None,2.8,None,1.1,None,5.1,None,1.5,None,11.0,None,3.0,None,8.4,None,2.0,None,14.0,None,1.9,None,11.0,None,2.3,None,29.5,None,4.2,None,117570,None,9771,None,184364,None,26945,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),28.4,None,-888888888.0,(X),860Z200US10003
3,860Z200US10004,ZCTA5 10004,1775,None,384,None,2.3,None,1.6,None,0.0,None,2.2,None,0.3,None,0.5,None,0.3,None,0.5,None,0.3,None,0.5,None,4.6,None,4.9,None,9.9,None,7.5,None,14.1,None,7.8,None,13.4,None,10.1,None,54.8,None,11.5,None,220592,None,53147,None,309645,None,70590,None,42.9,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),799,None,205,None,1.9,None,2.8,None,0.0,None,4.9,None,0.8,None,1.1,None,0.0,None,4.9,None,0.0,None,4.9,None,0.5,None,0.8,None,3.1,None,3.5,None,11.6,None,10.1,None,8.1,None,7.1,None,74.0,None,13.2,None,250001,"250,000+",-333333333,***,394971,None,85515,None,-888888888,(X),-888888888,(X),51.2,None,-888888888.0,(X),-888888888,(X),-888888888,(X),761,None,209,None,2.0,None,2.9,None,0.0,None,5.1,None,0.8,None,1.2,None,0.0,None,5.1,None,0.0,None,5.1,None,0.5,None,0.8,None,2.6,None,3.5,None,12.2,None,10.4,None,5.0,None,4.3,None,76.9,None,13.4,None,250001,"250,000+",-333333333,***,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),976,None,287,None,2.6,None,1.9,None,0.0,None,4.0,None,0.0,None,4.0,None,0.5,None,0.9,None,0.6,None,0.9,None,8.0,None,8.6,None,16.0,None,13.3,None,15.7,None,11.3,None,18.1,None,17.4,None,38.5,None,15.9,None,178034,None,46920,None,238825,None,102272,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),36.2,None,-888888888.0,(X),860Z200US10004
4,860Z200US10005,ZCTA5 10005,5156,None,588,None,0.4,None,0.6,None,1.6,None,1.6,None,0.2,None,0.2,None,2.5,None,2.3,None,5.1,None,3.5,None,4.2,None,2.9,None,7.9,None,4.3,None,12.7,None,4.8,None,13.9,None,5.0,None,51.7,None,7.2,None,211810,None,29291,None,279387,None,30910,None,24.7,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),1432,None,348,None,0.0,None,2.8,None,0.0,None,2.8,None,2.7,None,5.7,None,2.9,None,4.4,None,0.0,None,2.8,None,0.6,None,1.0,None,4.7,None,5.0,None,8.9,None,7.1,None,11.5,None,8.4,None,68.6,None,12.8,None,250001,"250,000+",-333333333,***,391858,None,82109,None,-888888888,(X),-888888888,(X),24.6,None,-888888888.0,(X),-888888888,(X),-888888888,(X),1321,None,346,None,0.0,None,3.0,None,0.0,None,3.0,None,0.0,None,3.0,None,3.2,None,4.7,None,0.0,None,3.0,None,0.7,None,1.0,None,4.8,None,5.5,None,7.6,None,6.7,None,12.4,None,8.9,None,71.2,None,12.3,None,250001,"250,000+",-333333333,***,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),3724,None,587,None,0.5,None,0.9,None,2.1,None,2.2,None,0.2,None,0.3,None,2.3,None,2.7,None,6.0,None,4.2,None,5.6,None,4.0,None,9.0,None,5.5,None,14.1,None,6.2,None,14.8,None,6.7,None,45.2,None,8.8,None,191394,None,32759,None,235868,None,32534,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),24.8,None,-888888888.0,(X),860Z200US10005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,860Z200US11691,ZCTA5 11691,22382,None,914,None,10.7,None,2.3,None,8.8,None,2.0,None,7.7,None,1.6,None,8.4,None,2.0,None,9.1,None,2.1,None,14.6,None,2.7,None,9.2,None,2.4,None,14.5,None,2.3,None,8.4,None,1.9,None,8.5,None,2.3,None,57027,None,6034,None,87977,None,7902,None,60.2,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),14408,None,1081,None,6.4,None,1.8,None,1.9,None,1.1,None,6.8,None,2.1,None,7.6,None,2.1,None,9.3,None,2.1,None,16.3,None,3.4,None,10.1,None,2.8,None,20.2,None,3.1,None,10.9,None,2.8,None,10.4,None,2.9,None,80367,None,9907,None,103179,None,8917,None,-888888888,(X),-888888888,(X),66.8,None,-888888888.0,(X),-888888888,(X),-888888888,(X),8066,None,814,None,3.1,None,2.2,None,1.7,None,1.6,None,2.5,None,2.0,None,6.1,None,2.6,None,6.9,None,2.7,None,14.6,None,4.2,None,10.3,None,3.9,None,26.3,None,5.0,None,13.8,None,4.1,None,14.7,None,4.7,None,109545,None,12182,None,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),7974,None,850,None,19.6,None,5.1,None,21.2,None,5.2,None,9.8,None,2.9,None,11.6,None,3.5,None,9.3,None,4.0,None,13.7,None,4.2,None,4.8,None,2.6,None,6.4,None,2.6,None,2.0,None,2.2,None,1.4,None,1.0,None,23932,None,6554,None,50878,None,14578,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),47.2,None,-888888888.0,(X),860Z200US11691
208,860Z200US11692,ZCTA5 11692,7981,None,468,None,11.7,None,3.6,None,6.8,None,2.5,None,9.8,None,3.5,None,11.2,None,3.3,None,11.1,None,2.5,None,10.1,None,2.9,None,7.9,None,2.7,None,13.2,None,3.9,None,6.9,None,2.4,None,11.3,None,2.9,None,49507,None,7136,None,89324,None,11132,None,55.5,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),5210,None,467,None,9.7,None,3.9,None,4.1,None,2.2,None,7.7,None,2.8,None,8.9,None,3.1,None,11.1,None,2.8,None,10.0,None,3.6,None,7.0,None,3.4,None,19.2,None,5.0,None,7.3,None,2.8,None,15.1,None,4.5,None,69754,None,17276,None,108276,None,16495,None,-888888888,(X),-888888888,(X),55.8,None,-888888888.0,(X),-888888888,(X),-888888888,(X),2451,None,376,None,1.4,None,1.7,None,2.5,None,2.5,None,0.9,None,1.1,None,7.7,None,5.0,None,5.9,None,4.2,None,12.0,None,5.3,None,8.8,None,5.2,None,23.7,None,8.2,None,9.1,None,4.5,None,28.0,None,8.4,None,123649,None,12961,None,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),2771,None,480,None,15.5,None,7.4,None,12.2,None,6.2,None,14.3,None,7.7,None,16.2,None,7.6,None,10.6,None,4.4,None,10.3,None,4.3,None,9.8,None,4.8,None,4.3,None,3.0,None,2.7,None,2.4,None,4.2,None,2.4,None,28584,None,3868,None,50287,None,8500,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),53.9,None,-888888888.0,(X),860Z200US11692
209,860Z200US11693,ZCTA5 11693,5405,None,523,None,8.5,None,4.4,None,4.1,None,2.1,None,7.7,None,3.9,None,9.6,None,4.5,None,10.7,None,4.4,None,11.2,None,3.6,None,11.6,None,3.8,None,16.5,None,5.9,None,9.9,None,2.9,None,10.2,None,3.0,None,67829,None,19053,None,94035,None,9563,None,49.9,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),3487,None,461,None,7.9,None,6.2,None,2.8,None,2.6,None,3.9,None,3.2,None,5.4,None,3.5,None,8.1,None,3.8,None,14.6,None,5.5,None,13.8,None,5.3,None,19.8,None,8.7,None,12.9,None,3.7,None,10.9,None,4.0,None,87813,None,15540,None,104257,None,10944,None,-888888888,(X),-888888888,(X),58.0,None,-888888888.0,(X),-888888888,(X),-888888888,(X),1885,None,360,None,0.0,None,2.1,None,1.5,None,1.6,None,1.0,None,1.5,None,6.9,None,4.6,None,8.0,None,4.7,None,11.0,None,5.6,None,13.1,None,6.7,None,21.9,None,12.1,None,18.0,None,6.1,None,18.7,None,7.2,None,118566,None,7818,None,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),1918,None,350,None,9.7,None,4.7,None,6.5,None,3.6,None,14.6,None,8.9,None,17.3,None,10.4,None,15.4,None,10.1,None,11.5,None,4.8,None,3.9,None,1.9,None,10.4,None,5.8,None,3.6,None,3.8,None,7.0,None,4.6,None,39375,None,12119,None,69336,None,15930,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),35.1,None,-888888888.0,(X),860Z200US11693
210,860Z200US11694,ZCTA5 11694,8046,None,445,None,4.4,None,1.9,None,3.8,None,1.9,None,4.8,None,2.1,None,5.0,None,2.3,None,8.1,None,2.1,None,12.0,None,3.3,None,9.6,None,2.7,None,18.5,None,3.8,None,15.5,None,3.5,None,18.3,None,3.2,None,103792,None,11215,None,131803,None,10971,None,50.5,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),4929,None,461,None,3.0,None,1.9,None,1.0,None,1.3,None,3.9,None,2.5,None,3.1,None,2.5,None,7.1,None,2.8,None,11.5,None,4.6,None,6.7,None,2.9,None,18.6,None,4.7,None,20.1,None,5.0,None,25.1,None,4.6,None,128512,None,28341,None,156862,None,13705,None,-888888888,(X),-888888888,(X),53.6,None,-888888888.0,(X),-888888888,(X),-888888888,(X),3592,None,443,None,1.8,None,1.8,None,0.3,None,0.3,None,3.7,None,2.8,None,3.7,None,3.4,None,4.8,None,2.6,None,9.2,None,4.2,None,6.5,None,3.2,None,17.3,None,4.9,None,23.6,None,6.2,None,29.2,None,5.3,None,159135,None,12637,None,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),3117,None,355,None,7.1,None,3.8,None,8.2,None,4.4,None,6.8,None,4.0,None,8.0,None,5.1,None,9.4,None,3.7,None,17.1,None,5.0,None,10.8,None,3.8,None,17.5,None,7.1,None,9.6,None,4.7,None,5.5,None,3.3,None,63546,None,10726,None,88194,None,16572,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),44.0,None,-888888888.0,(X),860Z200US11694
211,860Z200US11697,ZCTA5 11697,1668,None,200,None,4.7,None,3.4,None,1.6,None,1.5,None,3.2,None,2.4,None,3.9,None,3.0,None,5.3,None,3.6,None,11.2,None,4.0,None,8.2,None,3.9,None,16.7,None,5.8,None,14.3,None,6.0,None,30.9,None,10.0,None,134844,None,31149,None,160574,None,19405,None,48.5,None,-888888888.0,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),1055,None,200,None,2.1,None,3.3,None,0.9,None,1.3,None,0.0,None,3.7,None,0.6,None,1.0,None,2.2,None,3.2,None,8.5,None,4.2,None,8.6,None,5.6,None,18.1,None,7.4,None,13.8,None,7.1,None,45.2,None,12.8,None,175708,None,45394,None,195736,None,20599,None,-888888888,(X),-888888888,(X),53.1,None,-888888888.0,(X),-888888888,(X),-888888888,(X),888,None,193,None,0.0,None,4.4,None,0.0,None,4.4,None,0.0,None,4.4,None,0.0,None,4.4,None,2.6,None,3.8,None,8.3,None,4.3,None,7.4,None,5.8,None,15.3,None,7.6,None,13.4,None,7.6,None,52.9,None,14.3,None,213958,None,56456,None,-999999999,N,-999999999,N,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),613,None,148,None,12.7,None,8.8,None,2.9,None,3.4,None,8.8,None,6.6,None,9.6,None,7.6,None,10.8,None,8.5,None,12.1,None,8.4,None,7.5,None,4.7,None,14.2,None,8.5,None,17.9,None,12.2,None,3.4,None,4.0,None,70190,None,38681,None,93762,None,29325,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),37.0,None,-888888888.0,(X),860Z200US11697

In [ ]:

df_income_2023 = json_to_dataframe(response)

In [ ]:
df_income_2023

              ucgid  year S1901_C01_012E S1901_C01_013E
0    860Z200US10001  2023         123393         205444
1    860Z200US10002  2023          46525          93314
2    860Z200US10003  2023         153750         248577
3    860Z200US10004  2023         220592         309645
4    860Z200US10005  2023         211810         279387
..              ...   ...            ...            ...
207  860Z200US11691  2023          57027          87977
208  860Z200US11692  2023          49507          89324
209  860Z200US11693  2023          67829          94035
210  860Z200US11694  2023         103792         131803
211  860Z200US11697  2023         134844         160574

[212 rows x 4 columns]

In [ ]:
df_income_2023 = df_income_2023[['ucgid','S1901_C01_001E','S1901_C01_012E', 'S1901_C01_013E']]
df_income_2023

KeyError: "['S1901_C01_001E'] not in index"

In [ ]:
df_income_2023['year'] = '2023'
df_income_2023

              ucgid S1901_C01_012E S1901_C01_013E  year
0    860Z200US10001         123393         205444  2023
1    860Z200US10002          46525          93314  2023
2    860Z200US10003         153750         248577  2023
3    860Z200US10004         220592         309645  2023
4    860Z200US10005         211810         279387  2023
..              ...            ...            ...   ...
207  860Z200US11691          57027          87977  2023
208  860Z200US11692          49507          89324  2023
209  860Z200US11693          67829          94035  2023
210  860Z200US11694         103792         131803  2023
211  860Z200US11697         134844         160574  2023

[212 rows x 4 columns]

In [ ]:
# prompt: I want to column order changed from ucgid	S1901_C01_012E	S1901_C01_013E	year to ucgid	year S1901_C01_012E	S1901_C01_013E

# Assuming 'sel_df_income_2023' is the DataFrame you want to modify.

new_column_order = ['ucgid', 'year', 'S1901_C01_001E', 'S1901_C01_012E', 'S1901_C01_013E']
df_income_2023 = sel_df_income_2023[new_column_order]

print(df_income_2023.head())

KeyError: "['S1901_C01_001E'] not in index"

In [ ]:
def process_income_response(response, year):
    """
    Convert Census API response to a DataFrame with selected columns and a year column.

    Parameters:
        response: requests.Response object from Census API
        year (str or int): Year of the data

    Returns:
        pd.DataFrame: Cleaned DataFrame with ['ucgid', 'year', 'S1901_C01_012E', 'S1901_C01_013E']
    """
    df = pd.DataFrame(response.json()[1:], columns=response.json()[0])
    df = df[['ucgid', 'S1901_C01_001E','S1901_C01_012E', 'S1901_C01_013E']]
    df['year'] = str(year)
    return df[['ucgid', 'year', 'S1901_C01_001E','S1901_C01_012E', 'S1901_C01_013E']]

#2023

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S1901)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2023 = process_income_response(response, 2023)
print(df_income_2023.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  860Z200US10001  2023          15097         123393         205444
1  860Z200US10002  2023          35771          46525          93314
2  860Z200US10003  2023          25080         153750         248577
3  860Z200US10004  2023           1775         220592         309645
4  860Z200US10005  2023           5156         211810         279387

# 2022

In [ ]:
url = "https://api.census.gov/data/2022/acs/acs5/subject?get=group(S1901)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
response.text

'[["GEO_ID","NAME","S1901_C01_001E","S1901_C01_001EA","S1901_C01_001M","S1901_C01_001MA","S1901_C01_002E","S1901_C01_002EA","S1901_C01_002M","S1901_C01_002MA","S1901_C01_003E","S1901_C01_003EA","S1901_C01_003M","S1901_C01_003MA","S1901_C01_004E","S1901_C01_004EA","S1901_C01_004M","S1901_C01_004MA","S1901_C01_005E","S1901_C01_005EA","S1901_C01_005M","S1901_C01_005MA","S1901_C01_006E","S1901_C01_006EA","S1901_C01_006M","S1901_C01_006MA","S1901_C01_007E","S1901_C01_007EA","S1901_C01_007M","S1901_C01_007MA","S1901_C01_008E","S1901_C01_008EA","S1901_C01_008M","S1901_C01_008MA","S1901_C01_009E","S1901_C01_009EA","S1901_C01_009M","S1901_C01_009MA","S1901_C01_010E","S1901_C01_010EA","S1901_C01_010M","S1901_C01_010MA","S1901_C01_011E","S1901_C01_011EA","S1901_C01_011M","S1901_C01_011MA","S1901_C01_012E","S1901_C01_012EA","S1901_C01_012M","S1901_C01_012MA","S1901_C01_013E","S1901_C01_013EA","S1901_C01_013M","S1901_C01_013MA","S1901_C01_014E","S1901_C01_014EA","S1901_C01_014M","S1901_C01_014MA","S1901_C01_015E","S1901_C01_015EA","S1901_C01_015M","S1901_C01_015MA","S1901_C01_016E","S1901_C01_016EA","S1901_C01_016M","S1901_C01_016MA","S1901_C02_001E","S1901_C02_001EA","S1901_C02_001M","S1901_C02_001MA","S1901_C02_002E","S1901_C02_002EA","S1901_C02_002M","S1901_C02_002MA","S1901_C02_003E","S1901_C02_003EA","S1901_C02_003M","S1901_C02_003MA","S1901_C02_004E","S1901_C02_004EA","S1901_C02_004M","S1901_C02_004MA","S1901_C02_005E","S1901_C02_005EA","S1901_C02_005M","S1901_C02_005MA","S1901_C02_006E","S1901_C02_006EA","S1901_C02_006M","S1901_C02_006MA","S1901_C02_007E","S1901_C02_007EA","S1901_C02_007M","S1901_C02_007MA","S1901_C02_008E","S1901_C02_008EA","S1901_C02_008M","S1901_C02_008MA","S1901_C02_009E","S1901_C02_009EA","S1901_C02_009M","S1901_C02_009MA","S1901_C02_010E","S1901_C02_010EA","S1901_C02_010M","S1901_C02_010MA","S1901_C02_011E","S1901_C02_011EA","S1901_C02_011M","S1901_C02_011MA","S1901_C02_012E","S1901_C02_012EA","S1901_C02_012M","S1901_C02_012MA","S1901_C02_013E","S1901_C02_013EA","S1901_C02_013M","S1901_C02_013MA","S1901_C02_014E","S1901_C02_014EA","S1901_C02_014M","S1901_C02_014MA","S1901_C02_015E","S1901_C02_015EA","S1901_C02_015M","S1901_C02_015MA","S1901_C02_016E","S1901_C02_016EA","S1901_C02_016M","S1901_C02_016MA","S1901_C03_001E","S1901_C03_001EA","S1901_C03_001M","S1901_C03_001MA","S1901_C03_002E","S1901_C03_002EA","S1901_C03_002M","S1901_C03_002MA","S1901_C03_003E","S1901_C03_003EA","S1901_C03_003M","S1901_C03_003MA","S1901_C03_004E","S1901_C03_004EA","S1901_C03_004M","S1901_C03_004MA","S1901_C03_005E","S1901_C03_005EA","S1901_C03_005M","S1901_C03_005MA","S1901_C03_006E","S1901_C03_006EA","S1901_C03_006M","S1901_C03_006MA","S1901_C03_007E","S1901_C03_007EA","S1901_C03_007M","S1901_C03_007MA","S1901_C03_008E","S1901_C03_008EA","S1901_C03_008M","S1901_C03_008MA","S1901_C03_009E","S1901_C03_009EA","S1901_C03_009M","S1901_C03_009MA","S1901_C03_010E","S1901_C03_010EA","S1901_C03_010M","S1901_C03_010MA","S1901_C03_011E","S1901_C03_011EA","S1901_C03_011M","S1901_C03_011MA","S1901_C03_012E","S1901_C03_012EA","S1901_C03_012M","S1901_C03_012MA","S1901_C03_013E","S1901_C03_013EA","S1901_C03_013M","S1901_C03_013MA","S1901_C03_014E","S1901_C03_014EA","S1901_C03_014M","S1901_C03_014MA","S1901_C03_015E","S1901_C03_015EA","S1901_C03_015M","S1901_C03_015MA","S1901_C03_016E","S1901_C03_016EA","S1901_C03_016M","S1901_C03_016MA","S1901_C04_001E","S1901_C04_001EA","S1901_C04_001M","S1901_C04_001MA","S1901_C04_002E","S1901_C04_002EA","S1901_C04_002M","S1901_C04_002MA","S1901_C04_003E","S1901_C04_003EA","S1901_C04_003M","S1901_C04_003MA","S1901_C04_004E","S1901_C04_004EA","S1901_C04_004M","S1901_C04_004MA","S1901_C04_005E","S1901_C04_005EA","S1901_C04_005M","S1901_C04_005MA","S1901_C04_006E","S1901_C04_006EA","S1901_C04_006M","S1901_C04_006MA","S1901_C04_007E","S1901_C04_007EA","S1901_C04_007M","S1901_C04_007MA","S1901_C04_008E","S1901_C04_008EA","S1901_C04_008M","S1901_C04_008MA","S1901_C04_009E","S1901_C04_009EA","S1901_C04_009M","S1901_C04_009MA","S1901_C04_010E","S1901_C04_010EA","S1901_C04_010M","S1901_C04_010MA","S1901_C04_011E","S1901_C04_011EA","S1901_C04_011M","S1901_C04_011MA","S1901_C04_012E","S1901_C04_012EA","S1901_C04_012M","S1901_C04_012MA","S1901_C04_013E","S1901_C04_013EA","S1901_C04_013M","S1901_C04_013MA","S1901_C04_014E","S1901_C04_014EA","S1901_C04_014M","S1901_C04_014MA","S1901_C04_015E","S1901_C04_015EA","S1901_C04_015M","S1901_C04_015MA","S1901_C04_016E","S1901_C04_016EA","S1901_C04_016M","S1901_C04_016MA","ucgid"],\n["860Z200US10001","ZCTA5 10001","14375",null,"782",null,"5.1",null,"1.6",null,"6.2",null,"2.3",null,"4.8",null,"1.8",null,"5.7",null,"2.1",null,"6.6",null,"1.9",null,"11.5",null,"2.6",null,"7.8",null,"2.0",null,"13.7",null,"2.7",null,"8.2",null,"2.1",null,"30.3",null,"2.9",null,"106509",null,"9423",null,"176483",null,"12890",null,"23.4",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","4052",null,"505",null,"4.5",null,"2.7",null,"2.9",null,"3.4",null,"5.3",null,"4.1",null,"6.9",null,"4.3",null,"3.2",null,"1.7",null,"9.0",null,"5.1",null,"4.0",null,"2.2",null,"9.5",null,"4.3",null,"10.1",null,"4.2",null,"44.5",null,"5.9",null,"162877",null,"24538",null,"249866",null,"29598",null,"-888888888","(X)","-888888888","(X)","29.6",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","2779",null,"467",null,"0.9",null,"1.6",null,"1.7",null,"2.7",null,"4.5",null,"5.0",null,"5.3",null,"4.9",null,"4.1",null,"2.3",null,"3.0",null,"2.7",null,"2.7",null,"2.0",null,"9.1",null,"4.9",null,"14.1",null,"5.9",null,"54.6",null,"8.6",null,"213309",null,"41776",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10323",null,"776",null,"5.6",null,"2.1",null,"8.2",null,"2.9",null,"4.8",null,"1.9",null,"5.2",null,"2.3",null,"7.3",null,"2.2",null,"12.3",null,"3.1",null,"9.6",null,"2.6",null,"15.0",null,"3.3",null,"7.4",null,"2.3",null,"24.8",null,"3.6",null,"95064",null,"8531",null,"146235",null,"13967",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","21.0",null,"-888888888.0","(X)","860Z200US10001"],\n["860Z200US10002","ZCTA5 10002","36028",null,"1326",null,"10.2",null,"1.8",null,"11.7",null,"2.4",null,"13.2",null,"2.1",null,"9.2",null,"2.3",null,"9.6",null,"1.6",null,"10.2",null,"1.6",null,"9.2",null,"1.3",null,"11.7",null,"1.4",null,"4.9",null,"1.1",null,"10.2",null,"1.2",null,"43362",null,"5737",null,"86843",null,"5853",null,"41.4",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","17022",null,"949",null,"6.7",null,"1.9",null,"7.3",null,"3.6",null,"13.8",null,"3.2",null,"11.7",null,"4.1",null,"12.4",null,"2.9",null,"11.9",null,"2.3",null,"8.8",null,"1.8",null,"10.8",null,"1.9",null,"4.9",null,"1.5",null,"11.6",null,"1.9",null,"46207",null,"5920",null,"95651",null,"9583",null,"-888888888","(X)","-888888888","(X)","46.0",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","9953",null,"768",null,"2.5",null,"1.3",null,"8.2",null,"6.0",null,"13.7",null,"4.5",null,"12.4",null,"6.6",null,"9.5",null,"2.9",null,"8.5",null,"2.2",null,"8.5",null,"2.8",null,"14.1",null,"3.1",null,"6.1",null,"2.4",null,"16.5",null,"2.6",null,"59988",null,"15624",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","19006",null,"1177",null,"13.7",null,"2.9",null,"15.7",null,"3.1",null,"12.4",null,"3.2",null,"7.0",null,"2.1",null,"7.5",null,"1.7",null,"8.3",null,"2.2",null,"9.8",null,"2.0",null,"12.2",null,"2.1",null,"4.7",null,"1.4",null,"8.7",null,"1.9",null,"38297",null,"8171",null,"77823",null,"7804",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","37.3",null,"-888888888.0","(X)","860Z200US10002"],\n["860Z200US10003","ZCTA5 10003","24987",null,"936",null,"7.2",null,"1.8",null,"3.1",null,"1.5",null,"3.0",null,"0.9",null,"3.0",null,"1.2",null,"4.3",null,"1.7",null,"9.7",null,"2.3",null,"7.2",null,"1.2",null,"11.6",null,"1.7",null,"12.2",null,"1.8",null,"38.7",null,"3.2",null,"152863",null,"10149",null,"250384",null,"21612",null,"31.0",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","6718",null,"690",null,"2.5",null,"2.5",null,"0.5",null,"0.6",null,"0.4",null,"0.8",null,"2.6",null,"1.9",null,"0.5",null,"0.6",null,"3.8",null,"2.0",null,"3.4",null,"1.6",null,"8.8",null,"2.4",null,"14.5",null,"3.6",null,"62.9",null,"5.0",null,"250001","250,000+","-333333333","***","419389",null,"52783",null,"-888888888","(X)","-888888888","(X)","38.7",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","5839",null,"607",null,"0.7",null,"0.9",null,"0.0",null,"0.7",null,"0.5",null,"0.9",null,"2.7",null,"2.2",null,"0.1",null,"0.2",null,"3.0",null,"2.2",null,"3.3",null,"1.7",null,"8.3",null,"2.6",null,"14.1",null,"3.7",null,"67.3",null,"5.3",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","18269",null,"960",null,"8.9",null,"2.3",null,"4.1",null,"2.0",null,"4.0",null,"1.2",null,"3.1",null,"1.2",null,"5.7",null,"2.4",null,"11.8",null,"3.0",null,"8.6",null,"1.6",null,"12.8",null,"2.1",null,"11.5",null,"2.1",null,"29.4",null,"3.8",null,"113669",null,"12837",null,"187413",null,"23917",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","28.0",null,"-888888888.0","(X)","860Z200US10003"],\n["860Z200US10004","ZCTA5 10004","2123",null,"394",null,"1.6",null,"1.4",null,"0.0",null,"1.9",null,"0.1",null,"0.2",null,"1.5",null,"1.4",null,"0.1",null,"0.2",null,"3.5",null,"3.6",null,"7.2",null,"5.8",null,"16.2",null,"6.4",null,"11.9",null,"8.6",null,"57.9",null,"8.1",null,"232543",null,"14137",null,"342833",null,"90255",null,"40.8",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1006",null,"291",null,"1.3",null,"2.0",null,"0.0",null,"3.9",null,"0.3",null,"0.5",null,"1.5",null,"2.3",null,"0.0",null,"3.9",null,"0.3",null,"0.4",null,"3.1",null,"3.3",null,"12.9",null,"10.0",null,"2.9",null,"2.6",null,"77.7",null,"10.2",null,"250001","250,000+","-333333333","***","468231",null,"161137",null,"-888888888","(X)","-888888888","(X)","54.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","984",null,"289",null,"1.3",null,"2.0",null,"0.0",null,"4.0",null,"0.3",null,"0.5",null,"1.5",null,"2.3",null,"0.0",null,"4.0",null,"0.3",null,"0.4",null,"2.8",null,"3.4",null,"13.2",null,"10.2",null,"1.8",null,"2.3",null,"78.7",null,"10.4",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1117",null,"322",null,"1.8",null,"1.7",null,"0.0",null,"3.5",null,"0.0",null,"3.5",null,"1.5",null,"1.6",null,"0.2",null,"0.5",null,"6.4",null,"7.1",null,"11.1",null,"10.5",null,"18.8",null,"10.7",null,"21.0",null,"15.7",null,"39.1",null,"13.4",null,"171998",null,"19028",null,"228130",null,"79688",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","28.8",null,"-888888888.0","(X)","860Z200US10004"],\n["860Z200US10005","ZCTA5 10005","4881",null,"550",null,"1.0",null,"1.1",null,"1.8",null,"2.2",null,"0.1",null,"0.2",null,"1.4",null,"1.8",null,"4.6",null,"4.0",null,"3.3",null,"2.5",null,"8.6",null,"3.8",null,"17.0",null,"5.4",null,"13.6",null,"5.3",null,"48.5",null,"7.4",null,"189886",null,"29192",null,"251095",null,"27079",null,"24.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1272",null,"318",null,"0.0",null,"3.1",null,"0.0",null,"3.1",null,"3.6",null,"5.9",null,"0.0",null,"3.1",null,"0.0",null,"3.1",null,"0.0",null,"3.1",null,"6.7",null,"5.4",null,"15.9",null,"9.0",null,"15.6",null,"10.6",null,"58.2",null,"13.6",null,"250001","250,000+","-333333333","***","350854",null,"73447",null,"-888888888","(X)","-888888888","(X)","27.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1078",null,"305",null,"0.0",null,"3.6",null,"0.0",null,"3.6",null,"0.0",null,"3.6",null,"0.0",null,"3.6",null,"0.0",null,"3.6",null,"0.0",null,"3.6",null,"7.2",null,"6.4",null,"14.4",null,"9.3",null,"18.5",null,"12.1",null,"59.9",null,"15.4",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","3609",null,"520",null,"1.3",null,"1.5",null,"2.4",null,"3.1",null,"0.2",null,"0.2",null,"1.9",null,"2.5",null,"4.9",null,"4.9",null,"4.5",null,"3.4",null,"9.3",null,"4.8",null,"17.5",null,"7.0",null,"12.9",null,"6.3",null,"45.1",null,"9.2",null,"188117",null,"23891",null,"215618",null,"27358",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","23.4",null,"-888888888.0","(X)","860Z200US10005"],\n["860Z200US10006","ZCTA5 10006","2046",null,"254",null,"3.1",null,"2.1",null,"0.0",null,"1.9",null,"2.2",null,"3.5",null,"3.0",null,"3.2",null,"7.3",null,"5.0",null,"5.8",null,"4.3",null,"4.6",null,"4.2",null,"10.3",null,"5.2",null,"11.2",null,"6.2",null,"52.5",null,"9.9",null,"204574",null,"22309",null,"218507",null,"29701",null,"27.6",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","808",null,"268",null,"2.8",null,"3.4",null,"0.0",null,"4.8",null,"5.6",null,"8.9",null,"0.0",null,"4.8",null,"0.0",null,"4.8",null,"0.0",null,"4.8",null,"1.9",null,"3.3",null,"6.6",null,"6.8",null,"10.3",null,"10.3",null,"72.9",null,"14.7",null,"236742",null,"23114",null,"281987",null,"48907",null,"-888888888","(X)","-888888888","(X)","29.6",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","586",null,"241",null,"0.0",null,"6.6",null,"0.0",null,"6.6",null,"0.0",null,"6.6",null,"0.0",null,"6.6",null,"0.0",null,"6.6",null,"0.0",null,"6.6",null,"2.6",null,"4.5",null,"4.8",null,"7.3",null,"6.1",null,"7.2",null,"86.5",null,"11.0",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1238",null,"208",null,"3.3",null,"3.0",null,"0.0",null,"3.2",null,"0.0",null,"3.2",null,"4.9",null,"5.4",null,"12.1",null,"7.7",null,"9.6",null,"6.7",null,"6.4",null,"6.7",null,"12.7",null,"7.5",null,"11.8",null,"7.3",null,"39.2",null,"13.3",null,"163382",null,"62465",null,"177075",null,"32188",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","26.3",null,"-888888888.0","(X)","860Z200US10006"],\n["860Z200US10007","ZCTA5 10007","3084",null,"503",null,"3.0",null,"1.9",null,"1.3",null,"2.0",null,"0.0",null,"1.3",null,"1.8",null,"2.3",null,"1.4",null,"1.2",null,"2.8",null,"2.5",null,"2.6",null,"2.5",null,"4.6",null,"4.1",null,"15.2",null,"7.4",null,"67.4",null,"8.3",null,"250001","250,000+","-333333333","***","483196",null,"112668",null,"32.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1612",null,"399",null,"0.5",null,"1.1",null,"0.0",null,"2.4",null,"0.0",null,"2.4",null,"0.0",null,"2.4",null,"1.1",null,"1.7",null,"1.2",null,"2.3",null,"3.8",null,"4.5",null,"3.6",null,"5.3",null,"8.7",null,"7.1",null,"81.0",null,"10.2",null,"250001","250,000+","-333333333","***","660349",null,"188871",null,"-888888888","(X)","-888888888","(X)","28.9",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1498",null,"421",null,"0.5",null,"1.2",null,"0.0",null,"2.6",null,"0.0",null,"2.6",null,"0.0",null,"2.6",null,"1.1",null,"1.9",null,"1.3",null,"2.5",null,"4.1",null,"4.9",null,"0.0",null,"2.6",null,"8.3",null,"7.4",null,"84.6",null,"8.9",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1472",null,"323",null,"5.6",null,"4.2",null,"2.8",null,"4.2",null,"0.0",null,"2.7",null,"3.8",null,"4.8",null,"1.8",null,"1.6",null,"4.4",null,"4.5",null,"1.2",null,"2.0",null,"5.6",null,"6.3",null,"22.4",null,"13.8",null,"52.4",null,"13.6",null,"204000",null,"31647",null,"280763",null,"62976",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","36.3",null,"-888888888.0","(X)","860Z200US10007"],\n["860Z200US10009","ZCTA5 10009","29670",null,"1202",null,"11.9",null,"2.1",null,"6.0",null,"1.6",null,"7.0",null,"1.5",null,"4.3",null,"1.1",null,"6.0",null,"1.3",null,"12.2",null,"2.0",null,"9.0",null,"1.9",null,"14.7",null,"2.3",null,"9.8",null,"2.4",null,"19.1",null,"2.9",null,"83344",null,"8153",null,"130249",null,"11189",null,"30.2",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10366",null,"956",null,"7.4",null,"2.4",null,"4.9",null,"3.2",null,"8.2",null,"2.0",null,"6.2",null,"2.0",null,"8.9",null,"2.6",null,"10.8",null,"2.6",null,"6.2",null,"2.6",null,"7.4",null,"3.1",null,"11.0",null,"3.9",null,"29.1",null,"6.1",null,"87197",null,"23140",null,"170784",null,"26048",null,"-888888888","(X)","-888888888","(X)","35.4",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","5946",null,"882",null,"3.5",null,"1.6",null,"5.1",null,"4.9",null,"4.7",null,"1.8",null,"6.1",null,"2.7",null,"4.3",null,"2.5",null,"6.5",null,"2.7",null,"5.2",null,"3.1",null,"7.3",null,"4.5",null,"16.4",null,"5.9",null,"40.8",null,"8.7",null,"168000",null,"21818",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","19304",null,"1210",null,"14.5",null,"2.9",null,"7.3",null,"2.4",null,"6.5",null,"2.0",null,"3.5",null,"1.1",null,"4.4",null,"1.2",null,"12.3",null,"2.5",null,"10.9",null,"2.5",null,"17.8",null,"3.0",null,"9.7",null,"2.9",null,"13.1",null,"3.0",null,"79870",null,"9761",null,"103372",null,"8334",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","27.0",null,"-888888888.0","(X)","860Z200US10009"],\n["860Z200US10010","ZCTA5 10010","16050",null,"1244",null,"4.5",null,"1.5",null,"3.3",null,"2.7",null,"3.6",null,"1.8",null,"3.3",null,"1.7",null,"4.2",null,"1.5",null,"7.2",null,"2.3",null,"7.9",null,"2.5",null,"15.9",null,"3.3",null,"9.0",null,"2.2",null,"41.0",null,"3.9",null,"150288",null,"23588",null,"254222",null,"33683",null,"33.6",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","6619",null,"913",null,"1.7",null,"0.6",null,"3.0",null,"4.5",null,"1.6",null,"1.6",null,"0.6",null,"0.7",null,"3.5",null,"2.3",null,"6.1",null,"3.2",null,"5.5",null,"4.0",null,"10.7",null,"4.7",null,"9.3",null,"2.6",null,"58.0",null,"7.2",null,"217464",null,"35412",null,"352311",null,"68055",null,"-888888888","(X)","-888888888","(X)","38.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","5249",null,"807",null,"0.0",null,"0.8",null,"0.0",null,"0.8",null,"1.8",null,"2.0",null,"0.8",null,"0.9",null,"3.5",null,"2.7",null,"0.9",null,"1.0",null,"6.6",null,"4.8",null,"12.3",null,"6.0",null,"7.9",null,"3.1",null,"66.2",null,"7.0",null,"246277",null,"33121",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","9431",null,"955",null,"6.4",null,"2.3",null,"3.5",null,"3.6",null,"5.0",null,"2.8",null,"5.3",null,"2.8",null,"4.8",null,"2.1",null,"8.8",null,"3.5",null,"8.8",null,"2.9",null,"19.6",null,"4.6",null,"8.8",null,"3.0",null,"29.1",null,"5.6",null,"113699",null,"10221",null,"184720",null,"28295",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","30.1",null,"-888888888.0","(X)","860Z200US10010"],\n["860Z200US10011","ZCTA5 10011","28874",null,"1301",null,"5.2",

In [ ]:
df_income_2022 = process_income_response(response, 2022)
print(df_income_2022.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  860Z200US10001  2022          14375         106509         176483
1  860Z200US10002  2022          36028          43362          86843
2  860Z200US10003  2022          24987         152863         250384
3  860Z200US10004  2022           2123         232543         342833
4  860Z200US10005  2022           4881         189886         251095

# 2021

In [ ]:
url = "https://api.census.gov/data/2021/acs/acs5/subject?get=group(S1901)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
response.text

'[["GEO_ID","NAME","S1901_C01_001E","S1901_C01_001EA","S1901_C01_001M","S1901_C01_001MA","S1901_C01_002E","S1901_C01_002EA","S1901_C01_002M","S1901_C01_002MA","S1901_C01_003E","S1901_C01_003EA","S1901_C01_003M","S1901_C01_003MA","S1901_C01_004E","S1901_C01_004EA","S1901_C01_004M","S1901_C01_004MA","S1901_C01_005E","S1901_C01_005EA","S1901_C01_005M","S1901_C01_005MA","S1901_C01_006E","S1901_C01_006EA","S1901_C01_006M","S1901_C01_006MA","S1901_C01_007E","S1901_C01_007EA","S1901_C01_007M","S1901_C01_007MA","S1901_C01_008E","S1901_C01_008EA","S1901_C01_008M","S1901_C01_008MA","S1901_C01_009E","S1901_C01_009EA","S1901_C01_009M","S1901_C01_009MA","S1901_C01_010E","S1901_C01_010EA","S1901_C01_010M","S1901_C01_010MA","S1901_C01_011E","S1901_C01_011EA","S1901_C01_011M","S1901_C01_011MA","S1901_C01_012E","S1901_C01_012EA","S1901_C01_012M","S1901_C01_012MA","S1901_C01_013E","S1901_C01_013EA","S1901_C01_013M","S1901_C01_013MA","S1901_C01_014E","S1901_C01_014EA","S1901_C01_014M","S1901_C01_014MA","S1901_C01_015E","S1901_C01_015EA","S1901_C01_015M","S1901_C01_015MA","S1901_C01_016E","S1901_C01_016EA","S1901_C01_016M","S1901_C01_016MA","S1901_C02_001E","S1901_C02_001EA","S1901_C02_001M","S1901_C02_001MA","S1901_C02_002E","S1901_C02_002EA","S1901_C02_002M","S1901_C02_002MA","S1901_C02_003E","S1901_C02_003EA","S1901_C02_003M","S1901_C02_003MA","S1901_C02_004E","S1901_C02_004EA","S1901_C02_004M","S1901_C02_004MA","S1901_C02_005E","S1901_C02_005EA","S1901_C02_005M","S1901_C02_005MA","S1901_C02_006E","S1901_C02_006EA","S1901_C02_006M","S1901_C02_006MA","S1901_C02_007E","S1901_C02_007EA","S1901_C02_007M","S1901_C02_007MA","S1901_C02_008E","S1901_C02_008EA","S1901_C02_008M","S1901_C02_008MA","S1901_C02_009E","S1901_C02_009EA","S1901_C02_009M","S1901_C02_009MA","S1901_C02_010E","S1901_C02_010EA","S1901_C02_010M","S1901_C02_010MA","S1901_C02_011E","S1901_C02_011EA","S1901_C02_011M","S1901_C02_011MA","S1901_C02_012E","S1901_C02_012EA","S1901_C02_012M","S1901_C02_012MA","S1901_C02_013E","S1901_C02_013EA","S1901_C02_013M","S1901_C02_013MA","S1901_C02_014E","S1901_C02_014EA","S1901_C02_014M","S1901_C02_014MA","S1901_C02_015E","S1901_C02_015EA","S1901_C02_015M","S1901_C02_015MA","S1901_C02_016E","S1901_C02_016EA","S1901_C02_016M","S1901_C02_016MA","S1901_C03_001E","S1901_C03_001EA","S1901_C03_001M","S1901_C03_001MA","S1901_C03_002E","S1901_C03_002EA","S1901_C03_002M","S1901_C03_002MA","S1901_C03_003E","S1901_C03_003EA","S1901_C03_003M","S1901_C03_003MA","S1901_C03_004E","S1901_C03_004EA","S1901_C03_004M","S1901_C03_004MA","S1901_C03_005E","S1901_C03_005EA","S1901_C03_005M","S1901_C03_005MA","S1901_C03_006E","S1901_C03_006EA","S1901_C03_006M","S1901_C03_006MA","S1901_C03_007E","S1901_C03_007EA","S1901_C03_007M","S1901_C03_007MA","S1901_C03_008E","S1901_C03_008EA","S1901_C03_008M","S1901_C03_008MA","S1901_C03_009E","S1901_C03_009EA","S1901_C03_009M","S1901_C03_009MA","S1901_C03_010E","S1901_C03_010EA","S1901_C03_010M","S1901_C03_010MA","S1901_C03_011E","S1901_C03_011EA","S1901_C03_011M","S1901_C03_011MA","S1901_C03_012E","S1901_C03_012EA","S1901_C03_012M","S1901_C03_012MA","S1901_C03_013E","S1901_C03_013EA","S1901_C03_013M","S1901_C03_013MA","S1901_C03_014E","S1901_C03_014EA","S1901_C03_014M","S1901_C03_014MA","S1901_C03_015E","S1901_C03_015EA","S1901_C03_015M","S1901_C03_015MA","S1901_C03_016E","S1901_C03_016EA","S1901_C03_016M","S1901_C03_016MA","S1901_C04_001E","S1901_C04_001EA","S1901_C04_001M","S1901_C04_001MA","S1901_C04_002E","S1901_C04_002EA","S1901_C04_002M","S1901_C04_002MA","S1901_C04_003E","S1901_C04_003EA","S1901_C04_003M","S1901_C04_003MA","S1901_C04_004E","S1901_C04_004EA","S1901_C04_004M","S1901_C04_004MA","S1901_C04_005E","S1901_C04_005EA","S1901_C04_005M","S1901_C04_005MA","S1901_C04_006E","S1901_C04_006EA","S1901_C04_006M","S1901_C04_006MA","S1901_C04_007E","S1901_C04_007EA","S1901_C04_007M","S1901_C04_007MA","S1901_C04_008E","S1901_C04_008EA","S1901_C04_008M","S1901_C04_008MA","S1901_C04_009E","S1901_C04_009EA","S1901_C04_009M","S1901_C04_009MA","S1901_C04_010E","S1901_C04_010EA","S1901_C04_010M","S1901_C04_010MA","S1901_C04_011E","S1901_C04_011EA","S1901_C04_011M","S1901_C04_011MA","S1901_C04_012E","S1901_C04_012EA","S1901_C04_012M","S1901_C04_012MA","S1901_C04_013E","S1901_C04_013EA","S1901_C04_013M","S1901_C04_013MA","S1901_C04_014E","S1901_C04_014EA","S1901_C04_014M","S1901_C04_014MA","S1901_C04_015E","S1901_C04_015EA","S1901_C04_015M","S1901_C04_015MA","S1901_C04_016E","S1901_C04_016EA","S1901_C04_016M","S1901_C04_016MA","ucgid"],\n["860Z200US10001","ZCTA5 10001","14273",null,"830",null,"7.2",null,"1.9",null,"3.4",null,"1.1",null,"5.4",null,"2.2",null,"3.3",null,"1.1",null,"7.4",null,"2.2",null,"11.5",null,"2.8",null,"11.2",null,"2.2",null,"14.9",null,"2.8",null,"10.5",null,"2.3",null,"25.2",null,"3.3",null,"101409",null,"11816",null,"170154",null,"17586",null,"22.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","4256",null,"524",null,"7.3",null,"3.8",null,"0.0",null,"0.9",null,"4.5",null,"3.9",null,"3.3",null,"2.2",null,"7.5",null,"5.2",null,"9.8",null,"4.7",null,"7.8",null,"3.1",null,"12.1",null,"5.2",null,"7.9",null,"4.0",null,"39.8",null,"7.4",null,"142042",null,"23428",null,"258526",null,"53596",null,"-888888888","(X)","-888888888","(X)","28.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","2932",null,"498",null,"1.0",null,"1.2",null,"0.0",null,"1.3",null,"4.4",null,"4.7",null,"1.7",null,"2.3",null,"7.8",null,"5.9",null,"6.5",null,"4.7",null,"7.5",null,"3.5",null,"13.0",null,"6.4",null,"10.7",null,"5.0",null,"47.4",null,"9.2",null,"193302",null,"56892",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10017",null,"822",null,"7.3",null,"1.9",null,"4.8",null,"1.5",null,"5.8",null,"2.7",null,"3.4",null,"1.3",null,"7.4",null,"2.4",null,"12.2",null,"3.8",null,"13.0",null,"2.9",null,"15.7",null,"3.2",null,"11.4",null,"2.9",null,"19.0",null,"3.3",null,"89723",null,"9344",null,"131592",null,"11695",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","20.1",null,"-888888888.0","(X)","860Z200US10001"],\n["860Z200US10002","ZCTA5 10002","34737",null,"1319",null,"13.0",null,"2.0",null,"11.8",null,"2.3",null,"12.9",null,"2.1",null,"10.0",null,"2.3",null,"9.1",null,"1.6",null,"11.2",null,"1.7",null,"9.2",null,"1.6",null,"9.2",null,"1.4",null,"4.4",null,"0.9",null,"9.1",null,"1.0",null,"37093",null,"3148",null,"76115",null,"3723",null,"38.3",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","16914",null,"1029",null,"8.3",null,"1.9",null,"8.9",null,"3.9",null,"14.5",null,"2.9",null,"13.1",null,"4.2",null,"11.3",null,"2.6",null,"12.5",null,"2.2",null,"9.0",null,"1.8",null,"8.0",null,"1.9",null,"4.4",null,"1.4",null,"10.1",null,"1.7",null,"38815",null,"4243",null,"82382",null,"7013",null,"-888888888","(X)","-888888888","(X)","41.9",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","10194",null,"859",null,"3.2",null,"1.5",null,"10.0",null,"5.9",null,"13.9",null,"4.5",null,"13.4",null,"6.3",null,"8.6",null,"2.8",null,"10.0",null,"2.6",null,"10.6",null,"2.3",null,"10.8",null,"2.8",null,"5.4",null,"2.1",null,"13.9",null,"2.6",null,"51689",null,"11913",null,"101513",null,"11164",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","17823",null,"1118",null,"18.2",null,"3.3",null,"14.5",null,"2.8",null,"11.1",null,"2.8",null,"7.4",null,"1.9",null,"6.9",null,"1.9",null,"10.0",null,"2.3",null,"9.4",null,"2.3",null,"10.1",null,"2.0",null,"4.3",null,"1.1",null,"8.0",null,"1.7",null,"32489",null,"5961",null,"69003",null,"6056",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","34.8",null,"-888888888.0","(X)","860Z200US10002"],\n["860Z200US10003","ZCTA5 10003","25181",null,"951",null,"6.8",null,"1.8",null,"2.2",null,"0.9",null,"3.3",null,"0.9",null,"4.3",null,"1.1",null,"4.2",null,"1.3",null,"11.9",null,"2.2",null,"6.9",null,"1.3",null,"13.3",null,"1.9",null,"11.8",null,"1.7",null,"35.4",null,"3.2",null,"137533",null,"10077",null,"222765",null,"20794",null,"31.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","6855",null,"575",null,"2.5",null,"1.6",null,"0.7",null,"0.8",null,"1.0",null,"0.8",null,"2.3",null,"2.1",null,"2.6",null,"1.7",null,"4.1",null,"2.6",null,"5.2",null,"1.9",null,"11.4",null,"3.4",null,"15.0",null,"3.6",null,"55.3",null,"5.1",null,"219957",null,"23940",null,"346563",null,"46424",null,"-888888888","(X)","-888888888","(X)","38.0",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","5932",null,"536",null,"0.6",null,"0.7",null,"0.0",null,"0.6",null,"1.1",null,"1.0",null,"2.7",null,"2.5",null,"2.5",null,"1.8",null,"3.6",null,"2.8",null,"5.4",null,"2.1",null,"10.4",null,"3.6",null,"15.4",null,"4.0",null,"58.4",null,"4.9",null,"240365",null,"23664",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","18326",null,"929",null,"8.4",null,"2.4",null,"2.8",null,"1.2",null,"4.2",null,"1.2",null,"4.9",null,"1.3",null,"4.8",null,"1.7",null,"14.7",null,"3.0",null,"7.6",null,"1.7",null,"14.2",null,"2.4",null,"10.7",null,"1.8",null,"27.7",null,"4.2",null,"105808",null,"11134",null,"175535",null,"25914",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","28.5",null,"-888888888.0","(X)","860Z200US10003"],\n["860Z200US10004","ZCTA5 10004","2113",null,"340",null,"2.2",null,"1.5",null,"0.0",null,"1.8",null,"0.9",null,"1.2",null,"1.6",null,"1.6",null,"0.4",null,"0.4",null,"2.0",null,"1.3",null,"6.1",null,"5.7",null,"13.5",null,"6.5",null,"14.8",null,"9.6",null,"58.5",null,"8.6",null,"216017",null,"10041",null,"317203",null,"71063",null,"38.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1062",null,"276",null,"1.5",null,"1.9",null,"0.0",null,"3.5",null,"0.2",null,"0.3",null,"1.6",null,"2.7",null,"0.1",null,"0.4",null,"0.9",null,"1.3",null,"2.3",null,"2.2",null,"7.0",null,"6.5",null,"9.8",null,"7.8",null,"76.6",null,"9.4",null,"247237",null,"19655",null,"412109",null,"129100",null,"-888888888","(X)","-888888888","(X)","50.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1035",null,"273",null,"1.5",null,"2.0",null,"0.0",null,"3.6",null,"0.2",null,"0.3",null,"1.6",null,"2.7",null,"0.1",null,"0.4",null,"1.0",null,"1.3",null,"1.6",null,"2.1",null,"7.1",null,"6.7",null,"8.9",null,"7.9",null,"77.9",null,"9.5",null,"247607",null,"18651",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1051",null,"270",null,"2.9",null,"2.4",null,"0.0",null,"3.5",null,"1.5",null,"2.4",null,"1.6",null,"1.7",null,"0.7",null,"0.7",null,"3.1",null,"2.2",null,"10.6",null,"11.0",null,"19.9",null,"11.2",null,"21.0",null,"17.5",null,"38.7",null,"13.0",null,"159518",null,"16520",null,"218597",null,"78738",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","25.7",null,"-888888888.0","(X)","860Z200US10004"],\n["860Z200US10005","ZCTA5 10005","4782",null,"520",null,"0.9",null,"1.0",null,"0.0",null,"0.8",null,"0.1",null,"0.2",null,"1.4",null,"2.2",null,"2.1",null,"2.2",null,"9.2",null,"4.4",null,"6.1",null,"3.8",null,"15.2",null,"5.6",null,"16.4",null,"5.7",null,"48.5",null,"7.4",null,"197188",null,"17558",null,"225528",null,"20055",null,"22.8",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1311",null,"338",null,"0.0",null,"2.8",null,"0.0",null,"2.8",null,"0.0",null,"2.8",null,"0.0",null,"2.8",null,"0.0",null,"2.8",null,"2.7",null,"4.3",null,"9.0",null,"6.9",null,"10.1",null,"6.5",null,"11.0",null,"7.1",null,"67.1",null,"11.1",null,"250001","250,000+","-333333333","***","298091",null,"50351",null,"-888888888","(X)","-888888888","(X)","25.8",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1146",null,"287",null,"0.0",null,"3.2",null,"0.0",null,"3.2",null,"0.0",null,"3.2",null,"0.0",null,"3.2",null,"0.0",null,"3.2",null,"3.1",null,"4.8",null,"6.3",null,"5.5",null,"11.6",null,"7.7",null,"12.6",null,"8.0",null,"66.4",null,"10.7",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","3471",null,"529",null,"1.3",null,"1.4",null,"0.0",null,"1.1",null,"0.2",null,"0.3",null,"2.0",null,"3.0",null,"2.9",null,"3.0",null,"11.7",null,"5.7",null,"5.0",null,"4.5",null,"17.2",null,"7.1",null,"18.4",null,"7.5",null,"41.4",null,"9.1",null,"185125",null,"27684",null,"198121",null,"22229",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","21.7",null,"-888888888.0","(X)","860Z200US10005"],\n["860Z200US10006","ZCTA5 10006","1991",null,"262",null,"2.0",null,"1.8",null,"0.4",null,"0.7",null,"0.7",null,"1.0",null,"2.6",null,"2.9",null,"7.4",null,"6.0",null,"3.6",null,"3.2",null,"2.0",null,"2.0",null,"13.6",null,"7.3",null,"17.3",null,"6.7",null,"50.5",null,"10.5",null,"200536",null,"24685",null,"222594",null,"27122",null,"19.3",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","854",null,"263",null,"1.6",null,"2.6",null,"0.0",null,"4.3",null,"0.0",null,"4.3",null,"0.0",null,"4.3",null,"0.0",null,"4.3",null,"0.0",null,"4.3",null,"1.9",null,"3.2",null,"12.2",null,"9.8",null,"10.4",null,"8.7",null,"73.9",null,"13.9",null,"218986",null,"58229",null,"272242",null,"44080",null,"-888888888","(X)","-888888888","(X)","25.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","665",null,"248",null,"0.0",null,"5.5",null,"0.0",null,"5.5",null,"0.0",null,"5.5",null,"0.0",null,"5.5",null,"0.0",null,"5.5",null,"0.0",null,"5.5",null,"2.4",null,"4.1",null,"6.5",null,"7.6",null,"13.4",null,"10.7",null,"77.7",null,"14.0",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1137",null,"200",null,"2.2",null,"2.6",null,"0.7",null,"1.1",null,"1.1",null,"1.8",null,"4.5",null,"5.2",null,"12.9",null,"9.9",null,"6.3",null,"5.4",null,"2.0",null,"2.6",null,"14.7",null,"9.8",null,"22.5",null,"10.2",null,"33.0",null,"12.0",null,"165901",null,"47171",null,"185303",null,"33487",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","14.7",null,"-888888888.0","(X)","860Z200US10006"],\n["860Z200US10007","ZCTA5 10007","3246",null,"517",null,"2.9",null,"2.1",null,"1.6",null,"1.9",null,"0.0",null,"1.1",null,"2.2",null,"2.4",null,"1.4",null,"1.3",null,"1.9",null,"2.3",null,"4.4",null,"3.7",null,"7.0",null,"4.7",null,"17.1",null,"7.9",null,"61.4",null,"9.4",null,"250001","250,000+","-333333333","***","444574",null,"104649",null,"33.5",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1789",null,"469",null,"1.1",null,"1.4",null,"0.0",null,"2.1",null,"0.0",null,"2.1",null,"0.0",null,"2.1",null,"0.0",null,"2.1",null,"3.1",null,"3.9",null,"2.7",null,"4.5",null,"9.1",null,"8.0",null,"5.1",null,"5.7",null,"78.9",null,"10.2",null,"250001","250,000+","-333333333","***","586053",null,"162635",null,"-888888888","(X)","-888888888","(X)","34.4",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","1685",null,"471",null,"1.1",null,"1.5",null,"0.0",null,"2.2",null,"0.0",null,"2.2",null,"0.0",null,"2.2",null,"0.0",null,"2.2",null,"3.3",null,"4.2",null,"2.9",null,"4.7",null,"6.4",null,"7.0",null,"4.5",null,"5.4",null,"81.9",null,"11.5",null,"250001","250,000+","-333333333","***","-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","1457",null,"308",null,"5.2",null,"4.0",null,"3.5",null,"4.2",null,"0.0",null,"2.5",null,"4.9",null,"5.2",null,"3.1",null,"3.0",null,"0.5",null,"0.7",null,"6.5",null,"5.4",null,"4.5",null,"5.0",null,"31.8",null,"14.7",null,"40.0",null,"14.3",null,"176892",null,"29658",null,"262977",null,"63267",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","32.4",null,"-888888888.0","(X)","860Z200US10007"],\n["860Z200US10009","ZCTA5 10009","29407",null,"1191",null,"12.4",null,"2.2",null,"7.5",null,"1.4",null,"6.5",null,"1.2",null,"5.0",null,"1.0",null,"7.3",null,"1.8",null,"10.1",null,"2.0",null,"10.1",null,"2.0",null,"13.7",null,"2.2",null,"7.9",null,"2.0",null,"19.6",null,"2.6",null,"77551",null,"8516",null,"122290",null,"9636",null,"26.6",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","10555",null,"1101",null,"8.2",null,"3.1",null,"5.5",null,"3.1",null,"7.4",null,"1.7",null,"5.7",null,"1.3",null,"9.6",null,"3.0",null,"8.0",null,"2.9",null,"4.1",null,"1.8",null,"10.4",null,"3.5",null,"11.0",null,"3.9",null,"29.9",null,"4.8",null,"110010",null,"32737",null,"165376",null,"21616",null,"-888888888","(X)","-888888888","(X)","30.8",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","6300",null,"749",null,"2.5",null,"1.6",null,"5.3",null,"4.7",null,"5.0",null,"2.1",null,"3.5",null,"1.2",null,"5.7",null,"2.7",null,"3.8",null,"2.3",null,"4.6",null,"2.9",null,"12.7",null,"5.7",null,"12.5",null,"5.2",null,"44.6",null,"7.7",null,"176044",null,"27969",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","18852",null,"1253",null,"15.0",null,"2.9",null,"9.2",null,"2.3",null,"6.0",null,"1.7",null,"4.9",null,"1.4",null,"5.2",null,"1.6",null,"11.7",null,"2.6",null,"13.2",null,"3.1",null,"15.6",null,"3.1",null,"7.3",null,"2.2",null,"11.9",null,"2.9",null,"68564",null,"10704",null,"93822",null,"7944",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","24.1",null,"-888888888.0","(X)","860Z200US10009"],\n["860Z200US10010","ZCTA5 10010","16207",null,"1356",null,"4.4",null,"2.0",null,"4.2",null,"2.8",null,"3.7",null,"1.6",null,"5.6",null,"2.9",null,"7.3",null,"2.9",null,"5.3",null,"1.9",null,"8.6",null,"2.6",null,"15.6",null,"3.4",null,"12.3",null,"4.3",null,"32.9",null,"3.1",null,"131635",null,"18605",null,"217670",null,"20488",null,"34.1",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","6494",null,"894",null,"0.5",null,"0.7",null,"3.9",null,"4.8",null,"3.1",null,"2.4",null,"2.3",null,"2.2",null,"3.3",null,"2.0",null,"3.5",null,"2.3",null,"7.6",null,"4.2",null,"10.9",null,"4.5",null,"14.4",null,"8.5",null,"50.5",null,"7.6",null,"207683",null,"31988",null,"315476",null,"41846",null,"-888888888","(X)","-888888888","(X)","35.7",null,"-888888888.0","(X)","-888888888","(X)","-888888888","(X)","5252",null,"776",null,"0.6",null,"0.9",null,"0.0",null,"0.7",null,"3.6",null,"2.9",null,"1.5",null,"1.4",null,"3.0",null,"2.4",null,"1.3",null,"1.1",null,"7.7",null,"4.4",null,"9.6",null,"4.8",null,"15.9",null,"10.0",null,"56.9",null,"8.5",null,"241176",null,"43897",null,"-999999999","N","-999999999","N","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","9713",null,"894",null,"7.1",null,"3.4",null,"4.4",null,"3.1",null,"4.1",null,"2.3",null,"7.8",null,"4.5",null,"9.9",null,"4.5",null,"7.3",null,"3.0",null,"8.6",null,"3.1",null,"18.8",null,"4.7",null,"11.0",null,"3.7",null,"21.1",null,"3.8",null,"100658",null,"8566",null,"151672",null,"21717",null,"-888888888","(X)","-888888888","(X)","-888888888","(X)","-888888888","(X)","32.9",null,"-888888888.0","(X)","860Z200US10010"],\n["860Z200US10011","ZCTA5 10011","29222",null,"1342",null,"5.2",null,"1.3",null,"3.7",null,"1.2",null

In [ ]:
df_income_2021 = process_income_response(response, 2021)
print(df_income_2021.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  860Z200US10001  2021          14273         101409         170154
1  860Z200US10002  2021          34737          37093          76115
2  860Z200US10003  2021          25181         137533         222765
3  860Z200US10004  2021           2113         216017         317203
4  860Z200US10005  2021           4782         197188         225528

#2020

In [ ]:
url = "https://api.census.gov/data/2020/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2020 = process_income_response(response, 2020)
print(df_income_2020.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2020          13311          96787         166167
1  8600000US10002  2020          33790          35607          70204
2  8600000US10003  2020          25158         129981         211756
3  8600000US10004  2020           1822         204949         325028
4  8600000US10005  2020           4649         184681         218441

#2019

In [ ]:
url = "https://api.census.gov/data/2019/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2019 = process_income_response(response, 2019)
print(df_income_2019.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2019          12997          92840         160300
1  8600000US10002  2019          33459          36982          69323
2  8600000US10003  2019          26043         118161         196931
3  8600000US10004  2019           1777         190223         249586
4  8600000US10005  2019           4363         189702         225453

#2018

In [ ]:
url = "https://api.census.gov/data/2018/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2018 = process_income_response(response, 2018)
print(df_income_2018.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2018          12431          88526         151628
1  8600000US10002  2018          33540          35859          68315
2  8600000US10003  2018          26124         112131         189885
3  8600000US10004  2018           1659         157645         218650
4  8600000US10005  2018           4374         173333         208186

#2017

In [ ]:
url = "https://api.census.gov/data/2017/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2017 = process_income_response(response, 2017)
print(df_income_2017.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2017          12347          85221         161227
1  8600000US10002  2017          33461          35449          65718
2  8600000US10003  2017          26699         104441         182531
3  8600000US10004  2017           1587         140450         191760
4  8600000US10005  2017           4239         154213         201734

#2016

In [ ]:
url = "https://api.census.gov/data/2016/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2016 = process_income_response(response, 2016)
print(df_income_2016.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2016          11967          85168         162724
1  8600000US10002  2016          33327          35594          64196
2  8600000US10003  2016          27258         100791         171737
3  8600000US10004  2016           1592         123056         173800
4  8600000US10005  2016           4295         130116         193229

#2015

In [ ]:
url = "https://api.census.gov/data/2015/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2015 = process_income_response(response, 2015)
print(df_income_2015.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2015          11639          86801         158183
1  8600000US10002  2015          33348          33726          61946
2  8600000US10003  2015          27487          98151         161692
3  8600000US10004  2015           1574         119691         177262
4  8600000US10005  2015           4252         124194         176424

#2014

In [ ]:
url = "https://api.census.gov/data/2014/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2014 = process_income_response(response, 2014)
print(df_income_2014.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2014          11169          81445         151316
1  8600000US10002  2014          32550          32966          60564
2  8600000US10003  2014          27564          97524         156983
3  8600000US10004  2014           1580         123409         181042
4  8600000US10005  2014           4100         121840         175864

#2013

In [ ]:
url = "https://api.census.gov/data/2013/acs/acs5/subject?get=group(S1901)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_income_2013 = process_income_response(response, 2013)
print(df_income_2013.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  8600000US10001  2013          11024          81671         157557
1  8600000US10002  2013          32467          33218          60347
2  8600000US10003  2013          27505          92540         146769
3  8600000US10004  2013           1430         129313         206142
4  8600000US10005  2013           3725         124670         178458

In [ ]:
# prompt: I want to merge df_income_2023, df_income_2022, df_income_2021, df_income_2020, df_income_2019, df_income_2018, df_income_2017, df_income_2016, df_income_2015, df_income_2014, df_income_2013

import pandas as pd

# Assuming df_income_2013 to df_income_2023 are already defined DataFrames

dfs = [df_income_2023, df_income_2022, df_income_2021, df_income_2020,
       df_income_2019, df_income_2018, df_income_2017, df_income_2016,
       df_income_2015, df_income_2014, df_income_2013]

# Concatenate the DataFrames vertically (row-wise)
merged_df_income = pd.concat(dfs, ignore_index=True)

print(merged_df_income.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0  860Z200US10001  2023          15097         123393         205444
1  860Z200US10002  2023          35771          46525          93314
2  860Z200US10003  2023          25080         153750         248577
3  860Z200US10004  2023           1775         220592         309645
4  860Z200US10005  2023           5156         211810         279387

In [ ]:
merged_df_income

               ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E
0     860Z200US10001  2023          15097         123393         205444
1     860Z200US10002  2023          35771          46525          93314
2     860Z200US10003  2023          25080         153750         248577
3     860Z200US10004  2023           1775         220592         309645
4     860Z200US10005  2023           5156         211810         279387
...              ...   ...            ...            ...            ...
2343  8600000US11691  2013          18942          39409          56640
2344  8600000US11692  2013           5974          43354          60455
2345  8600000US11693  2013           4518          50570          60995
2346  8600000US11694  2013           8190          76944          93633
2347  8600000US11697  2013           1701          87636         100542

[2348 rows x 5 columns]

# Get median rent and home value data


DP04_0126E - number of rent home \
DP04_0134E - Median rent \
DP04_0080E - number of owned home \
DP04_0089E - Median home value \

#2023

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP04)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_test = json_to_dataframe(response)

In [ ]:
df_test

,DP04_0001E,DP04_0001EA,DP04_0001M,DP04_0001MA,DP04_0001PE,DP04_0001PEA,DP04_0001PM,DP04_0001PMA,DP04_0002E,DP04_0002EA,DP04_0002M,DP04_0002MA,DP04_0002PE,DP04_0002PEA,DP04_0002PM,DP04_0002PMA,DP04_0003E,DP04_0003EA,DP04_0003M,DP04_0003MA,DP04_0003PE,DP04_0003PEA,DP04_0003PM,DP04_0003PMA,DP04_0004E,DP04_0004EA,DP04_0004M,DP04_0004MA,DP04_0004PE,DP04_0004PEA,DP04_0004PM,DP04_0004PMA,DP04_0005E,DP04_0005EA,DP04_0005M,DP04_0005MA,DP04_0005PE,DP04_0005PEA,DP04_0005PM,DP04_0005PMA,DP04_0006E,DP04_0006EA,DP04_0006M,DP04_0006MA,DP04_0006PE,DP04_0006PEA,DP04_0006PM,DP04_0006PMA,DP04_0007E,DP04_0007EA,DP04_0007M,DP04_0007MA,DP04_0007PE,DP04_0007PEA,DP04_0007PM,DP04_0007PMA,DP04_0008E,DP04_0008EA,DP04_0008M,DP04_0008MA,DP04_0008PE,DP04_0008PEA,DP04_0008PM,DP04_0008PMA,DP04_0009E,DP04_0009EA,DP04_0009M,DP04_0009MA,DP04_0009PE,DP04_0009PEA,DP04_0009PM,DP04_0009PMA,DP04_0010E,DP04_0010EA,DP04_0010M,DP04_0010MA,DP04_0010PE,DP04_0010PEA,DP04_0010PM,DP04_0010PMA,DP04_0011E,DP04_0011EA,DP04_0011M,DP04_0011MA,DP04_0011PE,DP04_0011PEA,DP04_0011PM,DP04_0011PMA,DP04_0012E,DP04_0012EA,DP04_0012M,DP04_0012MA,DP04_0012PE,DP04_0012PEA,DP04_0012PM,DP04_0012PMA,DP04_0013E,DP04_0013EA,DP04_0013M,DP04_0013MA,DP04_0013PE,DP04_0013PEA,DP04_0013PM,DP04_0013PMA,DP04_0014E,DP04_0014EA,DP04_0014M,DP04_0014MA,DP04_0014PE,DP04_0014PEA,DP04_0014PM,DP04_0014PMA,DP04_0015E,DP04_0015EA,DP04_0015M,DP04_0015MA,DP04_0015PE,DP04_0015PEA,DP04_0015PM,DP04_0015PMA,DP04_0016E,DP04_0016EA,DP04_0016M,DP04_0016MA,DP04_0016PE,DP04_0016PEA,DP04_0016PM,DP04_0016PMA,DP04_0017E,DP04_0017EA,DP04_0017M,DP04_0017MA,DP04_0017PE,DP04_0017PEA,DP04_0017PM,DP04_0017PMA,DP04_0018E,DP04_0018EA,DP04_0018M,DP04_0018MA,DP04_0018PE,DP04_0018PEA,DP04_0018PM,DP04_0018PMA,DP04_0019E,DP04_0019EA,DP04_0019M,DP04_0019MA,DP04_0019PE,DP04_0019PEA,DP04_0019PM,DP04_0019PMA,DP04_0020E,DP04_0020EA,DP04_0020M,DP04_0020MA,DP04_0020PE,DP04_0020PEA,DP04_0020PM,DP04_0020PMA,DP04_0021E,DP04_0021EA,DP04_0021M,DP04_0021MA,DP04_0021PE,DP04_0021PEA,DP04_0021PM,DP04_0021PMA,DP04_0022E,DP04_0022EA,DP04_0022M,DP04_0022MA,DP04_0022PE,DP04_0022PEA,DP04_0022PM,DP04_0022PMA,DP04_0023E,DP04_0023EA,DP04_0023M,DP04_0023MA,DP04_0023PE,DP04_0023PEA,DP04_0023PM,DP04_0023PMA,DP04_0024E,DP04_0024EA,DP04_0024M,DP04_0024MA,DP04_0024PE,DP04_0024PEA,DP04_0024PM,DP04_0024PMA,DP04_0025E,DP04_0025EA,DP04_0025M,DP04_0025MA,DP04_0025PE,DP04_0025PEA,DP04_0025PM,DP04_0025PMA,DP04_0026E,DP04_0026EA,DP04_0026M,DP04_0026MA,DP04_0026PE,DP04_0026PEA,DP04_0026PM,DP04_0026PMA,DP04_0027E,DP04_0027EA,DP04_0027M,DP04_0027MA,DP04_0027PE,DP04_0027PEA,DP04_0027PM,DP04_0027PMA,DP04_0028E,DP04_0028EA,DP04_0028M,DP04_0028MA,DP04_0028PE,DP04_0028PEA,DP04_0028PM,DP04_0028PMA,DP04_0029E,DP04_0029EA,DP04_0029M,DP04_0029MA,DP04_0029PE,DP04_0029PEA,DP04_0029PM,DP04_0029PMA,DP04_0030E,DP04_0030EA,DP04_0030M,DP04_0030MA,DP04_0030PE,DP04_0030PEA,DP04_0030PM,DP04_0030PMA,DP04_0031E,DP04_0031EA,DP04_0031M,DP04_0031MA,DP04_0031PE,DP04_0031PEA,DP04_0031PM,DP04_0031PMA,DP04_0032E,DP04_0032EA,DP04_0032M,DP04_0032MA,DP04_0032PE,DP04_0032PEA,DP04_0032PM,DP04_0032PMA,DP04_0033E,DP04_0033EA,DP04_0033M,DP04_0033MA,DP04_0033PE,DP04_0033PEA,DP04_0033PM,DP04_0033PMA,DP04_0034E,DP04_0034EA,DP04_0034M,DP04_0034MA,DP04_0034PE,DP04_0034PEA,DP04_0034PM,DP04_0034PMA,DP04_0035E,DP04_0035EA,DP04_0035M,DP04_0035MA,DP04_0035PE,DP04_0035PEA,DP04_0035PM,DP04_0035PMA,DP04_0036E,DP04_0036EA,DP04_0036M,DP04_0036MA,DP04_0036PE,DP04_0036PEA,DP04_0036PM,DP04_0036PMA,DP04_0037E,DP04_0037EA,DP04_0037M,DP04_0037MA,DP04_0037PE,DP04_0037PEA,DP04_0037PM,DP04_0037PMA,DP04_0038E,DP04_0038EA,DP04_0038M,DP04_0038MA,DP04_0038PE,DP04_0038PEA,DP04_0038PM,DP04_0038PMA,DP04_0039E,DP04_0039EA,DP04_0039M,DP04_0039MA,DP04_0039PE,DP04_0039PEA,DP04_0039PM,DP04_0039PMA,DP04_0040E,DP04_0040EA,DP04_0040M,DP04_0040MA,DP04_0040PE,DP04_0040PEA,DP04_0040PM,DP04_0040PMA,DP04_0041E,DP04_0041EA,DP04_0041M,DP04_0041MA,DP04_0041PE,DP04_0041PEA,DP04_0041PM,DP04_0041PMA,DP04_0042E,DP04_0042EA,DP04_0042M,DP04_0042MA,DP04_0042PE,DP04_0042PEA,DP04_0042PM,DP04_0042PMA,DP04_0043E,DP04_0043EA,DP04_0043M,DP04_0043MA,DP04_0043PE,DP04_0043PEA,DP04_0043PM,DP04_0043PMA,DP04_0044E,DP04_0044EA,DP04_0044M,DP04_0044MA,DP04_0044PE,DP04_0044PEA,DP04_0044PM,DP04_0044PMA,DP04_0045E,DP04_0045EA,DP04_0045M,DP04_0045MA,DP04_0045PE,DP04_0045PEA,DP04_0045PM,DP04_0045PMA,DP04_0046E,DP04_0046EA,DP04_0046M,DP04_0046MA,DP04_0046PE,DP04_0046PEA,DP04_0046PM,DP04_0046PMA,DP04_0047E,DP04_0047EA,DP04_0047M,DP04_0047MA,DP04_0047PE,DP04_0047PEA,DP04_0047PM,DP04_0047PMA,DP04_0048E,DP04_0048EA,DP04_0048M,DP04_0048MA,DP04_0048PE,DP04_0048PEA,DP04_0048PM,DP04_0048PMA,DP04_0049E,DP04_0049EA,DP04_0049M,DP04_0049MA,DP04_0049PE,DP04_0049PEA,DP04_0049PM,DP04_0049PMA,DP04_0050E,DP04_0050EA,DP04_0050M,DP04_0050MA,DP04_0050PE,DP04_0050PEA,DP04_0050PM,DP04_0050PMA,DP04_0051E,DP04_0051EA,DP04_0051M,DP04_0051MA,DP04_0051PE,DP04_0051PEA,DP04_0051PM,DP04_0051PMA,DP04_0052E,DP04_0052EA,DP04_0052M,DP04_0052MA,DP04_0052PE,DP04_0052PEA,DP04_0052PM,DP04_0052PMA,DP04_0053E,DP04_0053EA,DP04_0053M,DP04_0053MA,DP04_0053PE,DP04_0053PEA,DP04_0053PM,DP04_0053PMA,DP04_0054E,DP04_0054EA,DP04_0054M,DP04_0054MA,DP04_0054PE,DP04_0054PEA,DP04_0054PM,DP04_0054PMA,DP04_0055E,DP04_0055EA,DP04_0055M,DP04_0055MA,DP04_0055PE,DP04_0055PEA,DP04_0055PM,DP04_0055PMA,DP04_0056E,DP04_0056EA,DP04_0056M,DP04_0056MA,DP04_0056PE,DP04_0056PEA,DP04_0056PM,DP04_0056PMA,DP04_0057E,DP04_0057EA,DP04_0057M,DP04_0057MA,DP04_0057PE,DP04_0057PEA,DP04_0057PM,DP04_0057PMA,DP04_0058E,DP04_0058EA,DP04_0058M,DP04_0058MA,DP04_0058PE,DP04_0058PEA,DP04_0058PM,DP04_0058PMA,DP04_0059E,DP04_0059EA,DP04_0059M,DP04_0059MA,DP04_0059PE,DP04_0059PEA,DP04_0059PM,DP04_0059PMA,DP04_0060E,DP04_0060EA,DP04_0060M,DP04_0060MA,DP04_0060PE,DP04_0060PEA,DP04_0060PM,DP04_0060PMA,DP04_0061E,DP04_0061EA,DP04_0061M,DP04_0061MA,DP04_0061PE,DP04_0061PEA,DP04_0061PM,DP04_0061PMA,DP04_0062E,DP04_0062EA,DP04_0062M,DP04_0062MA,DP04_0062PE,DP04_0062PEA,DP04_0062PM,DP04_0062PMA,DP04_0063E,DP04_0063EA,DP04_0063M,DP04_0063MA,DP04_0063PE,DP04_0063PEA,DP04_0063PM,DP04_0063PMA,DP04_0064E,DP04_0064EA,DP04_0064M,DP04_0064MA,DP04_0064PE,DP04_0064PEA,DP04_0064PM,DP04_0064PMA,DP04_0065E,DP04_0065EA,DP04_0065M,DP04_0065MA,DP04_0065PE,DP04_0065PEA,DP04_0065PM,DP04_0065PMA,DP04_0066E,DP04_0066EA,DP04_0066M,DP04_0066MA,DP04_0066PE,DP04_0066PEA,DP04_0066PM,DP04_0066PMA,DP04_0067E,DP04_0067EA,DP04_0067M,DP04_0067MA,DP04_0067PE,DP04_0067PEA,DP04_0067PM,DP04_0067PMA,DP04_0068E,DP04_0068EA,DP04_0068M,DP04_0068MA,DP04_0068PE,DP04_0068PEA,DP04_0068PM,DP04_0068PMA,DP04_0069E,DP04_0069EA,DP04_0069M,DP04_0069MA,DP04_0069PE,DP04_0069PEA,DP04_0069PM,DP04_0069PMA,DP04_0070E,DP04_0070EA,DP04_0070M,DP04_0070MA,DP04_0070PE,DP04_0070PEA,DP04_0070PM,DP04_0070PMA,DP04_0071E,DP04_0071EA,DP04_0071M,DP04_0071MA,DP04_0071PE,DP04_0071PEA,DP04_0071PM,DP04_0071PMA,DP04_0072E,DP04_0072EA,DP04_0072M,DP04_0072MA,DP04_0072PE,DP04_0072PEA,DP04_0072PM,DP04_0072PMA,DP04_0073E,DP04_0073EA,DP04_0073M,DP04_0073MA,DP04_0073PE,DP04_0073PEA,DP04_0073PM,DP04_0073PMA,DP04_0074E,DP04_0074EA,DP04_0074M,DP04_0074MA,DP04_0074PE,DP04_0074PEA,DP04_0074PM,DP04_0074PMA,DP04_0075E,DP04_0075EA,DP04_0075M,DP04_0075MA,DP04_0075PE,DP04_0075PEA,DP04_0075PM,DP04_0075PMA,DP04_0076E,DP04_0076EA,DP04_0076M,DP04_0076MA,DP04_0076PE,DP04_0076PEA,DP04_0076PM,DP04_0076PMA,DP04_0077E,DP04_0077EA,DP04_0077M,DP04_0077MA,DP04_0077PE,DP04_0077PEA,DP04_0077PM,DP04_0077PMA,DP04_0078E,DP04_0078EA,DP04_0078M,DP04_0078MA,DP04_0078PE,DP04_0078PEA,DP04_0078PM,DP04_0078PMA,DP04_0079E,DP04_0079EA,DP04_0079M,DP04_0079MA,DP04_0079PE,DP04_0079PEA,DP04_0079PM,DP04_0079PMA,DP04_0080E,DP04_0080EA,DP04_0080M,DP04_0080MA,DP04_0080PE,DP04_0080PEA,DP04_0080PM,DP04_0080PMA,DP04_0081E,DP04_0081EA,DP04_0081M,DP04_0081MA,DP04_0081PE,DP04_0081PEA,DP04_0081PM,DP04_0081PMA,DP04_0082E,DP04_0082EA,DP04_0082M,DP04_0082MA,DP04_0082PE,DP04_0082PEA,DP04_0082PM,DP04_0082PMA,DP04_0083E,DP04_0083EA,DP04_0083M,DP04_0083MA,DP04_0083PE,DP04_0083PEA,DP04_0083PM,DP04_0083PMA,DP04_0084E,DP04_0084EA,DP04_0084M,DP04_0084MA,DP04_0084PE,DP04_0084PEA,DP04_0084PM,DP04_0084PMA,DP04_0085E,DP04_0085EA,DP04_0085M,DP04_0085MA,DP04_0085PE,DP04_0085PEA,DP04_0085PM,DP04_0085PMA,DP04_0086E,DP04_0086EA,DP04_0086M,DP04_0086MA,DP04_0086PE,DP04_0086PEA,DP04_0086PM,DP04_0086PMA,DP04_0087E,DP04_0087EA,DP04_0087M,DP04_0087MA,DP04_0087PE,DP04_0087PEA,DP04_0087PM,DP04_0087PMA,DP04_0088E,DP04_0088EA,DP04_0088M,DP04_0088MA,DP04_0088PE,DP04_0088PEA,DP04_0088PM,DP04_0088PMA,DP04_0089E,DP04_0089EA,DP04_0089M,DP04_0089MA,DP04_0089PE,DP04_0089PEA,DP04_0089PM,DP04_0089PMA,DP04_0090E,DP04_0090EA,DP04_0090M,DP04_0090MA,DP04_0090PE,DP04_0090PEA,DP04_0090PM,DP04_0090PMA,DP04_0091E,DP04_0091EA,DP04_0091M,DP04_0091MA,DP04_0091PE,DP04_0091PEA,DP04_0091PM,DP04_0091PMA,DP04_0092E,DP04_0092EA,DP04_0092M,DP04_0092MA,DP04_0092PE,DP04_0092PEA,DP04_0092PM,DP04_0092PMA,DP04_0093E,DP04_0093EA,DP04_0093M,DP04_0093MA,DP04_0093PE,DP04_0093PEA,DP04_0093PM,DP04_0093PMA,DP04_0094E,DP04_0094EA,DP04_0094M,DP04_0094MA,DP04_0094PE,DP04_0094PEA,DP04_0094PM,DP04_0094PMA,DP04_0095E,DP04_0095EA,DP04_0095M,DP04_0095MA,DP04_0095PE,DP04_0095PEA,DP04_0095PM,DP04_0095PMA,DP04_0096E,DP04_0096EA,DP04_0096M,DP04_0096MA,DP04_0096PE,DP04_0096PEA,DP04_0096PM,DP04_0096PMA,DP04_0097E,DP04_0097EA,DP04_0097M,DP04_0097MA,DP04_0097PE,DP04_0097PEA,DP04_0097PM,DP04_0097PMA,DP04_0098E,DP04_0098EA,DP04_0098M,DP04_0098MA,DP04_0098PE,DP04_0098PEA,DP04_0098PM,DP04_0098PMA,DP04_0099E,DP04_0099EA,DP04_0099M,DP04_0099MA,DP04_0099PE,DP04_0099PEA,DP04_0099PM,DP04_0099PMA,DP04_0100E,DP04_0100EA,DP04_0100M,DP04_0100MA,DP04_0100PE,DP04_0100PEA,DP04_0100PM,DP04_0100PMA,DP04_0101E,DP04_0101EA,DP04_0101M,DP04_0101MA,DP04_0101PE,DP04_0101PEA,DP04_0101PM,DP04_0101PMA,DP04_0102E,DP04_0102EA,DP04_0102M,DP04_0102MA,DP04_0102PE,DP04_0102PEA,DP04_0102PM,DP04_0102PMA,DP04_0103E,DP04_0103EA,DP04_0103M,DP04_0103MA,DP04_0103PE,DP04_0103PEA,DP04_0103PM,DP04_0103PMA,DP04_0104E,DP04_0104EA,DP04_0104M,DP04_0104MA,DP04_0104PE,DP04_0104PEA,DP04_0104PM,DP04_0104PMA,DP04_0105E,DP04_0105EA,DP04_0105M,DP04_0105MA,DP04_0105PE,DP04_0105PEA,DP04_0105PM,DP04_0105PMA,DP04_0106E,DP04_0106EA,DP04_0106M,DP04_0106MA,DP04_0106PE,DP04_0106PEA,DP04_0106PM,DP04_0106PMA,DP04_0107E,DP04_0107EA,DP04_0107M,DP04_0107MA,DP04_0107PE,DP04_0107PEA,DP04_0107PM,DP04_0107PMA,DP04_0108E,DP04_0108EA,DP04_0108M,DP04_0108MA,DP04_0108PE,DP04_0108PEA,DP04_0108PM,DP04_0108PMA,DP04_0109E,DP04_0109EA,DP04_0109M,DP04_0109MA,DP04_0109PE,DP04_0109PEA,DP04_0109PM,DP04_0109PMA,DP04_0110E,DP04_0110EA,DP04_0110M,DP04_0110MA,DP04_0110PE,DP04_0110PEA,DP04_0110PM,DP04_0110PMA,DP04_0111E,DP04_0111EA,DP04_0111M,DP04_0111MA,DP04_0111PE,DP04_0111PEA,DP04_0111PM,DP04_0111PMA,DP04_0112E,DP04_0112EA,DP04_0112M,DP04_0112MA,DP04_0112PE,DP04_0112PEA,DP04_0112PM,DP04_0112PMA,DP04_0113E,DP04_0113EA,DP04_0113M,DP04_0113MA,DP04_0113PE,DP04_0113PEA,DP04_0113PM,DP04_0113PMA,DP04_0114E,DP04_0114EA,DP04_0114M,DP04_0114MA,DP04_0114PE,DP04_0114PEA,DP04_0114PM,DP04_0114PMA,DP04_0115E,DP04_0115EA,DP04_0115M,DP04_0115MA,DP04_0115PE,DP04_0115PEA,DP04_0115PM,DP04_0115PMA,DP04_0116E,DP04_0116EA,DP04_0116M,DP04_0116MA,DP04_0116PE,DP04_0116PEA,DP04_0116PM,DP04_0116PMA,DP04_0117E,DP04_0117EA,DP04_0117M,DP04_0117MA,DP04_0117PE,DP04_0117PEA,DP04_0117PM,DP04_0117PMA,DP04_0118E,DP04_0118EA,DP04_0118M,DP04_0118MA,DP04_0118PE,DP04_0118PEA,DP04_0118PM,DP04_0118PMA,DP04_0119E,DP04_0119EA,DP04_0119M,DP04_0119MA,DP04_0119PE,DP04_0119PEA,DP04_0119PM,DP04_0119PMA,DP04_0120E,DP04_0120EA,DP04_0120M,DP04_0120MA,DP04_0120PE,DP04_0120PEA,DP04_0120PM,DP04_0120PMA,DP04_0121E,DP04_0121EA,DP04_0121M,DP04_0121MA,DP04_0121PE,DP04_0121PEA,DP04_0121PM,DP04_0121PMA,DP04_0122E,DP04_0122EA,DP04_0122M,DP04_0122MA,DP04_0122PE,DP04_0122PEA,DP04_0122PM,DP04_0122PMA,DP04_0123E,DP04_0123EA,DP04_0123M,DP04_0123MA,DP04_0123PE,DP04_0123PEA,DP04_0123PM,DP04_0123PMA,DP04_0124E,DP04_0124EA,DP04_0124M,DP04_0124MA,DP04_0124PE,DP04_0124PEA,DP04_0124PM,DP04_0124PMA,DP04_0125E,DP04_0125EA,DP04_0125M,DP04_0125MA,DP04_0125PE,DP04_0125PEA,DP04_0125PM,DP04_0125PMA,DP04_0126E,DP04_0126EA,DP04_0126M,DP04_0126MA,DP04_0126PE,DP04_0126PEA,DP04_0126PM,DP04_0126PMA,DP04_0127E,DP04_0127EA,DP04_0127M,DP04_0127MA,DP04_0127PE,DP04_0127PEA,DP04_0127PM,DP04_0127PMA,DP04_0128E,DP04_0128EA,DP04_0128M,DP04_0128MA,DP04_0128PE,DP04_0128PEA,DP04_0128PM,DP04_0128PMA,DP04_0129E,DP04_0129EA,DP04_0129M,DP04_0129MA,DP04_0129PE,DP04_0129PEA,DP04_0129PM,DP04_0129PMA,DP04_0130E,DP04_0130EA,DP04_0130M,DP04_0130MA,DP04_0130PE,DP04_0130PEA,DP04_0130PM,DP04_0130PMA,DP04_0131E,DP04_0131EA,DP04_0131M,DP04_0131MA,DP04_0131PE,DP04_0131PEA,DP04_0131PM,DP04_0131PMA,DP04_0132E,DP04_0132EA,DP04_0132M,DP04_0132MA,DP04_0132PE,DP04_0132PEA,DP04_0132PM,DP04_0132PMA,DP04_0133E,DP04_0133EA,DP04_0133M,DP04_0133MA,DP04_0133PE,DP04_0133PEA,DP04_0133PM,DP04_0133PMA,DP04_0134E,DP04_0134EA,DP04_0134M,DP04_0134MA,DP04_0134PE,DP04_0134PEA,DP04_0134PM,DP04_0134PMA,DP04_0135E,DP04_0135EA,DP04_0135M,DP04_0135MA,DP04_0135PE,DP04_0135PEA,DP04_0135PM,DP04_0135PMA,DP04_0136E,DP04_0136EA,DP04_0136M,DP04_0136MA,DP04_0136PE,DP04_0136PEA,DP04_0136PM,DP04_0136PMA,DP04_0137E,DP04_0137EA,DP04_0137M,DP04_0137MA,DP04_0137PE,DP04_0137PEA,DP04_0137PM,DP04_0137PMA,DP04_0138E,DP04_0138EA,DP04_0138M,DP04_0138MA,DP04_0138PE,DP04_0138PEA,DP04_0138PM,DP04_0138PMA,DP04_0139E,DP04_0139EA,DP04_0139M,DP04_0139MA,DP04_0139PE,DP04_0139PEA,DP04_0139PM,DP04_0139PMA,DP04_0140E,DP04_0140EA,DP04_0140M,DP04_0140MA,DP04_0140PE,DP04_0140PEA,DP04_0140PM,DP04_0140PMA,DP04_0141E,DP04_0141EA,DP04_0141M,DP04_0141MA,DP04_0141PE,DP04_0141PEA,DP04_0141PM,DP04_0141PMA,DP04_0142E,DP04_0142EA,DP04_0142M,DP04_0142MA,DP04_0142PE,DP04_0142PEA,DP04_0142PM,DP04_0142PMA,DP04_0143E,DP04_0143EA,DP04_0143M,DP04_0143MA,DP04_0143PE,DP04_0143PEA,DP04_0143PM,DP04_0143PMA,GEO_ID,NAME,ucgid
0,17554,None,888,None,17554,None,-888888888,(X),15097,None,796,None,86.0,None,2.9,None,2457,None,552,None,14.0,None,2.9,None,2.9,None,3.4,None,-888888888,(X),-888888888,(X),7.4,None,2.5,None,-888888888,(X),-888888888,(X),17554,None,888,None,17554,None,-888888888,(X),163,None,151,None,0.9,None,0.9,None,70,None,63,None,0.4,None,0.4,None,106,None,80,None,0.6,None,0.5,None,477,None,224,None,2.7,None,1.3,None,575,None,207,None,3.3,None,1.2,None,1165,None,293,None,6.6,None,1.6,None,14961,None,888,None,85.2,None,2.4,None,15,None,23,None,0.1,None,0.1,None,22,None,37,None,0.1,None,0.2,None,17554,None,888,None,17554,None,-888888888,(X),127,None,98,None,0.7,None,0.6,None,4740,None,571,None,27.0,None,3.2,None,2564,None,456,None,14.6,None,2.4,None,301,None,184,None,1.7,None,1.0,None,496,None,195,None,2.8,None,1.1,None,465,None,219,None,2.6,None,1.2,None,2890,None,409,None,16.5,None,2.2,None,767,None,299,None,4.4,None,1.7,None,501,None,241,None,2.9,None,1.4,None,4703,None,611,None,26.8,None,2.9,None,17554,None,888,None,17554,None,-888888888,(X),2850,None,468,None,16.2,None,2.4,None,3552,None,522,None,20.2,None,2.7,None,6042,None,705,None,34.4,None,3.9,None,2922,None,462,None,16.6,None,2.4,None,1220,None,353,None,6.9,None,2.0,None,497,None,198,None,2.8,None,1.1,None,225,None,213,None,1.3,None,1.2,None,22,None,26,None,0.1,None,0.1,None,224,None,179,None,1.3,None,1.0,None,2.9,None,0.1,None,-888888888,(X),-888888888,(X),17554,None,888,None,17554,None,-888888888,(X),3202,None,487,None,18.2,None,2.5,None,8925,None,722,None,50.8,None,3.3,None,3468,None,492,None,19.8,None,2.6,None,1437,None,381,None,8.2,None,2.1,None,325,None,173,None,1.9,None,1.0,None,197,None,174,None,1.1,None,1.0,None,15097,None,796,None,15097,None,-888888888,(X),3570,None,565,None,23.6,None,3.4,None,11527,None,741,None,76.4,None,3.4,None,1.97,None,0.21,None,-888888888,(X),-888888888,(X),1.69,None,0.10,None,-888888888,(X),-888888888,(X),15097,None,796,None,15097,None,-888888888,(X),2577,None,303,None,17.1,None,2.2,None,4241,None,554,None,28.1,None,3.1,None,4347,None,533,None,28.8,None,3.2,None,1968,None,388,None,13.0,None,2.4,None,981,None,319,None,6.5,None,2.0,None,983,None,262,None,6.5,None,1.7,None,15097,None,796,None,15097,None,-888888888,(X),12699,None,814,None,84.1,None,3.1,None,2121,None,458,None,14.0,None,2.9,None,247,None,172,None,1.6,None,1.2,None,30,None,38,None,0.2,None,0.3,None,15097,None,796,None,15097,None,-888888888,(X),5268,None,614,None,34.9,None,3.5,None,250,None,122,None,1.7,None,0.8,None,7084,None,592,None,46.9,None,3.9,None,1028,None,308,None,6.8,None,2.0,None,0,None,25,None,0.0,None,0.3,None,0,None,25,None,0.0,None,0.3,None,181,None,247,None,1.2,None,1.6,None,565,None,205,None,3.7,None,1.3,None,721,None,245,None,4.8,None,1.6,None,15097,None,796,None,15097,None,-888888888,(X),171,None,156,None,1.1,None,1.0,None,114,None,72,None,0.8,None,0.5,None,58,None,54,None,0.4,None,0.4,None,15097,None,796,None,15097,None,-888888888,(X),14495,None,786,None,96.0,None,1.4,None,225,None,102,None,1.5,None,0.7,None,377,None,188,None,2.5,None,1.2,None,3570,None,565,None,3570,None,-888888888,(X),200,None,113,None,5.6,None,3.3,None,376,None,195,None,10.5,None,5.4,None,649,None,321,None,18.2,None,8.2,None,207,None,163,None,5.8,None,4.5,None,13,None,20,None,0.4,None,0.6,None,164,None,113,None,4.6,None,3.2,None,465,None,183,None,13.0,None,5.3,None,1496,None,398,None,41.9,None,7.7,None,793000,None,339113,None,-888888888,(X),-888888888,(X),3570,None,565,None,3570,None,-888888888,(X),1561,None,419,None,43.7,None,7.8,None,2009,None,360,None,56.3,None,7.8,None,1561,None,419,None,1561,None,-888888888,(X),120,None,93,None,7.7,None,5.8,None,170,None,140,None,10.9,None,8.1,None,36,None,34,None,2.3,None,2.2,None,139,None,208,None,8.9,None,12.5,None,69,None,52,None,4.4,None,3.7,None,92,None,85,None,5.9,None,5.0,None,935,None,304,None,59.9,None,12.8,None,3668,None,996,None,-888888888,(X),-888888888,(X),2009,None,360,None,2009,None,-888888888,(X),1292,None,329,None,64.3,None,10.7,None,10,None,18,None,0.5,None,0.9,None,55,None,54,None,2.7,None,2.7,None,17,None,27,None,0.8,None,1.3,None,37,None,60,None,1.8,None,3.0,None,598,None,199,None,29.8,None,8.9,None,131,None,39,None,-888888888,(X),-888888888,(X),1561,None,419,None,1561,None,-888888888,(X),901,None,329,None,57.7,None,12.8,None,191,None,142,None,12.2,None,8.2,None,122,None,103,None,7.8,None,6.3,None,59,None,60,None,3.8,None,3.8,None,288,None,151,None,18.4,None,9.5,None,0,None,25,None,-888888888,(X),-888888888,(X),2009,None,360,None,2009,None,-888888888,(X),1453,None,309,None,72.3,None,11.7,None,197,None,206,None,9.8,None,9.6,None,5,None,11,None,0.2,None,0.6,None,85,None,80,None,4.2,None,4.0,None,128,None,149,None,6.4,None,7.2,None,33,None,42,None,1.6,None,2.2,None,108,None,77,None,5.4,None,3.9,None,0,None,25,None,-888888888,(X),-888888888,(X),11399,None,734,None,11399,None,-888888888,(X),815,None,286,None,7.1,None,2.5,None,1406,None,388,None,12.3,None,3.1,None,1383,None,382,None,12.1,None,3.1,None,568,None,219,None,5.0,None,1.9,None,828,None,221,None,7.3,None,1.9,None,662,None,212,None,5.8,None,1.9,None,5737,None,498,None,50.3,None,4.1,None,3024,None,311,None,-888888888,(X),-888888888,(X),128,None,108,None,-888888888,(X),-888888888,(X),11130,None,753,None,11130,None,-888888888,(X),2621,None,429,None,23.5,None,3.5,None,1403,None,300,None,12.6,None,2.6,None,1581,None,411,None,14.2,None,3.5,None,1119,None,317,None,10.1,None,2.7,None,1199,None,295,None,10.8,None,2.6,None,3207,None,436,None,28.8,None,3.5,None,397,None,189,None,-888888888,(X),-888888888,(X),860Z200US10001,ZCTA5 10001,860Z200US10001

In [ ]:
df_test = json_to_dataframe(response)

In [ ]:
selected_columns = df_test[['ucgid','DP04_0134E', 'DP04_0089E']]

def process_rent_response(response, year):
    """
    Convert Census API response to a DataFrame with selected columns and a year column.

    Parameters:
        response: requests.Response object from Census API
        year (str or int): Year of the data

    Returns:
        pd.DataFrame: Cleaned DataFrame with ['ucgid', 'year', 'S1901_C01_012E', 'S1901_C01_013E']
    """
    df = pd.DataFrame(response.json()[1:], columns=response.json()[0])
    df = df[['ucgid', 'DP04_0126E','DP04_0134E','DP04_0080E','DP04_0089E']]
    df['year'] = str(year)
    return df[['ucgid', 'year', 'DP04_0126E','DP04_0134E', 'DP04_0080E','DP04_0089E']]

df_rent_2023 = process_rent_response(response, 2023)
print(df_rent_2023.head())

In [ ]:
df_rent_2023 = process_rent_response(response, 2023)
print(df_rent_2023.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  860Z200US10001  2023      11399       3024       3570     793000
1  860Z200US10002  2023      28916       1207       6660     808500
2  860Z200US10003  2023      16196       2772       8701    1137000
3  860Z200US10004  2023       1145       3501        630    1866400
4  860Z200US10005  2023       4276       3501        880    1387200

#2022

In [ ]:
url = "https://api.census.gov/data/2022/acs/acs5/profile?get=group(DP04)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2022 = process_rent_response(response, 2022)
print(df_rent_2022.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  860Z200US10001  2022      10783       2625       3422     535100
1  860Z200US10002  2022      29619       1136       6224     784800
2  860Z200US10003  2022      15927       2731       8927    1111000
3  860Z200US10004  2022       1189       3501        893    1792200
4  860Z200US10005  2022       4067       3501        814    1750000

# 2021

In [ ]:
url = "https://api.census.gov/data/2021/acs/acs5/profile?get=group(DP04)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2021 = process_rent_response(response, 2021)
print(df_rent_2021.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  860Z200US10001  2021      10279       2269       3780     467800
1  860Z200US10002  2021      28698       1047       5850     719500
2  860Z200US10003  2021      15774       2478       9245     972900
3  860Z200US10004  2021       1217       3501        864    1722600
4  860Z200US10005  2021       3915       3501        795    1237900

# 2020

In [ ]:
url = "https://api.census.gov/data/2020/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2020 = process_rent_response(response, 2020)
print(df_rent_2020.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2020       9572       2169       3600     403800
1  8600000US10002  2020      28744        979       4895     696900
2  8600000US10003  2020      16083       2437       8688     989500
3  8600000US10004  2020       1111       3393        697    1892400
4  8600000US10005  2020       3848       3501        735    1159600

#2019

In [ ]:
url = "https://api.census.gov/data/2019/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2019 = process_rent_response(response, 2019)
print(df_rent_2019.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2019       9585       2128       3285     386800
1  8600000US10002  2019      28721        980       4526     689700
2  8600000US10003  2019      17381       2331       8445    1028900
3  8600000US10004  2019       1086       3324        673    1783600
4  8600000US10005  2019       3372       3356        919    1298900

#2018

In [ ]:
url = "https://api.census.gov/data/2018/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2018 = process_rent_response(response, 2018)
print(df_rent_2018.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2018       9015       2065       3253     343400
1  8600000US10002  2018      28758        963       4470     665200
2  8600000US10003  2018      17213       2298       8605    1001200
3  8600000US10004  2018       1002       3235        635    1640600
4  8600000US10005  2018       3461       3226        859    1415400

#2017

In [ ]:
url = "https://api.census.gov/data/2017/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2017 = process_rent_response(response, 2017)
print(df_rent_2017.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2017       8709       1912       3479     355600
1  8600000US10002  2017      28616        936       4510     641400
2  8600000US10003  2017      17709       2201       8720     986100
3  8600000US10004  2017       1084       3049        474    1597500
4  8600000US10005  2017       3399       3141        778    1494400

#2016

In [ ]:
url = "https://api.census.gov/data/2016/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2016 = process_rent_response(response, 2016)
print(df_rent_2016.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2016       8631       2114       3232     460500
1  8600000US10002  2016      28351        919       4601     608900
2  8600000US10003  2016      18700       2117       8292     963100
3  8600000US10004  2016       1053       2911        430    1250000
4  8600000US10005  2016       3541       3005        749    1424900

#2015

In [ ]:
url = "https://api.census.gov/data/2015/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2015 = process_rent_response(response, 2015)
print(df_rent_2015.head())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2015       8401       1989       3161     575900
1  8600000US10002  2015      28488        882       4524     578300
2  8600000US10003  2015      18961       2030       8210     913200
3  8600000US10004  2015       1007       2851        487     847500
4  8600000US10005  2015       3585       2918        662    1332100

#2014

In [ ]:
url = "https://api.census.gov/data/2014/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_test = json_to_dataframe(response)
df_test

,DP04_0001E,DP04_0001EA,DP04_0001M,DP04_0001MA,DP04_0001PE,DP04_0001PEA,DP04_0001PM,DP04_0001PMA,DP04_0002E,DP04_0002EA,DP04_0002M,DP04_0002MA,DP04_0002PE,DP04_0002PEA,DP04_0002PM,DP04_0002PMA,DP04_0003E,DP04_0003EA,DP04_0003M,DP04_0003MA,DP04_0003PE,DP04_0003PEA,DP04_0003PM,DP04_0003PMA,DP04_0004E,DP04_0004EA,DP04_0004M,DP04_0004MA,DP04_0004PE,DP04_0004PEA,DP04_0004PM,DP04_0004PMA,DP04_0005E,DP04_0005EA,DP04_0005M,DP04_0005MA,DP04_0005PE,DP04_0005PEA,DP04_0005PM,DP04_0005PMA,DP04_0006E,DP04_0006EA,DP04_0006M,DP04_0006MA,DP04_0006PE,DP04_0006PEA,DP04_0006PM,DP04_0006PMA,DP04_0007E,DP04_0007EA,DP04_0007M,DP04_0007MA,DP04_0007PE,DP04_0007PEA,DP04_0007PM,DP04_0007PMA,DP04_0008E,DP04_0008EA,DP04_0008M,DP04_0008MA,DP04_0008PE,DP04_0008PEA,DP04_0008PM,DP04_0008PMA,DP04_0009E,DP04_0009EA,DP04_0009M,DP04_0009MA,DP04_0009PE,DP04_0009PEA,DP04_0009PM,DP04_0009PMA,DP04_0010E,DP04_0010EA,DP04_0010M,DP04_0010MA,DP04_0010PE,DP04_0010PEA,DP04_0010PM,DP04_0010PMA,DP04_0011E,DP04_0011EA,DP04_0011M,DP04_0011MA,DP04_0011PE,DP04_0011PEA,DP04_0011PM,DP04_0011PMA,DP04_0012E,DP04_0012EA,DP04_0012M,DP04_0012MA,DP04_0012PE,DP04_0012PEA,DP04_0012PM,DP04_0012PMA,DP04_0013E,DP04_0013EA,DP04_0013M,DP04_0013MA,DP04_0013PE,DP04_0013PEA,DP04_0013PM,DP04_0013PMA,DP04_0014E,DP04_0014EA,DP04_0014M,DP04_0014MA,DP04_0014PE,DP04_0014PEA,DP04_0014PM,DP04_0014PMA,DP04_0015E,DP04_0015EA,DP04_0015M,DP04_0015MA,DP04_0015PE,DP04_0015PEA,DP04_0015PM,DP04_0015PMA,DP04_0016E,DP04_0016EA,DP04_0016M,DP04_0016MA,DP04_0016PE,DP04_0016PEA,DP04_0016PM,DP04_0016PMA,DP04_0017E,DP04_0017EA,DP04_0017M,DP04_0017MA,DP04_0017PE,DP04_0017PEA,DP04_0017PM,DP04_0017PMA,DP04_0018E,DP04_0018EA,DP04_0018M,DP04_0018MA,DP04_0018PE,DP04_0018PEA,DP04_0018PM,DP04_0018PMA,DP04_0019E,DP04_0019EA,DP04_0019M,DP04_0019MA,DP04_0019PE,DP04_0019PEA,DP04_0019PM,DP04_0019PMA,DP04_0020E,DP04_0020EA,DP04_0020M,DP04_0020MA,DP04_0020PE,DP04_0020PEA,DP04_0020PM,DP04_0020PMA,DP04_0021E,DP04_0021EA,DP04_0021M,DP04_0021MA,DP04_0021PE,DP04_0021PEA,DP04_0021PM,DP04_0021PMA,DP04_0022E,DP04_0022EA,DP04_0022M,DP04_0022MA,DP04_0022PE,DP04_0022PEA,DP04_0022PM,DP04_0022PMA,DP04_0023E,DP04_0023EA,DP04_0023M,DP04_0023MA,DP04_0023PE,DP04_0023PEA,DP04_0023PM,DP04_0023PMA,DP04_0024E,DP04_0024EA,DP04_0024M,DP04_0024MA,DP04_0024PE,DP04_0024PEA,DP04_0024PM,DP04_0024PMA,DP04_0025E,DP04_0025EA,DP04_0025M,DP04_0025MA,DP04_0025PE,DP04_0025PEA,DP04_0025PM,DP04_0025PMA,DP04_0026E,DP04_0026EA,DP04_0026M,DP04_0026MA,DP04_0026PE,DP04_0026PEA,DP04_0026PM,DP04_0026PMA,DP04_0027E,DP04_0027EA,DP04_0027M,DP04_0027MA,DP04_0027PE,DP04_0027PEA,DP04_0027PM,DP04_0027PMA,DP04_0028E,DP04_0028EA,DP04_0028M,DP04_0028MA,DP04_0028PE,DP04_0028PEA,DP04_0028PM,DP04_0028PMA,DP04_0029E,DP04_0029EA,DP04_0029M,DP04_0029MA,DP04_0029PE,DP04_0029PEA,DP04_0029PM,DP04_0029PMA,DP04_0030E,DP04_0030EA,DP04_0030M,DP04_0030MA,DP04_0030PE,DP04_0030PEA,DP04_0030PM,DP04_0030PMA,DP04_0031E,DP04_0031EA,DP04_0031M,DP04_0031MA,DP04_0031PE,DP04_0031PEA,DP04_0031PM,DP04_0031PMA,DP04_0032E,DP04_0032EA,DP04_0032M,DP04_0032MA,DP04_0032PE,DP04_0032PEA,DP04_0032PM,DP04_0032PMA,DP04_0033E,DP04_0033EA,DP04_0033M,DP04_0033MA,DP04_0033PE,DP04_0033PEA,DP04_0033PM,DP04_0033PMA,DP04_0034E,DP04_0034EA,DP04_0034M,DP04_0034MA,DP04_0034PE,DP04_0034PEA,DP04_0034PM,DP04_0034PMA,DP04_0035E,DP04_0035EA,DP04_0035M,DP04_0035MA,DP04_0035PE,DP04_0035PEA,DP04_0035PM,DP04_0035PMA,DP04_0036E,DP04_0036EA,DP04_0036M,DP04_0036MA,DP04_0036PE,DP04_0036PEA,DP04_0036PM,DP04_0036PMA,DP04_0037E,DP04_0037EA,DP04_0037M,DP04_0037MA,DP04_0037PE,DP04_0037PEA,DP04_0037PM,DP04_0037PMA,DP04_0038E,DP04_0038EA,DP04_0038M,DP04_0038MA,DP04_0038PE,DP04_0038PEA,DP04_0038PM,DP04_0038PMA,DP04_0039E,DP04_0039EA,DP04_0039M,DP04_0039MA,DP04_0039PE,DP04_0039PEA,DP04_0039PM,DP04_0039PMA,DP04_0040E,DP04_0040EA,DP04_0040M,DP04_0040MA,DP04_0040PE,DP04_0040PEA,DP04_0040PM,DP04_0040PMA,DP04_0041E,DP04_0041EA,DP04_0041M,DP04_0041MA,DP04_0041PE,DP04_0041PEA,DP04_0041PM,DP04_0041PMA,DP04_0042E,DP04_0042EA,DP04_0042M,DP04_0042MA,DP04_0042PE,DP04_0042PEA,DP04_0042PM,DP04_0042PMA,DP04_0043E,DP04_0043EA,DP04_0043M,DP04_0043MA,DP04_0043PE,DP04_0043PEA,DP04_0043PM,DP04_0043PMA,DP04_0044E,DP04_0044EA,DP04_0044M,DP04_0044MA,DP04_0044PE,DP04_0044PEA,DP04_0044PM,DP04_0044PMA,DP04_0045E,DP04_0045EA,DP04_0045M,DP04_0045MA,DP04_0045PE,DP04_0045PEA,DP04_0045PM,DP04_0045PMA,DP04_0046E,DP04_0046EA,DP04_0046M,DP04_0046MA,DP04_0046PE,DP04_0046PEA,DP04_0046PM,DP04_0046PMA,DP04_0047E,DP04_0047EA,DP04_0047M,DP04_0047MA,DP04_0047PE,DP04_0047PEA,DP04_0047PM,DP04_0047PMA,DP04_0048E,DP04_0048EA,DP04_0048M,DP04_0048MA,DP04_0048PE,DP04_0048PEA,DP04_0048PM,DP04_0048PMA,DP04_0049E,DP04_0049EA,DP04_0049M,DP04_0049MA,DP04_0049PE,DP04_0049PEA,DP04_0049PM,DP04_0049PMA,DP04_0050E,DP04_0050EA,DP04_0050M,DP04_0050MA,DP04_0050PE,DP04_0050PEA,DP04_0050PM,DP04_0050PMA,DP04_0051E,DP04_0051EA,DP04_0051M,DP04_0051MA,DP04_0051PE,DP04_0051PEA,DP04_0051PM,DP04_0051PMA,DP04_0052E,DP04_0052EA,DP04_0052M,DP04_0052MA,DP04_0052PE,DP04_0052PEA,DP04_0052PM,DP04_0052PMA,DP04_0053E,DP04_0053EA,DP04_0053M,DP04_0053MA,DP04_0053PE,DP04_0053PEA,DP04_0053PM,DP04_0053PMA,DP04_0054E,DP04_0054EA,DP04_0054M,DP04_0054MA,DP04_0054PE,DP04_0054PEA,DP04_0054PM,DP04_0054PMA,DP04_0055E,DP04_0055EA,DP04_0055M,DP04_0055MA,DP04_0055PE,DP04_0055PEA,DP04_0055PM,DP04_0055PMA,DP04_0056E,DP04_0056EA,DP04_0056M,DP04_0056MA,DP04_0056PE,DP04_0056PEA,DP04_0056PM,DP04_0056PMA,DP04_0057E,DP04_0057EA,DP04_0057M,DP04_0057MA,DP04_0057PE,DP04_0057PEA,DP04_0057PM,DP04_0057PMA,DP04_0058E,DP04_0058EA,DP04_0058M,DP04_0058MA,DP04_0058PE,DP04_0058PEA,DP04_0058PM,DP04_0058PMA,DP04_0059E,DP04_0059EA,DP04_0059M,DP04_0059MA,DP04_0059PE,DP04_0059PEA,DP04_0059PM,DP04_0059PMA,DP04_0060E,DP04_0060EA,DP04_0060M,DP04_0060MA,DP04_0060PE,DP04_0060PEA,DP04_0060PM,DP04_0060PMA,DP04_0061E,DP04_0061EA,DP04_0061M,DP04_0061MA,DP04_0061PE,DP04_0061PEA,DP04_0061PM,DP04_0061PMA,DP04_0062E,DP04_0062EA,DP04_0062M,DP04_0062MA,DP04_0062PE,DP04_0062PEA,DP04_0062PM,DP04_0062PMA,DP04_0063E,DP04_0063EA,DP04_0063M,DP04_0063MA,DP04_0063PE,DP04_0063PEA,DP04_0063PM,DP04_0063PMA,DP04_0064E,DP04_0064EA,DP04_0064M,DP04_0064MA,DP04_0064PE,DP04_0064PEA,DP04_0064PM,DP04_0064PMA,DP04_0065E,DP04_0065EA,DP04_0065M,DP04_0065MA,DP04_0065PE,DP04_0065PEA,DP04_0065PM,DP04_0065PMA,DP04_0066E,DP04_0066EA,DP04_0066M,DP04_0066MA,DP04_0066PE,DP04_0066PEA,DP04_0066PM,DP04_0066PMA,DP04_0067E,DP04_0067EA,DP04_0067M,DP04_0067MA,DP04_0067PE,DP04_0067PEA,DP04_0067PM,DP04_0067PMA,DP04_0068E,DP04_0068EA,DP04_0068M,DP04_0068MA,DP04_0068PE,DP04_0068PEA,DP04_0068PM,DP04_0068PMA,DP04_0069E,DP04_0069EA,DP04_0069M,DP04_0069MA,DP04_0069PE,DP04_0069PEA,DP04_0069PM,DP04_0069PMA,DP04_0070E,DP04_0070EA,DP04_0070M,DP04_0070MA,DP04_0070PE,DP04_0070PEA,DP04_0070PM,DP04_0070PMA,DP04_0071E,DP04_0071EA,DP04_0071M,DP04_0071MA,DP04_0071PE,DP04_0071PEA,DP04_0071PM,DP04_0071PMA,DP04_0072E,DP04_0072EA,DP04_0072M,DP04_0072MA,DP04_0072PE,DP04_0072PEA,DP04_0072PM,DP04_0072PMA,DP04_0073E,DP04_0073EA,DP04_0073M,DP04_0073MA,DP04_0073PE,DP04_0073PEA,DP04_0073PM,DP04_0073PMA,DP04_0074E,DP04_0074EA,DP04_0074M,DP04_0074MA,DP04_0074PE,DP04_0074PEA,DP04_0074PM,DP04_0074PMA,DP04_0075E,DP04_0075EA,DP04_0075M,DP04_0075MA,DP04_0075PE,DP04_0075PEA,DP04_0075PM,DP04_0075PMA,DP04_0076E,DP04_0076EA,DP04_0076M,DP04_0076MA,DP04_0076PE,DP04_0076PEA,DP04_0076PM,DP04_0076PMA,DP04_0077E,DP04_0077EA,DP04_0077M,DP04_0077MA,DP04_0077PE,DP04_0077PEA,DP04_0077PM,DP04_0077PMA,DP04_0078E,DP04_0078EA,DP04_0078M,DP04_0078MA,DP04_0078PE,DP04_0078PEA,DP04_0078PM,DP04_0078PMA,DP04_0079E,DP04_0079EA,DP04_0079M,DP04_0079MA,DP04_0079PE,DP04_0079PEA,DP04_0079PM,DP04_0079PMA,DP04_0080E,DP04_0080EA,DP04_0080M,DP04_0080MA,DP04_0080PE,DP04_0080PEA,DP04_0080PM,DP04_0080PMA,DP04_0081E,DP04_0081EA,DP04_0081M,DP04_0081MA,DP04_0081PE,DP04_0081PEA,DP04_0081PM,DP04_0081PMA,DP04_0082E,DP04_0082EA,DP04_0082M,DP04_0082MA,DP04_0082PE,DP04_0082PEA,DP04_0082PM,DP04_0082PMA,DP04_0083E,DP04_0083EA,DP04_0083M,DP04_0083MA,DP04_0083PE,DP04_0083PEA,DP04_0083PM,DP04_0083PMA,DP04_0084E,DP04_0084EA,DP04_0084M,DP04_0084MA,DP04_0084PE,DP04_0084PEA,DP04_0084PM,DP04_0084PMA,DP04_0085E,DP04_0085EA,DP04_0085M,DP04_0085MA,DP04_0085PE,DP04_0085PEA,DP04_0085PM,DP04_0085PMA,DP04_0086E,DP04_0086EA,DP04_0086M,DP04_0086MA,DP04_0086PE,DP04_0086PEA,DP04_0086PM,DP04_0086PMA,DP04_0087E,DP04_0087EA,DP04_0087M,DP04_0087MA,DP04_0087PE,DP04_0087PEA,DP04_0087PM,DP04_0087PMA,DP04_0088E,DP04_0088EA,DP04_0088M,DP04_0088MA,DP04_0088PE,DP04_0088PEA,DP04_0088PM,DP04_0088PMA,DP04_0089E,DP04_0089EA,DP04_0089M,DP04_0089MA,DP04_0089PE,DP04_0089PEA,DP04_0089PM,DP04_0089PMA,DP04_0090E,DP04_0090EA,DP04_0090M,DP04_0090MA,DP04_0090PE,DP04_0090PEA,DP04_0090PM,DP04_0090PMA,DP04_0091E,DP04_0091EA,DP04_0091M,DP04_0091MA,DP04_0091PE,DP04_0091PEA,DP04_0091PM,DP04_0091PMA,DP04_0092E,DP04_0092EA,DP04_0092M,DP04_0092MA,DP04_0092PE,DP04_0092PEA,DP04_0092PM,DP04_0092PMA,DP04_0093E,DP04_0093EA,DP04_0093M,DP04_0093MA,DP04_0093PE,DP04_0093PEA,DP04_0093PM,DP04_0093PMA,DP04_0094E,DP04_0094EA,DP04_0094M,DP04_0094MA,DP04_0094PE,DP04_0094PEA,DP04_0094PM,DP04_0094PMA,DP04_0095E,DP04_0095EA,DP04_0095M,DP04_0095MA,DP04_0095PE,DP04_0095PEA,DP04_0095PM,DP04_0095PMA,DP04_0096E,DP04_0096EA,DP04_0096M,DP04_0096MA,DP04_0096PE,DP04_0096PEA,DP04_0096PM,DP04_0096PMA,DP04_0097E,DP04_0097EA,DP04_0097M,DP04_0097MA,DP04_0097PE,DP04_0097PEA,DP04_0097PM,DP04_0097PMA,DP04_0098E,DP04_0098EA,DP04_0098M,DP04_0098MA,DP04_0098PE,DP04_0098PEA,DP04_0098PM,DP04_0098PMA,DP04_0099E,DP04_0099EA,DP04_0099M,DP04_0099MA,DP04_0099PE,DP04_0099PEA,DP04_0099PM,DP04_0099PMA,DP04_0100E,DP04_0100EA,DP04_0100M,DP04_0100MA,DP04_0100PE,DP04_0100PEA,DP04_0100PM,DP04_0100PMA,DP04_0101E,DP04_0101EA,DP04_0101M,DP04_0101MA,DP04_0101PE,DP04_0101PEA,DP04_0101PM,DP04_0101PMA,DP04_0102E,DP04_0102EA,DP04_0102M,DP04_0102MA,DP04_0102PE,DP04_0102PEA,DP04_0102PM,DP04_0102PMA,DP04_0103E,DP04_0103EA,DP04_0103M,DP04_0103MA,DP04_0103PE,DP04_0103PEA,DP04_0103PM,DP04_0103PMA,DP04_0104E,DP04_0104EA,DP04_0104M,DP04_0104MA,DP04_0104PE,DP04_0104PEA,DP04_0104PM,DP04_0104PMA,DP04_0105E,DP04_0105EA,DP04_0105M,DP04_0105MA,DP04_0105PE,DP04_0105PEA,DP04_0105PM,DP04_0105PMA,DP04_0106E,DP04_0106EA,DP04_0106M,DP04_0106MA,DP04_0106PE,DP04_0106PEA,DP04_0106PM,DP04_0106PMA,DP04_0107E,DP04_0107EA,DP04_0107M,DP04_0107MA,DP04_0107PE,DP04_0107PEA,DP04_0107PM,DP04_0107PMA,DP04_0108E,DP04_0108EA,DP04_0108M,DP04_0108MA,DP04_0108PE,DP04_0108PEA,DP04_0108PM,DP04_0108PMA,DP04_0109E,DP04_0109EA,DP04_0109M,DP04_0109MA,DP04_0109PE,DP04_0109PEA,DP04_0109PM,DP04_0109PMA,DP04_0110E,DP04_0110EA,DP04_0110M,DP04_0110MA,DP04_0110PE,DP04_0110PEA,DP04_0110PM,DP04_0110PMA,DP04_0111E,DP04_0111EA,DP04_0111M,DP04_0111MA,DP04_0111PE,DP04_0111PEA,DP04_0111PM,DP04_0111PMA,DP04_0112E,DP04_0112EA,DP04_0112M,DP04_0112MA,DP04_0112PE,DP04_0112PEA,DP04_0112PM,DP04_0112PMA,DP04_0113E,DP04_0113EA,DP04_0113M,DP04_0113MA,DP04_0113PE,DP04_0113PEA,DP04_0113PM,DP04_0113PMA,DP04_0114E,DP04_0114EA,DP04_0114M,DP04_0114MA,DP04_0114PE,DP04_0114PEA,DP04_0114PM,DP04_0114PMA,DP04_0115E,DP04_0115EA,DP04_0115M,DP04_0115MA,DP04_0115PE,DP04_0115PEA,DP04_0115PM,DP04_0115PMA,DP04_0116E,DP04_0116EA,DP04_0116M,DP04_0116MA,DP04_0116PE,DP04_0116PEA,DP04_0116PM,DP04_0116PMA,DP04_0117E,DP04_0117EA,DP04_0117M,DP04_0117MA,DP04_0117PE,DP04_0117PEA,DP04_0117PM,DP04_0117PMA,DP04_0118E,DP04_0118EA,DP04_0118M,DP04_0118MA,DP04_0118PE,DP04_0118PEA,DP04_0118PM,DP04_0118PMA,DP04_0119E,DP04_0119EA,DP04_0119M,DP04_0119MA,DP04_0119PE,DP04_0119PEA,DP04_0119PM,DP04_0119PMA,DP04_0120E,DP04_0120EA,DP04_0120M,DP04_0120MA,DP04_0120PE,DP04_0120PEA,DP04_0120PM,DP04_0120PMA,DP04_0121E,DP04_0121EA,DP04_0121M,DP04_0121MA,DP04_0121PE,DP04_0121PEA,DP04_0121PM,DP04_0121PMA,DP04_0122E,DP04_0122EA,DP04_0122M,DP04_0122MA,DP04_0122PE,DP04_0122PEA,DP04_0122PM,DP04_0122PMA,DP04_0123E,DP04_0123EA,DP04_0123M,DP04_0123MA,DP04_0123PE,DP04_0123PEA,DP04_0123PM,DP04_0123PMA,DP04_0124E,DP04_0124EA,DP04_0124M,DP04_0124MA,DP04_0124PE,DP04_0124PEA,DP04_0124PM,DP04_0124PMA,DP04_0125E,DP04_0125EA,DP04_0125M,DP04_0125MA,DP04_0125PE,DP04_0125PEA,DP04_0125PM,DP04_0125PMA,DP04_0126E,DP04_0126EA,DP04_0126M,DP04_0126MA,DP04_0126PE,DP04_0126PEA,DP04_0126PM,DP04_0126PMA,DP04_0127E,DP04_0127EA,DP04_0127M,DP04_0127MA,DP04_0127PE,DP04_0127PEA,DP04_0127PM,DP04_0127PMA,DP04_0128E,DP04_0128EA,DP04_0128M,DP04_0128MA,DP04_0128PE,DP04_0128PEA,DP04_0128PM,DP04_0128PMA,DP04_0129E,DP04_0129EA,DP04_0129M,DP04_0129MA,DP04_0129PE,DP04_0129PEA,DP04_0129PM,DP04_0129PMA,DP04_0130E,DP04_0130EA,DP04_0130M,DP04_0130MA,DP04_0130PE,DP04_0130PEA,DP04_0130PM,DP04_0130PMA,DP04_0131E,DP04_0131EA,DP04_0131M,DP04_0131MA,DP04_0131PE,DP04_0131PEA,DP04_0131PM,DP04_0131PMA,DP04_0132E,DP04_0132EA,DP04_0132M,DP04_0132MA,DP04_0132PE,DP04_0132PEA,DP04_0132PM,DP04_0132PMA,DP04_0133E,DP04_0133EA,DP04_0133M,DP04_0133MA,DP04_0133PE,DP04_0133PEA,DP04_0133PM,DP04_0133PMA,DP04_0134E,DP04_0134EA,DP04_0134M,DP04_0134MA,DP04_0134PE,DP04_0134PEA,DP04_0134PM,DP04_0134PMA,DP04_0135E,DP04_0135EA,DP04_0135M,DP04_0135MA,DP04_0135PE,DP04_0135PEA,DP04_0135PM,DP04_0135PMA,DP04_0136E,DP04_0136EA,DP04_0136M,DP04_0136MA,DP04_0136PE,DP04_0136PEA,DP04_0136PM,DP04_0136PMA,DP04_0137E,DP04_0137EA,DP04_0137M,DP04_0137MA,DP04_0137PE,DP04_0137PEA,DP04_0137PM,DP04_0137PMA,DP04_0138E,DP04_0138EA,DP04_0138M,DP04_0138MA,DP04_0138PE,DP04_0138PEA,DP04_0138PM,DP04_0138PMA,DP04_0139E,DP04_0139EA,DP04_0139M,DP04_0139MA,DP04_0139PE,DP04_0139PEA,DP04_0139PM,DP04_0139PMA,DP04_0140E,DP04_0140EA,DP04_0140M,DP04_0140MA,DP04_0140PE,DP04_0140PEA,DP04_0140PM,DP04_0140PMA,DP04_0141E,DP04_0141EA,DP04_0141M,DP04_0141MA,DP04_0141PE,DP04_0141PEA,DP04_0141PM,DP04_0141PMA,GEO_ID,NAME,ucgid
0,12638,None,442,None,12638,None,-888888888,(X),11169,None,461,None,88.4,None,2.1,None,1469,None,272,None,11.6,None,2.1,None,1.6,None,2.2,None,-888888888,(X),-888888888,(X),3.1,None,1.3,None,-888888888,(X),-888888888,(X),12638,None,442,None,12638,None,-888888888,(X),59,None,48,None,0.5,None,0.4,None,96,None,138,None,0.8,None,1.1,None,223,None,131,None,1.8,None,1.0,None,274,None,91,None,2.2,None,0.7,None,546,None,151,None,4.3,None,1.2,None,1134,None,216,None,9.0,None,1.7,None,10294,None,501,None,81.5,None,2.5,None,12,None,13,None,0.1,None,0.1,None,0,None,21,None,0.0,None,0.2,None,12638,None,442,None,12638,None,-888888888,(X),720,None,146,None,5.7,None,1.1,None,2622,None,286,None,20.7,None,2.1,None,339,None,100,None,2.7,None,0.8,None,344,None,171,None,2.7,None,1.3,None,184,None,69,None,1.5,None,0.5,None,2515,None,305,None,19.9,None,2.2,None,641,None,160,None,5.1,None,1.3,None,665,None,212,None,5.3,None,1.7,None,4608,None,410,None,36.5,None,3.0,None,12638,None,442,None,12638,None,-888888888,(X),1988,None,298,None,15.7,None,2.5,None,2081,None,255,None,16.5,None,2.0,None,4240,None,399,None,33.5,None,2.8,None,2566,None,359,None,20.3,None,2.7,None,898,None,218,None,7.1,None,1.7,None,430,None,187,None,3.4,None,1.5,None,212,None,183,None,1.7,None,1.4,None,181,None,153,None,1.4,None,1.2,None,42,None,33,None,0.3,None,0.3,None,3.0,None,0.1,None,-888888888,(X),-888888888,(X),12638,None,442,None,12638,None,-888888888,(X),2479,None,315,None,19.6,None,2.6,None,5829,None,409,None,46.1,None,2.7,None,2898,None,370,None,22.9,None,2.8,None,941,None,208,None,7.4,None,1.6,None,338,None,215,None,2.7,None,1.7,None,153,None,171,None,1.2,None,1.3,None,11169,None,461,None,11169,None,-888888888,(X),3055,None,428,None,27.4,None,3.4,None,8114,None,461,None,72.6,None,3.4,None,1.78,None,0.13,None,-888888888,(X),-888888888,(X),1.99,None,0.21,None,-888888888,(X),-888888888,(X),11169,None,461,None,11169,None,-888888888,(X),4231,None,492,None,37.9,None,3.8,None,4087,None,401,None,36.6,None,3.4,None,1477,None,301,None,13.2,None,2.7,None,457,None,167,None,4.1,None,1.5,None,612,None,196,None,5.5,None,1.8,None,305,None,123,None,2.7,None,1.1,None,11169,None,461,None,11169,None,-888888888,(X),9164,None,492,None,82.0,None,3.2,None,1689,None,350,None,15.1,None,3.0,None,301,None,184,None,2.7,None,1.6,None,15,None,15,None,0.1,None,0.1,None,11169,None,461,None,11169,None,-888888888,(X),3456,None,437,None,30.9,None,3.9,None,80,None,62,None,0.7,None,0.6,None,3744,None,365,None,33.5,None,3.2,None,3272,None,487,None,29.3,None,3.9,None,9,None,15,None,0.1,None,0.1,None,26,None,28,None,0.2,None,0.3,None,0,None,21,None,0.0,None,0.3,None,249,None,118,None,2.2,None,1.0,None,333,None,126,None,3.0,None,1.1,None,11169,None,461,None,11169,None,-888888888,(X),69,None,57,None,0.6,None,0.5,None,169,None,99,None,1.5,None,0.9,None,236,None,82,None,2.1,None,0.7,None,11169,None,461,None,11169,None,-888888888,(X),10706,None,436,None,95.9,None,1.6,None,232,None,180,None,2.1,None,1.6,None,231,None,92,None,2.1,None,0.8,None,3055,None,428,None,3055,None,-888888888,(X),461,None,167,None,15.1,None,5.3,None,465,None,275,None,15.2,None,8.2,None,100,None,77,None,3.3,None,2.4,None,36,None,41,None,1.2,None,1.3,None,65,None,45,None,2.1,None,1.6,None,277,None,140,None,9.1,None,4.7,None,584,None,171,None,19.1,None,5.5,None,1067,None,259,None,34.9,None,6.7,None,597600,None,170388,None,-888888888,(X),-888888888,(X),3055,None,428,None,3055,None,-888888888,(X),1440,None,313,None,47.1,None,7.8,None,1615,None,327,None,52.9,None,7.8,None,1440,None,313,None,1440,None,-888888888,(X),0,None,21,None,0.0,None,2.1,None,0,None,21,None,0.0,None,2.1,None,210,None,232,None,14.6,None,14.4,None,49,None,38,None,3.4,None,2.7,None,48,None,36,None,3.3,None,2.5,None,112,None,64,None,7.8,None,4.6,None,1021,None,198,None,70.9,None,12.9,None,3399,None,906,None,-888888888,(X),-888888888,(X),1615,None,327,None,1615,None,-888888888,(X),434,None,194,None,26.9,None,10.7,None,172,None,82,None,10.7,None,5.0,None,52,None,43,None,3.2,None,2.8,None,88,None,86,None,5.4,None,5.3,None,869,None,258,None,53.8,None,10.0,None,551,None,280,None,-888888888,(X),-888888888,(X),1432,None,312,None,1432,None,-888888888,(X),716,None,280,None,50.0,None,11.7,None,202,None,92,None,14.1,None,7.2,None,70,None,40,None,4.9,None,3.0,None,40,None,44,None,2.8,None,3.0,None,404,None,135,None,28.2,None,8.6,None,8,None,13,None,-888888888,(X),-888888888,(X),1580,None,320,None,1580,None,-888888888,(X),968,None,285,None,61.3,None,9.8,None,223,None,127,None,14.1,None,8.2,None,83,None,61,None,5.3,None,3.8,None,29,None,34,None,1.8,None,2.2,None,73,None,70,None,4.6,None,4.3,None,0,None,21,None,0.0,None,1.9,None,204,None,87,None,12.9,None,5.4,None,35,None,48,None,-888888888,(X),-888888888,(X),8037,None,477,None,8037,None,-888888888,(X),23,None,25,None,0.3,None,0.3,None,436,None,185,None,5.4,None,2.3,None,287,None,129,None,3.6,None,1.6,None,892,None,227,None,11.1,None,2.7,None,814,None,217,None,10.1,None,2.7,None,869,None,247,None,10.8,None,2.9,None,4716,None,400,None,58.7,None,4.0,None,1865,None,167,None,-888888888,(X),-888888888,(X),77,None,65,None,-888888888,(X),-888888888,(X),7890,None,467,None,7890,None,-888888888,(X),1445,None,214,None,18.3,None,2.6,None,1104,None,269,None,14.0,None,3.2,None,860,None,250,None,10.9,None,2.9,None,948,None,206,None,12.0,None,2.6,None,732,None,235,None,9.3,None,2.9,None,2801,None,326,None,35.5,None,4.0,None,224,None,90,None,-888888888,(X),-888888888,(X),8600000US10001,ZCTA5 10001,8600000US10001

DP04_0124E number of rent house \
DP04_0132E median rent \
DP04_0079E number of owned house \
DP04_0088E median value \

In [ ]:
def process_rent2_response(response, year):
    """
    Convert Census API response to a DataFrame with selected columns and a year column.

    Parameters:
        response: requests.Response object from Census API
        year (str or int): Year of the data

    Returns:
        pd.DataFrame: Cleaned DataFrame with ['ucgid', 'year', 'S1901_C01_012E', 'S1901_C01_013E']
    """
    df = pd.DataFrame(response.json()[1:], columns=response.json()[0])
    df = df[['ucgid', 'DP04_0124E','DP04_0132E','DP04_0079E','DP04_0088E']]
    df['year'] = str(year)
    return df[['ucgid', 'year', 'DP04_0124E','DP04_0132E', 'DP04_0079E','DP04_0088E']]

In [ ]:
df_rent_2014 = process_rent2_response(response, 2014)
print(df_rent_2014.head())

            ucgid  year DP04_0124E DP04_0132E DP04_0079E DP04_0088E
0  8600000US10001  2014       8037       1865       3055     597600
1  8600000US10002  2014      27848        863       4370     544900
2  8600000US10003  2014      18653       1955       8537     863200
3  8600000US10004  2014       1018       2001        462     818600
4  8600000US10005  2014       3537       2001        544    1000001

#2013

In [ ]:
url = "https://api.census.gov/data/2013/acs/acs5/profile?get=group(DP04)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_rent_2013 = process_rent2_response(response, 2013)
print(df_rent_2013.head())

            ucgid  year DP04_0124E DP04_0132E DP04_0079E DP04_0088E
0  8600000US10001  2013       7944       1830       3007     650200
1  8600000US10002  2013      27894        848       4361     535600
2  8600000US10003  2013      18725       1855       8358     817700
3  8600000US10004  2013        988       2001        361     894200
4  8600000US10005  2013       3148       2001        560    1000001

# Merge df

In [ ]:
import pandas as pd

# Assuming df_rent_2013 to df_rent_2023 are already defined DataFrames

dfs = [df_rent_2023, df_rent_2022, df_rent_2021, df_rent_2020,
       df_rent_2019, df_rent_2018, df_rent_2017, df_rent_2016,
       df_rent_2015]

# Concatenate the DataFrames vertically (row-wise)
merged_df_rent_2315 = pd.concat(dfs, ignore_index=True)

print(merged_df_rent_2315.head())
merged_df_rent_2315.shape

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  860Z200US10001  2023      11399       3024       3570     793000
1  860Z200US10002  2023      28916       1207       6660     808500
2  860Z200US10003  2023      16196       2772       8701    1137000
3  860Z200US10004  2023       1145       3501        630    1866400
4  860Z200US10005  2023       4276       3501        880    1387200

(1920, 6)

In [ ]:
# Assuming df_rent_2013 to df_rent_2023 are already defined DataFrames

dfs = [df_rent_2014, df_rent_2013]

# Concatenate the DataFrames vertically (row-wise)
merged_df_rent_1413 = pd.concat(dfs, ignore_index=True)

print(merged_df_rent_1413.head())

            ucgid  year DP04_0124E DP04_0132E DP04_0079E DP04_0088E
0  8600000US10001  2014       8037       1865       3055     597600
1  8600000US10002  2014      27848        863       4370     544900
2  8600000US10003  2014      18653       1955       8537     863200
3  8600000US10004  2014       1018       2001        462     818600
4  8600000US10005  2014       3537       2001        544    1000001

In [ ]:
merged_df_rent_1413 = merged_df_rent_1413.rename(columns={
    'DP04_0124E': 'DP04_0126E',
    'DP04_0132E': 'DP04_0134E',
    'DP04_0079E': 'DP04_0080E',
    'DP04_0088E': 'DP04_0089E'
})

print(merged_df_rent_1413.head())
merged_df_rent_1413.shape

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  8600000US10001  2014       8037       1865       3055     597600
1  8600000US10002  2014      27848        863       4370     544900
2  8600000US10003  2014      18653       1955       8537     863200
3  8600000US10004  2014       1018       2001        462     818600
4  8600000US10005  2014       3537       2001        544    1000001

(428, 6)

In [ ]:
# Assuming df_rent_2013 to df_rent_2023 are already defined DataFrames

dfs = [merged_df_rent_2315, merged_df_rent_1413]

# Concatenate the DataFrames vertically (row-wise)
merged_df_rent = pd.concat(dfs, ignore_index=True)

print(merged_df_rent.head())
print(merged_df_rent.tail())

            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
0  860Z200US10001  2023      11399       3024       3570     793000
1  860Z200US10002  2023      28916       1207       6660     808500
2  860Z200US10003  2023      16196       2772       8701    1137000
3  860Z200US10004  2023       1145       3501        630    1866400
4  860Z200US10005  2023       4276       3501        880    1387200
               ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E
2343  8600000US11691  2013      13955       1012       4825     448200
2344  8600000US11692  2013       3918        875       2000     355800
2345  8600000US11693  2013       2419        831       1992     323100
2346  8600000US11694  2013       3494       1161       4570     623200
2347  8600000US11697  2013         52        908       1649     525600

In [ ]:
merged_df_rent.shape

(2348, 6)

# Education

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S1501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:

df_test = json_to_dataframe(response)

In [ ]:
df_test

,GEO_ID,NAME,S1501_C01_001E,S1501_C01_001EA,S1501_C01_001M,S1501_C01_001MA,S1501_C01_002E,S1501_C01_002EA,S1501_C01_002M,S1501_C01_002MA,S1501_C01_003E,S1501_C01_003EA,S1501_C01_003M,S1501_C01_003MA,S1501_C01_004E,S1501_C01_004EA,S1501_C01_004M,S1501_C01_004MA,S1501_C01_005E,S1501_C01_005EA,S1501_C01_005M,S1501_C01_005MA,S1501_C01_006E,S1501_C01_006EA,S1501_C01_006M,S1501_C01_006MA,S1501_C01_007E,S1501_C01_007EA,S1501_C01_007M,S1501_C01_007MA,S1501_C01_008E,S1501_C01_008EA,S1501_C01_008M,S1501_C01_008MA,S1501_C01_009E,S1501_C01_009EA,S1501_C01_009M,S1501_C01_009MA,S1501_C01_010E,S1501_C01_010EA,S1501_C01_010M,S1501_C01_010MA,S1501_C01_011E,S1501_C01_011EA,S1501_C01_011M,S1501_C01_011MA,S1501_C01_012E,S1501_C01_012EA,S1501_C01_012M,S1501_C01_012MA,S1501_C01_013E,S1501_C01_013EA,S1501_C01_013M,S1501_C01_013MA,S1501_C01_014E,S1501_C01_014EA,S1501_C01_014M,S1501_C01_014MA,S1501_C01_015E,S1501_C01_015EA,S1501_C01_015M,S1501_C01_015MA,S1501_C01_016E,S1501_C01_016EA,S1501_C01_016M,S1501_C01_016MA,S1501_C01_017E,S1501_C01_017EA,S1501_C01_017M,S1501_C01_017MA,S1501_C01_018E,S1501_C01_018EA,S1501_C01_018M,S1501_C01_018MA,S1501_C01_019E,S1501_C01_019EA,S1501_C01_019M,S1501_C01_019MA,S1501_C01_020E,S1501_C01_020EA,S1501_C01_020M,S1501_C01_020MA,S1501_C01_021E,S1501_C01_021EA,S1501_C01_021M,S1501_C01_021MA,S1501_C01_022E,S1501_C01_022EA,S1501_C01_022M,S1501_C01_022MA,S1501_C01_023E,S1501_C01_023EA,S1501_C01_023M,S1501_C01_023MA,S1501_C01_024E,S1501_C01_024EA,S1501_C01_024M,S1501_C01_024MA,S1501_C01_025E,S1501_C01_025EA,S1501_C01_025M,S1501_C01_025MA,S1501_C01_026E,S1501_C01_026EA,S1501_C01_026M,S1501_C01_026MA,S1501_C01_027E,S1501_C01_027EA,S1501_C01_027M,S1501_C01_027MA,S1501_C01_028E,S1501_C01_028EA,S1501_C01_028M,S1501_C01_028MA,S1501_C01_029E,S1501_C01_029EA,S1501_C01_029M,S1501_C01_029MA,S1501_C01_030E,S1501_C01_030EA,S1501_C01_030M,S1501_C01_030MA,S1501_C01_031E,S1501_C01_031EA,S1501_C01_031M,S1501_C01_031MA,S1501_C01_032E,S1501_C01_032EA,S1501_C01_032M,S1501_C01_032MA,S1501_C01_033E,S1501_C01_033EA,S1501_C01_033M,S1501_C01_033MA,S1501_C01_034E,S1501_C01_034EA,S1501_C01_034M,S1501_C01_034MA,S1501_C01_035E,S1501_C01_035EA,S1501_C01_035M,S1501_C01_035MA,S1501_C01_036E,S1501_C01_036EA,S1501_C01_036M,S1501_C01_036MA,S1501_C01_037E,S1501_C01_037EA,S1501_C01_037M,S1501_C01_037MA,S1501_C01_038E,S1501_C01_038EA,S1501_C01_038M,S1501_C01_038MA,S1501_C01_039E,S1501_C01_039EA,S1501_C01_039M,S1501_C01_039MA,S1501_C01_040E,S1501_C01_040EA,S1501_C01_040M,S1501_C01_040MA,S1501_C01_041E,S1501_C01_041EA,S1501_C01_041M,S1501_C01_041MA,S1501_C01_042E,S1501_C01_042EA,S1501_C01_042M,S1501_C01_042MA,S1501_C01_043E,S1501_C01_043EA,S1501_C01_043M,S1501_C01_043MA,S1501_C01_044E,S1501_C01_044EA,S1501_C01_044M,S1501_C01_044MA,S1501_C01_045E,S1501_C01_045EA,S1501_C01_045M,S1501_C01_045MA,S1501_C01_046E,S1501_C01_046EA,S1501_C01_046M,S1501_C01_046MA,S1501_C01_047E,S1501_C01_047EA,S1501_C01_047M,S1501_C01_047MA,S1501_C01_048E,S1501_C01_048EA,S1501_C01_048M,S1501_C01_048MA,S1501_C01_049E,S1501_C01_049EA,S1501_C01_049M,S1501_C01_049MA,S1501_C01_050E,S1501_C01_050EA,S1501_C01_050M,S1501_C01_050MA,S1501_C01_051E,S1501_C01_051EA,S1501_C01_051M,S1501_C01_051MA,S1501_C01_052E,S1501_C01_052EA,S1501_C01_052M,S1501_C01_052MA,S1501_C01_053E,S1501_C01_053EA,S1501_C01_053M,S1501_C01_053MA,S1501_C01_054E,S1501_C01_054EA,S1501_C01_054M,S1501_C01_054MA,S1501_C01_055E,S1501_C01_055EA,S1501_C01_055M,S1501_C01_055MA,S1501_C01_056E,S1501_C01_056EA,S1501_C01_056M,S1501_C01_056MA,S1501_C01_057E,S1501_C01_057EA,S1501_C01_057M,S1501_C01_057MA,S1501_C01_058E,S1501_C01_058EA,S1501_C01_058M,S1501_C01_058MA,S1501_C01_059E,S1501_C01_059EA,S1501_C01_059M,S1501_C01_059MA,S1501_C01_060E,S1501_C01_060EA,S1501_C01_060M,S1501_C01_060MA,S1501_C01_061E,S1501_C01_061EA,S1501_C01_061M,S1501_C01_061MA,S1501_C01_062E,S1501_C01_062EA,S1501_C01_062M,S1501_C01_062MA,S1501_C01_063E,S1501_C01_063EA,S1501_C01_063M,S1501_C01_063MA,S1501_C01_064E,S1501_C01_064EA,S1501_C01_064M,S1501_C01_064MA,S1501_C02_001E,S1501_C02_001EA,S1501_C02_001M,S1501_C02_001MA,S1501_C02_002E,S1501_C02_002EA,S1501_C02_002M,S1501_C02_002MA,S1501_C02_003E,S1501_C02_003EA,S1501_C02_003M,S1501_C02_003MA,S1501_C02_004E,S1501_C02_004EA,S1501_C02_004M,S1501_C02_004MA,S1501_C02_005E,S1501_C02_005EA,S1501_C02_005M,S1501_C02_005MA,S1501_C02_006E,S1501_C02_006EA,S1501_C02_006M,S1501_C02_006MA,S1501_C02_007E,S1501_C02_007EA,S1501_C02_007M,S1501_C02_007MA,S1501_C02_008E,S1501_C02_008EA,S1501_C02_008M,S1501_C02_008MA,S1501_C02_009E,S1501_C02_009EA,S1501_C02_009M,S1501_C02_009MA,S1501_C02_010E,S1501_C02_010EA,S1501_C02_010M,S1501_C02_010MA,S1501_C02_011E,S1501_C02_011EA,S1501_C02_011M,S1501_C02_011MA,S1501_C02_012E,S1501_C02_012EA,S1501_C02_012M,S1501_C02_012MA,S1501_C02_013E,S1501_C02_013EA,S1501_C02_013M,S1501_C02_013MA,S1501_C02_014E,S1501_C02_014EA,S1501_C02_014M,S1501_C02_014MA,S1501_C02_015E,S1501_C02_015EA,S1501_C02_015M,S1501_C02_015MA,S1501_C02_016E,S1501_C02_016EA,S1501_C02_016M,S1501_C02_016MA,S1501_C02_017E,S1501_C02_017EA,S1501_C02_017M,S1501_C02_017MA,S1501_C02_018E,S1501_C02_018EA,S1501_C02_018M,S1501_C02_018MA,S1501_C02_019E,S1501_C02_019EA,S1501_C02_019M,S1501_C02_019MA,S1501_C02_020E,S1501_C02_020EA,S1501_C02_020M,S1501_C02_020MA,S1501_C02_021E,S1501_C02_021EA,S1501_C02_021M,S1501_C02_021MA,S1501_C02_022E,S1501_C02_022EA,S1501_C02_022M,S1501_C02_022MA,S1501_C02_023E,S1501_C02_023EA,S1501_C02_023M,S1501_C02_023MA,S1501_C02_024E,S1501_C02_024EA,S1501_C02_024M,S1501_C02_024MA,S1501_C02_025E,S1501_C02_025EA,S1501_C02_025M,S1501_C02_025MA,S1501_C02_026E,S1501_C02_026EA,S1501_C02_026M,S1501_C02_026MA,S1501_C02_027E,S1501_C02_027EA,S1501_C02_027M,S1501_C02_027MA,S1501_C02_028E,S1501_C02_028EA,S1501_C02_028M,S1501_C02_028MA,S1501_C02_029E,S1501_C02_029EA,S1501_C02_029M,S1501_C02_029MA,S1501_C02_030E,S1501_C02_030EA,S1501_C02_030M,S1501_C02_030MA,S1501_C02_031E,S1501_C02_031EA,S1501_C02_031M,S1501_C02_031MA,S1501_C02_032E,S1501_C02_032EA,S1501_C02_032M,S1501_C02_032MA,S1501_C02_033E,S1501_C02_033EA,S1501_C02_033M,S1501_C02_033MA,S1501_C02_034E,S1501_C02_034EA,S1501_C02_034M,S1501_C02_034MA,S1501_C02_035E,S1501_C02_035EA,S1501_C02_035M,S1501_C02_035MA,S1501_C02_036E,S1501_C02_036EA,S1501_C02_036M,S1501_C02_036MA,S1501_C02_037E,S1501_C02_037EA,S1501_C02_037M,S1501_C02_037MA,S1501_C02_038E,S1501_C02_038EA,S1501_C02_038M,S1501_C02_038MA,S1501_C02_039E,S1501_C02_039EA,S1501_C02_039M,S1501_C02_039MA,S1501_C02_040E,S1501_C02_040EA,S1501_C02_040M,S1501_C02_040MA,S1501_C02_041E,S1501_C02_041EA,S1501_C02_041M,S1501_C02_041MA,S1501_C02_042E,S1501_C02_042EA,S1501_C02_042M,S1501_C02_042MA,S1501_C02_043E,S1501_C02_043EA,S1501_C02_043M,S1501_C02_043MA,S1501_C02_044E,S1501_C02_044EA,S1501_C02_044M,S1501_C02_044MA,S1501_C02_045E,S1501_C02_045EA,S1501_C02_045M,S1501_C02_045MA,S1501_C02_046E,S1501_C02_046EA,S1501_C02_046M,S1501_C02_046MA,S1501_C02_047E,S1501_C02_047EA,S1501_C02_047M,S1501_C02_047MA,S1501_C02_048E,S1501_C02_048EA,S1501_C02_048M,S1501_C02_048MA,S1501_C02_049E,S1501_C02_049EA,S1501_C02_049M,S1501_C02_049MA,S1501_C02_050E,S1501_C02_050EA,S1501_C02_050M,S1501_C02_050MA,S1501_C02_051E,S1501_C02_051EA,S1501_C02_051M,S1501_C02_051MA,S1501_C02_052E,S1501_C02_052EA,S1501_C02_052M,S1501_C02_052MA,S1501_C02_053E,S1501_C02_053EA,S1501_C02_053M,S1501_C02_053MA,S1501_C02_054E,S1501_C02_054EA,S1501_C02_054M,S1501_C02_054MA,S1501_C02_055E,S1501_C02_055EA,S1501_C02_055M,S1501_C02_055MA,S1501_C02_056E,S1501_C02_056EA,S1501_C02_056M,S1501_C02_056MA,S1501_C02_057E,S1501_C02_057EA,S1501_C02_057M,S1501_C02_057MA,S1501_C02_058E,S1501_C02_058EA,S1501_C02_058M,S1501_C02_058MA,S1501_C02_059E,S1501_C02_059EA,S1501_C02_059M,S1501_C02_059MA,S1501_C02_060E,S1501_C02_060EA,S1501_C02_060M,S1501_C02_060MA,S1501_C02_061E,S1501_C02_061EA,S1501_C02_061M,S1501_C02_061MA,S1501_C02_062E,S1501_C02_062EA,S1501_C02_062M,S1501_C02_062MA,S1501_C02_063E,S1501_C02_063EA,S1501_C02_063M,S1501_C02_063MA,S1501_C02_064E,S1501_C02_064EA,S1501_C02_064M,S1501_C02_064MA,S1501_C03_001E,S1501_C03_001EA,S1501_C03_001M,S1501_C03_001MA,S1501_C03_002E,S1501_C03_002EA,S1501_C03_002M,S1501_C03_002MA,S1501_C03_003E,S1501_C03_003EA,S1501_C03_003M,S1501_C03_003MA,S1501_C03_004E,S1501_C03_004EA,S1501_C03_004M,S1501_C03_004MA,S1501_C03_005E,S1501_C03_005EA,S1501_C03_005M,S1501_C03_005MA,S1501_C03_006E,S1501_C03_006EA,S1501_C03_006M,S1501_C03_006MA,S1501_C03_007E,S1501_C03_007EA,S1501_C03_007M,S1501_C03_007MA,S1501_C03_008E,S1501_C03_008EA,S1501_C03_008M,S1501_C03_008MA,S1501_C03_009E,S1501_C03_009EA,S1501_C03_009M,S1501_C03_009MA,S1501_C03_010E,S1501_C03_010EA,S1501_C03_010M,S1501_C03_010MA,S1501_C03_011E,S1501_C03_011EA,S1501_C03_011M,S1501_C03_011MA,S1501_C03_012E,S1501_C03_012EA,S1501_C03_012M,S1501_C03_012MA,S1501_C03_013E,S1501_C03_013EA,S1501_C03_013M,S1501_C03_013MA,S1501_C03_014E,S1501_C03_014EA,S1501_C03_014M,S1501_C03_014MA,S1501_C03_015E,S1501_C03_015EA,S1501_C03_015M,S1501_C03_015MA,S1501_C03_016E,S1501_C03_016EA,S1501_C03_016M,S1501_C03_016MA,S1501_C03_017E,S1501_C03_017EA,S1501_C03_017M,S1501_C03_017MA,S1501_C03_018E,S1501_C03_018EA,S1501_C03_018M,S1501_C03_018MA,S1501_C03_019E,S1501_C03_019EA,S1501_C03_019M,S1501_C03_019MA,S1501_C03_020E,S1501_C03_020EA,S1501_C03_020M,S1501_C03_020MA,S1501_C03_021E,S1501_C03_021EA,S1501_C03_021M,S1501_C03_021MA,S1501_C03_022E,S1501_C03_022EA,S1501_C03_022M,S1501_C03_022MA,S1501_C03_023E,S1501_C03_023EA,S1501_C03_023M,S1501_C03_023MA,S1501_C03_024E,S1501_C03_024EA,S1501_C03_024M,S1501_C03_024MA,S1501_C03_025E,S1501_C03_025EA,S1501_C03_025M,S1501_C03_025MA,S1501_C03_026E,S1501_C03_026EA,S1501_C03_026M,S1501_C03_026MA,S1501_C03_027E,S1501_C03_027EA,S1501_C03_027M,S1501_C03_027MA,S1501_C03_028E,S1501_C03_028EA,S1501_C03_028M,S1501_C03_028MA,S1501_C03_029E,S1501_C03_029EA,S1501_C03_029M,S1501_C03_029MA,S1501_C03_030E,S1501_C03_030EA,S1501_C03_030M,S1501_C03_030MA,S1501_C03_031E,S1501_C03_031EA,S1501_C03_031M,S1501_C03_031MA,S1501_C03_032E,S1501_C03_032EA,S1501_C03_032M,S1501_C03_032MA,S1501_C03_033E,S1501_C03_033EA,S1501_C03_033M,S1501_C03_033MA,S1501_C03_034E,S1501_C03_034EA,S1501_C03_034M,S1501_C03_034MA,S1501_C03_035E,S1501_C03_035EA,S1501_C03_035M,S1501_C03_035MA,S1501_C03_036E,S1501_C03_036EA,S1501_C03_036M,S1501_C03_036MA,S1501_C03_037E,S1501_C03_037EA,S1501_C03_037M,S1501_C03_037MA,S1501_C03_038E,S1501_C03_038EA,S1501_C03_038M,S1501_C03_038MA,S1501_C03_039E,S1501_C03_039EA,S1501_C03_039M,S1501_C03_039MA,S1501_C03_040E,S1501_C03_040EA,S1501_C03_040M,S1501_C03_040MA,S1501_C03_041E,S1501_C03_041EA,S1501_C03_041M,S1501_C03_041MA,S1501_C03_042E,S1501_C03_042EA,S1501_C03_042M,S1501_C03_042MA,S1501_C03_043E,S1501_C03_043EA,S1501_C03_043M,S1501_C03_043MA,S1501_C03_044E,S1501_C03_044EA,S1501_C03_044M,S1501_C03_044MA,S1501_C03_045E,S1501_C03_045EA,S1501_C03_045M,S1501_C03_045MA,S1501_C03_046E,S1501_C03_046EA,S1501_C03_046M,S1501_C03_046MA,S1501_C03_047E,S1501_C03_047EA,S1501_C03_047M,S1501_C03_047MA,S1501_C03_048E,S1501_C03_048EA,S1501_C03_048M,S1501_C03_048MA,S1501_C03_049E,S1501_C03_049EA,S1501_C03_049M,S1501_C03_049MA,S1501_C03_050E,S1501_C03_050EA,S1501_C03_050M,S1501_C03_050MA,S1501_C03_051E,S1501_C03_051EA,S1501_C03_051M,S1501_C03_051MA,S1501_C03_052E,S1501_C03_052EA,S1501_C03_052M,S1501_C03_052MA,S1501_C03_053E,S1501_C03_053EA,S1501_C03_053M,S1501_C03_053MA,S1501_C03_054E,S1501_C03_054EA,S1501_C03_054M,S1501_C03_054MA,S1501_C03_055E,S1501_C03_055EA,S1501_C03_055M,S1501_C03_055MA,S1501_C03_056E,S1501_C03_056EA,S1501_C03_056M,S1501_C03_056MA,S1501_C03_057E,S1501_C03_057EA,S1501_C03_057M,S1501_C03_057MA,S1501_C03_058E,S1501_C03_058EA,S1501_C03_058M,S1501_C03_058MA,S1501_C03_059E,S1501_C03_059EA,S1501_C03_059M,S1501_C03_059MA,S1501_C03_060E,S1501_C03_060EA,S1501_C03_060M,S1501_C03_060MA,S1501_C03_061E,S1501_C03_061EA,S1501_C03_061M,S1501_C03_061MA,S1501_C03_062E,S1501_C03_062EA,S1501_C03_062M,S1501_C03_062MA,S1501_C03_063E,S1501_C03_063EA,S1501_C03_063M,S1501_C03_063MA,S1501_C03_064E,S1501_C03_064EA,S1501_C03_064M,S1501_C03_064MA,S1501_C04_001E,S1501_C04_001EA,S1501_C04_001M,S1501_C04_001MA,S1501_C04_002E,S1501_C04_002EA,S1501_C04_002M,S1501_C04_002MA,S1501_C04_003E,S1501_C04_003EA,S1501_C04_003M,S1501_C04_003MA,S1501_C04_004E,S1501_C04_004EA,S1501_C04_004M,S1501_C04_004MA,S1501_C04_005E,S1501_C04_005EA,S1501_C04_005M,S1501_C04_005MA,S1501_C04_006E,S1501_C04_006EA,S1501_C04_006M,S1501_C04_006MA,S1501_C04_007E,S1501_C04_007EA,S1501_C04_007M,S1501_C04_007MA,S1501_C04_008E,S1501_C04_008EA,S1501_C04_008M,S1501_C04_008MA,S1501_C04_009E,S1501_C04_009EA,S1501_C04_009M,S1501_C04_009MA,S1501_C04_010E,S1501_C04_010EA,S1501_C04_010M,S1501_C04_010MA,S1501_C04_011E,S1501_C04_011EA,S1501_C04_011M,S1501_C04_011MA,S1501_C04_012E,S1501_C04_012EA,S1501_C04_012M,S1501_C04_012MA,S1501_C04_013E,S1501_C04_013EA,S1501_C04_013M,S1501_C04_013MA,S1501_C04_014E,S1501_C04_014EA,S1501_C04_014M,S1501_C04_014MA,S1501_C04_015E,S1501_C04_015EA,S1501_C04_015M,S1501_C04_015MA,S1501_C04_016E,S1501_C04_016EA,S1501_C04_016M,S1501_C04_016MA,S1501_C04_017E,S1501_C04_017EA,S1501_C04_017M,S1501_C04_017MA,S1501_C04_018E,S1501_C04_018EA,S1501_C04_018M,S1501_C04_018MA,S1501_C04_019E,S1501_C04_019EA,S1501_C04_019M,S1501_C04_019MA,S1501_C04_020E,S1501_C04_020EA,S1501_C04_020M,S1501_C04_020MA,S1501_C04_021E,S1501_C04_021EA,S1501_C04_021M,S1501_C04_021MA,S1501_C04_022E,S1501_C04_022EA,S1501_C04_022M,S1501_C04_022MA,S1501_C04_023E,S1501_C04_023EA,S1501_C04_023M,S1501_C04_023MA,S1501_C04_024E,S1501_C04_024EA,S1501_C04_024M,S1501_C04_024MA,S1501_C04_025E,S1501_C04_025EA,S1501_C04_025M,S1501_C04_025MA,S1501_C04_026E,S1501_C04_026EA,S1501_C04_026M,S1501_C04_026MA,S1501_C04_027E,S1501_C04_027EA,S1501_C04_027M,S1501_C04_027MA,S1501_C04_028E,S1501_C04_028EA,S1501_C04_028M,S1501_C04_028MA,S1501_C04_029E,S1501_C04_029EA,S1501_C04_029M,S1501_C04_029MA,S1501_C04_030E,S1501_C04_030EA,S1501_C04_030M,S1501_C04_030MA,S1501_C04_031E,S1501_C04_031EA,S1501_C04_031M,S1501_C04_031MA,S1501_C04_032E,S1501_C04_032EA,S1501_C04_032M,S1501_C04_032MA,S1501_C04_033E,S1501_C04_033EA,S1501_C04_033M,S1501_C04_033MA,S1501_C04_034E,S1501_C04_034EA,S1501_C04_034M,S1501_C04_034MA,S1501_C04_035E,S1501_C04_035EA,S1501_C04_035M,S1501_C04_035MA,S1501_C04_036E,S1501_C04_036EA,S1501_C04_036M,S1501_C04_036MA,S1501_C04_037E,S1501_C04_037EA,S1501_C04_037M,S1501_C04_037MA,S1501_C04_038E,S1501_C04_038EA,S1501_C04_038M,S1501_C04_038MA,S1501_C04_039E,S1501_C04_039EA,S1501_C04_039M,S1501_C04_039MA,S1501_C04_040E,S1501_C04_040EA,S1501_C04_040M,S1501_C04_040MA,S1501_C04_041E,S1501_C04_041EA,S1501_C04_041M,S1501_C04_041MA,S1501_C04_042E,S1501_C04_042EA,S1501_C04_042M,S1501_C04_042MA,S1501_C04_043E,S1501_C04_043EA,S1501_C04_043M,S1501_C04_043MA,S1501_C04_044E,S1501_C04_044EA,S1501_C04_044M,S1501_C04_044MA,S1501_C04_045E,S1501_C04_045EA,S1501_C04_045M,S1501_C04_045MA,S1501_C04_046E,S1501_C04_046EA,S1501_C04_046M,S1501_C04_046MA,S1501_C04_047E,S1501_C04_047EA,S1501_C04_047M,S1501_C04_047MA,S1501_C04_048E,S1501_C04_048EA,S1501_C04_048M,S1501_C04_048MA,S1501_C04_049E,S1501_C04_049EA,S1501_C04_049M,S1501_C04_049MA,S1501_C04_050E,S1501_C04_050EA,S1501_C04_050M,S1501_C04_050MA,S1501_C04_051E,S1501_C04_051EA,S1501_C04_051M,S1501_C04_051MA,S1501_C04_052E,S1501_C04_052EA,S1501_C04_052M,S1501_C04_052MA,S1501_C04_053E,S1501_C04_053EA,S1501_C04_053M,S1501_C04_053MA,S1501_C04_054E,S1501_C04_054EA,S1501_C04_054M,S1501_C04_054MA,S1501_C04_055E,S1501_C04_055EA,S1501_C04_055M,S1501_C04_055MA,S1501_C04_056E,S1501_C04_056EA,S1501_C04_056M,S1501_C04_056MA,S1501_C04_057E,S1501_C04_057EA,S1501_C04_057M,S1501_C04_057MA,S1501_C04_058E,S1501_C04_058EA,S1501_C04_058M,S1501_C04_058MA,S1501_C04_059E,S1501_C04_059EA,S1501_C04_059M,S1501_C04_059MA,S1501_C04_060E,S1501_C04_060EA,S1501_C04_060M,S1501_C04_060MA,S1501_C04_061E,S1501_C04_061EA,S1501_C04_061M,S1501_C04_061MA,S1501_C04_062E,S1501_C04_062EA,S1501_C04_062M,S1501_C04_062MA,S1501_C04_063E,S1501_C04_063EA,S1501_C04_063M,S1501_C04_063MA,S1501_C04_064E,S1501_C04_064EA,S1501_C04_064M,S1501_C04_064MA,S1501_C05_001E,S1501_C05_001EA,S1501_C05_001M,S1501_C05_001MA,S1501_C05_002E,S1501_C05_002EA,S1501_C05_002M,S1501_C05_002MA,S1501_C05_003E,S1501_C05_003EA,S1501_C05_003M,S1501_C05_003MA,S1501_C05_004E,S1501_C05_004EA,S1501_C05_004M,S1501_C05_004MA,S1501_C05_005E,S1501_C05_005EA,S1501_C05_005M,S1501_C05_005MA,S1501_C05_006E,S1501_C05_006EA,S1501_C05_006M,S1501_C05_006MA,S1501_C05_007E,S1501_C05_007EA,S1501_C05_007M,S1501_C05_007MA,S1501_C05_008E,S1501_C05_008EA,S1501_C05_008M,S1501_C05_008MA,S1501_C05_009E,S1501_C05_009EA,S1501_C05_009M,S1501_C05_009MA,S1501_C05_010E,S1501_C05_010EA,S1501_C05_010M,S1501_C05_010MA,S1501_C05_011E,S1501_C05_011EA,S1501_C05_011M,S1501_C05_011MA,S1501_C05_012E,S1501_C05_012EA,S1501_C05_012M,S1501_C05_012MA,S1501_C05_013E,S1501_C05_013EA,S1501_C05_013M,S1501_C05_013MA,S1501_C05_014E,S1501_C05_014EA,S1501_C05_014M,S1501_C05_014MA,S1501_C05_015E,S1501_C05_015EA,S1501_C05_015M,S1501_C05_015MA,S1501_C05_016E,S1501_C05_016EA,S1501_C05_016M,S1501_C05_016MA,S1501_C05_017E,S1501_C05_017EA,S1501_C05_017M,S1501_C05_017MA,S1501_C05_018E,S1501_C05_018EA,S1501_C05_018M,S1501_C05_018MA,S1501_C05_019E,S1501_C05_019EA,S1501_C05_019M,S1501_C05_019MA,S1501_C05_020E,S1501_C05_020EA,S1501_C05_020M,S1501_C05_020MA,S1501_C05_021E,S1501_C05_021EA,S1501_C05_021M,S1501_C05_021MA,S1501_C05_022E,S1501_C05_022EA,S1501_C05_022M,S1501_C05_022MA,S1501_C05_023E,S1501_C05_023EA,S1501_C05_023M,S1501_C05_023MA,S1501_C05_024E,S1501_C05_024EA,S1501_C05_024M,S1501_C05_024MA,S1501_C05_025E,S1501_C05_025EA,S1501_C05_025M,S1501_C05_025MA,S1501_C05_026E,S1501_C05_026EA,S1501_C05_026M,S1501_C05_026MA,S1501_C05_027E,S1501_C05_027EA,S1501_C05_027M,S1501_C05_027MA,S1501_C05_028E,S1501_C05_028EA,S1501_C05_028M,S1501_C05_028MA,S1501_C05_029E,S1501_C05_029EA,S1501_C05_029M,S1501_C05_029MA,S1501_C05_030E,S1501_C05_030EA,S1501_C05_030M,S1501_C05_030MA,S1501_C05_031E,S1501_C05_031EA,S1501_C05_031M,S1501_C05_031MA,S1501_C05_032E,S1501_C05_032EA,S1501_C05_032M,S1501_C05_032MA,S1501_C05_033E,S1501_C05_033EA,S1501_C05_033M,S1501_C05_033MA,S1501_C05_034E,S1501_C05_034EA,S1501_C05_034M,S1501_C05_034MA,S1501_C05_035E,S1501_C05_035EA,S1501_C05_035M,S1501_C05_035MA,S1501_C05_036E,S1501_C05_036EA,S1501_C05_036M,S1501_C05_036MA,S1501_C05_037E,S1501_C05_037EA,S1501_C05_037M,S1501_C05_037MA,S1501_C05_038E,S1501_C05_038EA,S1501_C05_038M,S1501_C05_038MA,S1501_C05_039E,S1501_C05_039EA,S1501_C05_039M,S1501_C05_039MA,S1501_C05_040E,S1501_C05_040EA,S1501_C05_040M,S1501_C05_040MA,S1501_C05_041E,S1501_C05_041EA,S1501_C05_041M,S1501_C05_041MA,S1501_C05_042E,S1501_C05_042EA,S1501_C05_042M,S1501_C05_042MA,S1501_C05_043E,S1501_C05_043EA,S1501_C05_043M,S1501_C05_043MA,S1501_C05_044E,S1501_C05_044EA,S1501_C05_044M,S1501_C05_044MA,S1501_C05_045E,S1501_C05_045EA,S1501_C05_045M,S1501_C05_045MA,S1501_C05_046E,S1501_C05_046EA,S1501_C05_046M,S1501_C05_046MA,S1501_C05_047E,S1501_C05_047EA,S1501_C05_047M,S1501_C05_047MA,S1501_C05_048E,S1501_C05_048EA,S1501_C05_048M,S1501_C05_048MA,S1501_C05_049E,S1501_C05_049EA,S1501_C05_049M,S1501_C05_049MA,S1501_C05_050E,S1501_C05_050EA,S1501_C05_050M,S1501_C05_050MA,S1501_C05_051E,S1501_C05_051EA,S1501_C05_051M,S1501_C05_051MA,S1501_C05_052E,S1501_C05_052EA,S1501_C05_052M,S1501_C05_052MA,S1501_C05_053E,S1501_C05_053EA,S1501_C05_053M,S1501_C05_053MA,S1501_C05_054E,S1501_C05_054EA,S1501_C05_054M,S1501_C05_054MA,S1501_C05_055E,S1501_C05_055EA,S1501_C05_055M,S1501_C05_055MA,S1501_C05_056E,S1501_C05_056EA,S1501_C05_056M,S1501_C05_056MA,S1501_C05_057E,S1501_C05_057EA,S1501_C05_057M,S1501_C05_057MA,S1501_C05_058E,S1501_C05_058EA,S1501_C05_058M,S1501_C05_058MA,S1501_C05_059E,S1501_C05_059EA,S1501_C05_059M,S1501_C05_059MA,S1501_C05_060E,S1501_C05_060EA,S1501_C05_060M,S1501_C05_060MA,S1501_C05_061E,S1501_C05_061EA,S1501_C05_061M,S1501_C05_061MA,S1501_C05_062E,S1501_C05_062EA,S1501_C05_062M,S1501_C05_062MA,S1501_C05_063E,S1501_C05_063EA,S1501_C05_063M,S1501_C05_063MA,S1501_C05_064E,S1501_C05_064EA,S1501_C05_064M,S1501_C05_064MA,S1501_C06_001E,S1501_C06_001EA,S1501_C06_001M,S1501_C06_001MA,S1501_C06_002E,S1501_C06_002EA,S1501_C06_002M,S1501_C06_002MA,S1501_C06_003E,S1501_C0

In [ ]:
'''
S1501_C01_006E = Population 25 years and over
S1501_C01_007E = Less than 9th grade
S1501_C01_008E = 9th to 12th grade
S1501_C01_009E = High school graduate
S1501_C01_010E = Some college, no degree
S1501_C01_011E = Associate's degree
S1501_C01_012E = Bachelor's degree
S1501_C01_013E = Graduate or professional degree
'''

"\nS1501_C01_006E = Population 25 years and over\nS1501_C01_007E = Less than 9th grade\nS1501_C01_008E = 9th to 12th grade\nS1501_C01_009E = High school graduate\nS1501_C01_010E = Some college, no degree\nS1501_C01_011E = Associate's degree\nS1501_C01_012E = Bachelor's degree\nS1501_C01_013E = Graduate or professional degree\n"

In [ ]:
def process_education_response(response, year):

    df = pd.DataFrame(response.json()[1:], columns=response.json()[0])
    df = df[['ucgid', 'S1501_C01_006E','S1501_C01_007E','S1501_C01_008E','S1501_C01_009E','S1501_C01_010E', 'S1501_C01_011E', 'S1501_C01_012E', 'S1501_C01_013E']]
    df['year'] = str(year)
    return df[['ucgid', 'year', 'S1501_C01_006E','S1501_C01_007E','S1501_C01_008E','S1501_C01_009E','S1501_C01_010E', 'S1501_C01_011E', 'S1501_C01_012E', 'S1501_C01_013E']]

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S1501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2023 = process_education_response(response, 2023)
print(df_education_2023.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2023          22724            480           1144
1  860Z200US10002  2023          59418           8193           9041
2  860Z200US10003  2023          36544           1090            480
3  860Z200US10004  2023           3010             16             11
4  860Z200US10005  2023           7325             65            122

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           1963           2162            727           9424           6824
1          10531           6148           2359          15771           7375
2           1755           2255            925          16346          13693
3             50            192              5           1283           1453
4            430            475             61           3703           2469

In [ ]:
url = "https://api.census.gov/data/2022/acs/acs5/subject?get=group(S1501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2022 = process_education_response(response, 2022)
print(df_education_2022.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2022          21203            741           1189
1  860Z200US10002  2022          60952           9858           8443
2  860Z200US10003  2022          37093           1001            573
3  860Z200US10004  2022           3586             16             16
4  860Z200US10005  2022           6842             64            104

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           1802           1771            661           8911           6128
1          11085           5998           2347          16087           7134
2           1984           2222            912          16265          14136
3             31            124             11           1588           1800
4            342            195             65           3870           2202

In [ ]:
url = "https://api.census.gov/data/2021/acs/acs5/subject?get=group(S1501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2021 = process_education_response(response, 2021)
print(df_education_2021.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2021          21296            673            865
1  860Z200US10002  2021          60747          10592           8984
2  860Z200US10003  2021          37589            982            378
3  860Z200US10004  2021           3624             12              1
4  860Z200US10005  2021           6829              6              0

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           1771           1779            632           9303           6273
1          10887           5742           2444          15502           6596
2           1915           2199           1153          16510          14452
3             22             58             32           1927           1572
4            370             72             52           3940           2389

In [ ]:
url = "https://api.census.gov/data/2020/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2020 = process_education_response(response, 2020)
print(df_education_2020.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2020          19550            845            633
1  8600000US10002  2020          58942          11227           8729
2  8600000US10003  2020          38411           1108            592
3  8600000US10004  2020           2899             12              1
4  8600000US10005  2020           6698             15              2

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           1945           1431            579           8571           5546
1          10996           5190           2459          14061           6280
2           1991           2137           1408          17347          13828
3             60             79             22           1324           1401
4            434             79             28           3451           2689

In [ ]:
url = "https://api.census.gov/data/2019/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2019 = process_education_response(response, 2019)
print(df_education_2019.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2019          19052            892            862
1  8600000US10002  2019          59346          11735           8268
2  8600000US10003  2019          37899           1110            575
3  8600000US10004  2019           2837             29              1
4  8600000US10005  2019           6449             13              2

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           2305           1454            536           7560           5443
1          11342           5562           2626          13208           6605
2           2273           2656           1149          16374          13762
3             76            103             22           1269           1337
4            286            137            186           3289           2536

In [ ]:
url = "https://api.census.gov/data/2018/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2018 = process_education_response(response, 2018)
print(df_education_2018.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2018          17985            763            720
1  8600000US10002  2018          59160          12443           7695
2  8600000US10003  2018          38236            849            637
3  8600000US10004  2018           2547             27              1
4  8600000US10005  2018           6586             48              3

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           2219           1462            588           6810           5423
1          11597           4963           2372          12928           7162
2           2279           2634           1178          16227          14432
3             55            147             14           1210           1093
4            296            141            273           3191           2634

In [ ]:
url = "https://api.census.gov/data/2017/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2017 = process_education_response(response, 2017)
print(df_education_2017.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2017          17839            572            522
1  8600000US10002  2017          60938          12339           7913
2  8600000US10003  2017          39339            715            662
3  8600000US10004  2017           2409             33              1
4  8600000US10005  2017           6403             41              4

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           2151           1634            428           6963           5569
1          12247           5816           2434          13236           6953
2           2074           3094           1175          17264          14355
3             49            111             35           1227            953
4            340            109            244           2869           2796

In [ ]:
url = "https://api.census.gov/data/2016/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2016 = process_education_response(response, 2016)
print(df_education_2016.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2016          17371            658            568
1  8600000US10002  2016          60343          12352           6739
2  8600000US10003  2016          40442            905            690
3  8600000US10004  2016           2343             30              0
4  8600000US10005  2016           6521             32             59

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           2352           1616            382           6249           5546
1          12219           5975           2450          13807           6801
2           2428           3035           1099          17415          14870
3             52            175             38           1119            929
4            231            220            219           3053           2707

In [ ]:
url = "https://api.census.gov/data/2015/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2015 = process_education_response(response, 2015)
print(df_education_2015.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2015          17148            736            623
1  8600000US10002  2015          61588          13276           6464
2  8600000US10003  2015          40870            721            599
3  8600000US10004  2015           2351             24              0
4  8600000US10005  2015           6256             16             57

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           2314           1669            365           5932           5509
1          12676           5838           3129          14072           6133
2           2796           3559            978          17386          14831
3             73            183             48           1118            905
4            161            285            219           3016           2502

#2014~2013 = percent

In [ ]:
url = "https://api.census.gov/data/2014/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2014 = process_education_response(response, 2014)
print(df_education_2014.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2014          16328            4.9            3.6
1  8600000US10002  2014          60932           23.3           11.4
2  8600000US10003  2014          41182            1.9            1.7
3  8600000US10004  2014           2279            0.5            0.7
4  8600000US10005  2014           5954            1.3            0.9

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           10.2            9.9            2.8           37.1           31.5
1           20.9            9.9            4.1           20.9            9.5
2            6.8            8.5            2.4           43.6           35.0
3            3.8           10.6            2.8           43.2           38.4
4            1.7            6.5            1.1           46.1           42.3

In [ ]:
url = "https://api.census.gov/data/2013/acs/acs5/subject?get=group(S1501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_education_2013 = process_education_response(response, 2013)
print(df_education_2013.head())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  8600000US10001  2013          15876            4.1            4.0
1  8600000US10002  2013          62471           24.6           11.4
2  8600000US10003  2013          41525            1.9            2.1
3  8600000US10004  2013           2087            0.3            1.6
4  8600000US10005  2013           5403            1.2            1.1

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0            8.4           10.9            3.2           37.5           31.8
1           20.1           10.7            4.0           20.8            8.5
2            7.0            9.5            1.9           42.9           34.8
3            6.2            9.4            4.0           41.6           36.8
4            1.0            7.4            0.7           47.8           40.9

#merge df

In [ ]:
  dfs = [df_education_2023, df_education_2022, df_education_2021, df_education_2020,
       df_education_2019, df_education_2018, df_education_2017, df_education_2016,
       df_education_2015]

# Concatenate the DataFrames vertically (row-wise)
merged_df_education = pd.concat(dfs, ignore_index=True)

print(merged_df_education.head())
print(merged_df_education.tail())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2023          22724            480           1144
1  860Z200US10002  2023          59418           8193           9041
2  860Z200US10003  2023          36544           1090            480
3  860Z200US10004  2023           3010             16             11
4  860Z200US10005  2023           7325             65            122

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0           1963           2162            727           9424           6824
1          10531           6148           2359          15771           7375
2           1755           2255            925          16346          13693
3             50            192              5           1283           1453
4            430            475             61           3703           2469
               ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
1915  8600000US11691  2015          38348           4945           6222
1916  8600000US11692  2015          12098           1441           1756
1917  8600000US11693  2015           7747            252           1049
1918  8600000US11694  2015          15114            704           1128
1919  8600000US11697  2015           2715             28             50

     S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E  \
1915          10285           6112           2513           5092
1916           3254           2104           1128           1552
1917           2452           1624            487           1398
1918           2949           3141           1385           3268
1919            666            481            165            729

     S1501_C01_013E
1915           3179
1916            863
1917            485
1918           2539
1919            596

In [ ]:
# First, convert all columns to numeric (just in case some are strings)
merged_df_education = merged_df_education.apply(pd.to_numeric, errors='ignore')

# Store total column separately
total_col = 'S1501_C01_006E'

# Columns to calculate percent for (exclude 'ucgid', 'year', and the total column itself)
percent_cols = [col for col in merged_df_education.columns
                if col not in ['ucgid', 'year', total_col]]

# Create percent columns
for col in percent_cols:
    pct_col = col + '_pct'
    merged_df_education[pct_col] = (merged_df_education[col] / merged_df_education[total_col]) * 100

In [ ]:
# Keep total column and all percentage columns
cols_to_keep = ['S1501_C01_006E'] + [col for col in merged_df_education.columns if col.endswith('_pct')]

# Also keep 'ucgid' and 'year' for context
cols_to_keep = ['ucgid', 'year'] + cols_to_keep

# Subset the DataFrame
merged_df_education = merged_df_education[cols_to_keep]

# Optional: reset index
merged_df_education = merged_df_education.reset_index(drop=True)

merged_df_education.columns = [
    col.replace('_pct', '') if col.endswith('_pct') else col
    for col in merged_df_education.columns
]

In [ ]:
  dfs = [merged_df_education, df_education_2014,
       df_education_2013]

# Concatenate the DataFrames vertically (row-wise)
merged_df_education_pct = pd.concat(dfs, ignore_index=True)

print(merged_df_education_pct.head())
print(merged_df_education_pct.tail())

            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2023          22724       2.112304       5.034325
1  860Z200US10002  2023          59418      13.788751      15.215928
2  860Z200US10003  2023          36544       2.982706       1.313485
3  860Z200US10004  2023           3010       0.531561       0.365449
4  860Z200US10005  2023           7325       0.887372       1.665529

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E
0       8.638444        9.51417       3.199261      41.471572      30.029924
1      17.723585      10.347033       3.970177      26.542462      12.412064
2        4.80243       6.170644       2.531195      44.729641      37.469899
3        1.66113       6.378738       0.166113      42.624585      48.272425
4       5.870307       6.484642       0.832765      50.552901      33.706485
               ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
2343  8600000US11691  2013          35984           12.5           14.4
2344  8600000US11692  2013          11102           10.7           13.6
2345  8600000US11693  2013           7664            3.4           15.5
2346  8600000US11694  2013          15705            5.1            6.9
2347  8600000US11697  2013           3085            1.8            3.7

     S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E  \
2343           28.3           16.9            6.4           13.5
2344           28.7           19.9            7.8           13.0
2345           30.2           19.5            7.4           17.2
2346           22.7           19.2            8.4           19.8
2347           27.4           16.1            6.8           24.9

     S1501_C01_013E
2343            8.0
2344            6.2
2345            6.6
2346           17.7
2347           19.3

In [ ]:
# dictionary

'''
S1901_C01_001E = number of household
S1901_C01_012E = household median income (1year estimate)
S1901_C01_013E = household mean income (1year estimate)
DP04_0126E = number of rent home
DP04_0134E = Median rent
DP04_0080E = number of owned home
DP04_0089E = Median home value
S1501_C01_006E = Population 25 years and over
S1501_C01_007E = Less than 9th grade
S1501_C01_008E = 9th to 12th grade
S1501_C01_009E = High school graduate
S1501_C01_010E = Some college, no degree
S1501_C01_011E = Associate's degree
S1501_C01_012E = Bachelor's degree
S1501_C01_013E = Graduate or professional degree
'''

"\nS1901_C01_001E = number of household\nS1901_C01_012E = household median income (1year estimate)\nS1901_C01_013E = household mean income (1year estimate)\nDP04_0126E = number of rent home\nDP04_0134E = Median rent\nDP04_0080E = number of owned home\nDP04_0089E = Median home value\nS1501_C01_006E = Population 25 years and over\nS1501_C01_007E = Less than 9th grade\nS1501_C01_008E = 9th to 12th grade\nS1501_C01_009E = High school graduate\nS1501_C01_010E = Some college, no degree\nS1501_C01_011E = Associate's degree\nS1501_C01_012E = Bachelor's degree\nS1501_C01_013E = Graduate or professional degree\n"

In [ ]:
print(merged_df_income.head())
print(merged_df_rent.head())
print(merged_df_education_pct.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E   zcta  \
0  860Z200US10001  2023          15097         123393         205444  10001
1  860Z200US10002  2023          35771          46525          93314  10002
2  860Z200US10003  2023          25080         153750         248577  10003
3  860Z200US10004  2023           1775         220592         309645  10004
4  860Z200US10005  2023           5156         211810         279387  10005

    merge_key
0  2023_10001
1  2023_10002
2  2023_10003
3  2023_10004
4  2023_10005
            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E   zcta  \
0  860Z200US10001  2023      11399       3024       3570     793000  10001
1  860Z200US10002  2023      28916       1207       6660     808500  10002
2  860Z200US10003  2023      16196       2772       8701    1137000  10003
3  860Z200US10004  2023       1145       3501        630    1866400  10004
4  860Z200US10005  2023       4276       3501        880    1387200  10005

    merge_key
0  2023_10001
1  2023_10002
2  2023_10003
3  2023_10004
4  2023_10005
            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2023          22724       2.112304       5.034325
1  860Z200US10002  2023          59418      13.788751      15.215928
2  860Z200US10003  2023          36544       2.982706       1.313485
3  860Z200US10004  2023           3010       0.531561       0.365449
4  860Z200US10005  2023           7325       0.887372       1.665529

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E  \
0       8.638444        9.51417       3.199261      41.471572      30.029924
1      17.723585      10.347033       3.970177      26.542462      12.412064
2        4.80243       6.170644       2.531195      44.729641      37.469899
3        1.66113       6.378738       0.166113      42.624585      48.272425
4       5.870307       6.484642       0.832765      50.552901      33.706485

    zcta
0  10001
1  10002
2  10003
3  10004
4  10005

In [ ]:
for df in [merged_df_income, merged_df_rent, merged_df_education_pct]:
    df['zcta'] = df['ucgid'].str[-5:]

In [ ]:
print(merged_df_income.head())
print(merged_df_rent.head())
print(merged_df_education_pct.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E   zcta  \
0  860Z200US10001  2023          15097         123393         205444  10001
1  860Z200US10002  2023          35771          46525          93314  10002
2  860Z200US10003  2023          25080         153750         248577  10003
3  860Z200US10004  2023           1775         220592         309645  10004
4  860Z200US10005  2023           5156         211810         279387  10005

    merge_key
0  2023_10001
1  2023_10002
2  2023_10003
3  2023_10004
4  2023_10005
            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E   zcta  \
0  860Z200US10001  2023      11399       3024       3570     793000  10001
1  860Z200US10002  2023      28916       1207       6660     808500  10002
2  860Z200US10003  2023      16196       2772       8701    1137000  10003
3  860Z200US10004  2023       1145       3501        630    1866400  10004
4  860Z200US10005  2023       4276       3501        880    1387200  10005

    merge_key
0  2023_10001
1  2023_10002
2  2023_10003
3  2023_10004
4  2023_10005
            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2023          22724       2.112304       5.034325
1  860Z200US10002  2023          59418      13.788751      15.215928
2  860Z200US10003  2023          36544       2.982706       1.313485
3  860Z200US10004  2023           3010       0.531561       0.365449
4  860Z200US10005  2023           7325       0.887372       1.665529

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E  \
0       8.638444        9.51417       3.199261      41.471572      30.029924
1      17.723585      10.347033       3.970177      26.542462      12.412064
2        4.80243       6.170644       2.531195      44.729641      37.469899
3        1.66113       6.378738       0.166113      42.624585      48.272425
4       5.870307       6.484642       0.832765      50.552901      33.706485

    zcta
0  10001
1  10002
2  10003
3  10004
4  10005

In [ ]:
for df in [merged_df_income, merged_df_rent, merged_df_education_pct]:
    # Ensure year is string before combining
    df['merge_key'] = df['year'].astype(str) + "_" + df['zcta']

In [ ]:
print(merged_df_income.head())
print(merged_df_rent.head())
print(merged_df_education_pct.head())

            ucgid  year S1901_C01_001E S1901_C01_012E S1901_C01_013E   zcta  \
0  860Z200US10001  2023          15097         123393         205444  10001
1  860Z200US10002  2023          35771          46525          93314  10002
2  860Z200US10003  2023          25080         153750         248577  10003
3  860Z200US10004  2023           1775         220592         309645  10004
4  860Z200US10005  2023           5156         211810         279387  10005

    merge_key
0  2023_10001
1  2023_10002
2  2023_10003
3  2023_10004
4  2023_10005
            ucgid  year DP04_0126E DP04_0134E DP04_0080E DP04_0089E   zcta  \
0  860Z200US10001  2023      11399       3024       3570     793000  10001
1  860Z200US10002  2023      28916       1207       6660     808500  10002
2  860Z200US10003  2023      16196       2772       8701    1137000  10003
3  860Z200US10004  2023       1145       3501        630    1866400  10004
4  860Z200US10005  2023       4276       3501        880    1387200  10005

    merge_key
0  2023_10001
1  2023_10002
2  2023_10003
3  2023_10004
4  2023_10005
            ucgid  year S1501_C01_006E S1501_C01_007E S1501_C01_008E  \
0  860Z200US10001  2023          22724       2.112304       5.034325
1  860Z200US10002  2023          59418      13.788751      15.215928
2  860Z200US10003  2023          36544       2.982706       1.313485
3  860Z200US10004  2023           3010       0.531561       0.365449
4  860Z200US10005  2023           7325       0.887372       1.665529

  S1501_C01_009E S1501_C01_010E S1501_C01_011E S1501_C01_012E S1501_C01_013E  \
0       8.638444        9.51417       3.199261      41.471572      30.029924
1      17.723585      10.347033       3.970177      26.542462      12.412064
2        4.80243       6.170644       2.531195      44.729641      37.469899
3        1.66113       6.378738       0.166113      42.624585      48.272425
4       5.870307       6.484642       0.832765      50.552901      33.706485

    zcta   merge_key
0  10001  2023_10001
1  10002  2023_10002
2  10003  2023_10003
3  10004  2023_10004
4  10005  2023_10005

In [ ]:
merged_all = merged_df_income.merge(merged_df_rent, on='merge_key', suffixes=('_income', '_rent')) \
                             .merge(merged_df_education_pct, on='merge_key')

In [ ]:
merged_all

,ucgid_income,year_income,S1901_C01_001E,S1901_C01_012E,S1901_C01_013E,zcta_income,merge_key,ucgid_rent,year_rent,DP04_0126E,DP04_0134E,DP04_0080E,DP04_0089E,zcta_rent,ucgid,year,S1501_C01_006E,S1501_C01_007E,S1501_C01_008E,S1501_C01_009E,S1501_C01_010E,S1501_C01_011E,S1501_C01_012E,S1501_C01_013E,zcta
0,860Z200US10001,2023,15097,123393,205444,10001,2023_10001,860Z200US10001,2023,11399,3024,3570,793000,10001,860Z200US10001,2023,22724,2.112304,5.034325,8.638444,9.51417,3.199261,41.471572,30.029924,10001
1,860Z200US10002,2023,35771,46525,93314,10002,2023_10002,860Z200US10002,2023,28916,1207,6660,808500,10002,860Z200US10002,2023,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064,10002
2,860Z200US10003,2023,25080,153750,248577,10003,2023_10003,860Z200US10003,2023,16196,2772,8701,1137000,10003,860Z200US10003,2023,36544,2.982706,1.313485,4.80243,6.170644,2.531195,44.729641,37.469899,10003
3,860Z200US10004,2023,1775,220592,309645,10004,2023_10004,860Z200US10004,2023,1145,3501,630,1866400,10004,860Z200US10004,2023,3010,0.531561,0.365449,1.66113,6.378738,0.166113,42.624585,48.272425,10004
4,860Z200US10005,2023,5156,211810,279387,10005,2023_10005,860Z200US10005,2023,4276,3501,880,1387200,10005,860Z200US10005,2023,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485,10005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,8600000US11691,2013,18942,39409,56640,11691,2013_11691,8600000US11691,2013,13955,1012,4825,448200,11691,8600000US11691,2013,35984,12.5,14.4,28.3,16.9,6.4,13.5,8.0,11691
2344,8600000US11692,2013,5974,43354,60455,11692,2013_11692,8600000US11692,2013,3918,875,2000,355800,11692,8600000US11692,2013,11102,10.7,13.6,28.7,19.9,7.8,13.0,6.2,11692
2345,8600000US11693,2013,4518,50570,60995,11693,2013_11693,8600000US11693,2013,2419,831,1992,323100,11693,8600000US11693,2013,7664,3.4,15.5,30.2,19.5,7.4,17.2,6.6,11693
2346,8600000US11694,2013,8190,76944,93633,11694,2013_11694,8600000US11694,2013,3494,1161,4570,623200,11694,8600000US11694,2013,15705,5.1,6.9,22.7,19.2,8.4,19.8,17.7,11694
2347,8600000US11697,2013,1701,87636,100542,11697,2013_11697,8600000US11697,2013,52,908,1649,525600,11697,8600000US11697,2013,3085,1.8,3.7,27.4,16.1,6.8,24.9,19.3,11697

In [ ]:
column_rename_map = {
    'S1901_C01_001E': 'number_of_households',
    'S1901_C01_012E': 'household_median_income_1yr',
    'S1901_C01_013E': 'household_mean_income_1yr',
    'DP04_0126E': 'number_of_rent_home',
    'DP04_0134E': 'median_rent',
    'DP04_0080E': 'number_of_owned_home',
    'DP04_0089E': 'median_home_value',
    'S1501_C01_006E': 'population_25_and_over',
    'S1501_C01_007E': 'less_than_9th_grade',
    'S1501_C01_008E': '9th_to_12th_grade',
    'S1501_C01_009E': 'high_school_graduate',
    'S1501_C01_010E': 'some_college_no_degree',
    'S1501_C01_011E': 'associates_degree',
    'S1501_C01_012E': 'bachelors_degree',
    'S1501_C01_013E': 'graduate_or_professional_degree'
}

# Rename columns
merged_all = merged_all.rename(columns=column_rename_map)

In [ ]:
merged_all

,ucgid_income,year_income,number_of_households,household_median_income_1yr,household_mean_income_1yr,zcta_income,merge_key,ucgid_rent,year_rent,number_of_rent_home,median_rent,number_of_owned_home,median_home_value,zcta_rent,ucgid,year,population_25_and_over,less_than_9th_grade,9th_to_12th_grade,high_school_graduate,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree,zcta
0,860Z200US10001,2023,15097,123393,205444,10001,2023_10001,860Z200US10001,2023,11399,3024,3570,793000,10001,860Z200US10001,2023,22724,2.112304,5.034325,8.638444,9.51417,3.199261,41.471572,30.029924,10001
1,860Z200US10002,2023,35771,46525,93314,10002,2023_10002,860Z200US10002,2023,28916,1207,6660,808500,10002,860Z200US10002,2023,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064,10002
2,860Z200US10003,2023,25080,153750,248577,10003,2023_10003,860Z200US10003,2023,16196,2772,8701,1137000,10003,860Z200US10003,2023,36544,2.982706,1.313485,4.80243,6.170644,2.531195,44.729641,37.469899,10003
3,860Z200US10004,2023,1775,220592,309645,10004,2023_10004,860Z200US10004,2023,1145,3501,630,1866400,10004,860Z200US10004,2023,3010,0.531561,0.365449,1.66113,6.378738,0.166113,42.624585,48.272425,10004
4,860Z200US10005,2023,5156,211810,279387,10005,2023_10005,860Z200US10005,2023,4276,3501,880,1387200,10005,860Z200US10005,2023,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485,10005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,8600000US11691,2013,18942,39409,56640,11691,2013_11691,8600000US11691,2013,13955,1012,4825,448200,11691,8600000US11691,2013,35984,12.5,14.4,28.3,16.9,6.4,13.5,8.0,11691
2344,8600000US11692,2013,5974,43354,60455,11692,2013_11692,8600000US11692,2013,3918,875,2000,355800,11692,8600000US11692,2013,11102,10.7,13.6,28.7,19.9,7.8,13.0,6.2,11692
2345,8600000US11693,2013,4518,50570,60995,11693,2013_11693,8600000US11693,2013,2419,831,1992,323100,11693,8600000US11693,2013,7664,3.4,15.5,30.2,19.5,7.4,17.2,6.6,11693
2346,8600000US11694,2013,8190,76944,93633,11694,2013_11694,8600000US11694,2013,3494,1161,4570,623200,11694,8600000US11694,2013,15705,5.1,6.9,22.7,19.2,8.4,19.8,17.7,11694
2347,8600000US11697,2013,1701,87636,100542,11697,2013_11697,8600000US11697,2013,52,908,1649,525600,11697,8600000US11697,2013,3085,1.8,3.7,27.4,16.1,6.8,24.9,19.3,11697

In [ ]:
'zcta'
'year'
'number_of_households',
'household_median_income_1yr',
'household_mean_income_1yr',
'number_of_rent_home',
'median_rent',
'number_of_owned_home',
'median_home_value',
'population_25_and_over',
'less_than_9th_grade',
'9th_to_12th_grade',
'high_school_graduate',
'some_college_no_degree',
'associates_degree',
'bachelors_degree',
'graduate_or_professional_degree'

In [ ]:
selected_columns = [
    'zcta',
    'year',
    'number_of_households',
    'household_median_income_1yr',
    'household_mean_income_1yr',
    'number_of_rent_home',
    'median_rent',
    'number_of_owned_home',
    'median_home_value',
    'population_25_and_over',
    'less_than_9th_grade',
    '9th_to_12th_grade',
    'high_school_graduate',
    'some_college_no_degree',
    'associates_degree',
    'bachelors_degree',
    'graduate_or_professional_degree'
]

clean_df = merged_all[selected_columns]

In [ ]:
clean_df

,zcta,year,number_of_households,household_median_income_1yr,household_mean_income_1yr,number_of_rent_home,median_rent,number_of_owned_home,median_home_value,population_25_and_over,less_than_9th_grade,9th_to_12th_grade,high_school_graduate,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree
0,10001,2023,15097,123393,205444,11399,3024,3570,793000,22724,2.112304,5.034325,8.638444,9.51417,3.199261,41.471572,30.029924
1,10002,2023,35771,46525,93314,28916,1207,6660,808500,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064
2,10003,2023,25080,153750,248577,16196,2772,8701,1137000,36544,2.982706,1.313485,4.80243,6.170644,2.531195,44.729641,37.469899
3,10004,2023,1775,220592,309645,1145,3501,630,1866400,3010,0.531561,0.365449,1.66113,6.378738,0.166113,42.624585,48.272425
4,10005,2023,5156,211810,279387,4276,3501,880,1387200,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,11691,2013,18942,39409,56640,13955,1012,4825,448200,35984,12.5,14.4,28.3,16.9,6.4,13.5,8.0
2344,11692,2013,5974,43354,60455,3918,875,2000,355800,11102,10.7,13.6,28.7,19.9,7.8,13.0,6.2
2345,11693,2013,4518,50570,60995,2419,831,1992,323100,7664,3.4,15.5,30.2,19.5,7.4,17.2,6.6
2346,11694,2013,8190,76944,93633,3494,1161,4570,623200,15705,5.1,6.9,22.7,19.2,8.4,19.8,17.7
2347,11697,2013,1701,87636,100542,52,908,1649,525600,3085,1.8,3.7,27.4,16.1,6.8,24.9,19.3

In [ ]:
clean_df.to_csv('ACS_clean_income_rent_eductiona.csv', index=False)

# household Size

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S2501)&ucgid=860Z200US10001"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_test = json_to_dataframe(response)
df_test.head()

,GEO_ID,NAME,S2501_C01_001E,S2501_C01_001EA,S2501_C01_001M,S2501_C01_001MA,S2501_C01_002E,S2501_C01_002EA,S2501_C01_002M,S2501_C01_002MA,S2501_C01_003E,S2501_C01_003EA,S2501_C01_003M,S2501_C01_003MA,S2501_C01_004E,S2501_C01_004EA,S2501_C01_004M,S2501_C01_004MA,S2501_C01_005E,S2501_C01_005EA,S2501_C01_005M,S2501_C01_005MA,S2501_C01_006E,S2501_C01_006EA,S2501_C01_006M,S2501_C01_006MA,S2501_C01_007E,S2501_C01_007EA,S2501_C01_007M,S2501_C01_007MA,S2501_C01_008E,S2501_C01_008EA,S2501_C01_008M,S2501_C01_008MA,S2501_C01_009E,S2501_C01_009EA,S2501_C01_009M,S2501_C01_009MA,S2501_C01_010E,S2501_C01_010EA,S2501_C01_010M,S2501_C01_010MA,S2501_C01_011E,S2501_C01_011EA,S2501_C01_011M,S2501_C01_011MA,S2501_C01_012E,S2501_C01_012EA,S2501_C01_012M,S2501_C01_012MA,S2501_C01_013E,S2501_C01_013EA,S2501_C01_013M,S2501_C01_013MA,S2501_C01_014E,S2501_C01_014EA,S2501_C01_014M,S2501_C01_014MA,S2501_C01_015E,S2501_C01_015EA,S2501_C01_015M,S2501_C01_015MA,S2501_C01_016E,S2501_C01_016EA,S2501_C01_016M,S2501_C01_016MA,S2501_C01_017E,S2501_C01_017EA,S2501_C01_017M,S2501_C01_017MA,S2501_C01_018E,S2501_C01_018EA,S2501_C01_018M,S2501_C01_018MA,S2501_C01_019E,S2501_C01_019EA,S2501_C01_019M,S2501_C01_019MA,S2501_C01_020E,S2501_C01_020EA,S2501_C01_020M,S2501_C01_020MA,S2501_C01_021E,S2501_C01_021EA,S2501_C01_021M,S2501_C01_021MA,S2501_C01_022E,S2501_C01_022EA,S2501_C01_022M,S2501_C01_022MA,S2501_C01_023E,S2501_C01_023EA,S2501_C01_023M,S2501_C01_023MA,S2501_C01_024E,S2501_C01_024EA,S2501_C01_024M,S2501_C01_024MA,S2501_C01_025E,S2501_C01_025EA,S2501_C01_025M,S2501_C01_025MA,S2501_C01_026E,S2501_C01_026EA,S2501_C01_026M,S2501_C01_026MA,S2501_C01_027E,S2501_C01_027EA,S2501_C01_027M,S2501_C01_027MA,S2501_C01_028E,S2501_C01_028EA,S2501_C01_028M,S2501_C01_028MA,S2501_C01_029E,S2501_C01_029EA,S2501_C01_029M,S2501_C01_029MA,S2501_C01_030E,S2501_C01_030EA,S2501_C01_030M,S2501_C01_030MA,S2501_C01_031E,S2501_C01_031EA,S2501_C01_031M,S2501_C01_031MA,S2501_C01_032E,S2501_C01_032EA,S2501_C01_032M,S2501_C01_032MA,S2501_C01_033E,S2501_C01_033EA,S2501_C01_033M,S2501_C01_033MA,S2501_C01_034E,S2501_C01_034EA,S2501_C01_034M,S2501_C01_034MA,S2501_C01_035E,S2501_C01_035EA,S2501_C01_035M,S2501_C01_035MA,S2501_C01_036E,S2501_C01_036EA,S2501_C01_036M,S2501_C01_036MA,S2501_C01_037E,S2501_C01_037EA,S2501_C01_037M,S2501_C01_037MA,S2501_C01_038E,S2501_C01_038EA,S2501_C01_038M,S2501_C01_038MA,S2501_C02_001E,S2501_C02_001EA,S2501_C02_001M,S2501_C02_001MA,S2501_C02_002E,S2501_C02_002EA,S2501_C02_002M,S2501_C02_002MA,S2501_C02_003E,S2501_C02_003EA,S2501_C02_003M,S2501_C02_003MA,S2501_C02_004E,S2501_C02_004EA,S2501_C02_004M,S2501_C02_004MA,S2501_C02_005E,S2501_C02_005EA,S2501_C02_005M,S2501_C02_005MA,S2501_C02_006E,S2501_C02_006EA,S2501_C02_006M,S2501_C02_006MA,S2501_C02_007E,S2501_C02_007EA,S2501_C02_007M,S2501_C02_007MA,S2501_C02_008E,S2501_C02_008EA,S2501_C02_008M,S2501_C02_008MA,S2501_C02_009E,S2501_C02_009EA,S2501_C02_009M,S2501_C02_009MA,S2501_C02_010E,S2501_C02_010EA,S2501_C02_010M,S2501_C02_010MA,S2501_C02_011E,S2501_C02_011EA,S2501_C02_011M,S2501_C02_011MA,S2501_C02_012E,S2501_C02_012EA,S2501_C02_012M,S2501_C02_012MA,S2501_C02_013E,S2501_C02_013EA,S2501_C02_013M,S2501_C02_013MA,S2501_C02_014E,S2501_C02_014EA,S2501_C02_014M,S2501_C02_014MA,S2501_C02_015E,S2501_C02_015EA,S2501_C02_015M,S2501_C02_015MA,S2501_C02_016E,S2501_C02_016EA,S2501_C02_016M,S2501_C02_016MA,S2501_C02_017E,S2501_C02_017EA,S2501_C02_017M,S2501_C02_017MA,S2501_C02_018E,S2501_C02_018EA,S2501_C02_018M,S2501_C02_018MA,S2501_C02_019E,S2501_C02_019EA,S2501_C02_019M,S2501_C02_019MA,S2501_C02_020E,S2501_C02_020EA,S2501_C02_020M,S2501_C02_020MA,S2501_C02_021E,S2501_C02_021EA,S2501_C02_021M,S2501_C02_021MA,S2501_C02_022E,S2501_C02_022EA,S2501_C02_022M,S2501_C02_022MA,S2501_C02_023E,S2501_C02_023EA,S2501_C02_023M,S2501_C02_023MA,S2501_C02_024E,S2501_C02_024EA,S2501_C02_024M,S2501_C02_024MA,S2501_C02_025E,S2501_C02_025EA,S2501_C02_025M,S2501_C02_025MA,S2501_C02_026E,S2501_C02_026EA,S2501_C02_026M,S2501_C02_026MA,S2501_C02_027E,S2501_C02_027EA,S2501_C02_027M,S2501_C02_027MA,S2501_C02_028E,S2501_C02_028EA,S2501_C02_028M,S2501_C02_028MA,S2501_C02_029E,S2501_C02_029EA,S2501_C02_029M,S2501_C02_029MA,S2501_C02_030E,S2501_C02_030EA,S2501_C02_030M,S2501_C02_030MA,S2501_C02_031E,S2501_C02_031EA,S2501_C02_031M,S2501_C02_031MA,S2501_C02_032E,S2501_C02_032EA,S2501_C02_032M,S2501_C02_032MA,S2501_C02_033E,S2501_C02_033EA,S2501_C02_033M,S2501_C02_033MA,S2501_C02_034E,S2501_C02_034EA,S2501_C02_034M,S2501_C02_034MA,S2501_C02_035E,S2501_C02_035EA,S2501_C02_035M,S2501_C02_035MA,S2501_C02_036E,S2501_C02_036EA,S2501_C02_036M,S2501_C02_036MA,S2501_C02_037E,S2501_C02_037EA,S2501_C02_037M,S2501_C02_037MA,S2501_C02_038E,S2501_C02_038EA,S2501_C02_038M,S2501_C02_038MA,S2501_C03_001E,S2501_C03_001EA,S2501_C03_001M,S2501_C03_001MA,S2501_C03_002E,S2501_C03_002EA,S2501_C03_002M,S2501_C03_002MA,S2501_C03_003E,S2501_C03_003EA,S2501_C03_003M,S2501_C03_003MA,S2501_C03_004E,S2501_C03_004EA,S2501_C03_004M,S2501_C03_004MA,S2501_C03_005E,S2501_C03_005EA,S2501_C03_005M,S2501_C03_005MA,S2501_C03_006E,S2501_C03_006EA,S2501_C03_006M,S2501_C03_006MA,S2501_C03_007E,S2501_C03_007EA,S2501_C03_007M,S2501_C03_007MA,S2501_C03_008E,S2501_C03_008EA,S2501_C03_008M,S2501_C03_008MA,S2501_C03_009E,S2501_C03_009EA,S2501_C03_009M,S2501_C03_009MA,S2501_C03_010E,S2501_C03_010EA,S2501_C03_010M,S2501_C03_010MA,S2501_C03_011E,S2501_C03_011EA,S2501_C03_011M,S2501_C03_011MA,S2501_C03_012E,S2501_C03_012EA,S2501_C03_012M,S2501_C03_012MA,S2501_C03_013E,S2501_C03_013EA,S2501_C03_013M,S2501_C03_013MA,S2501_C03_014E,S2501_C03_014EA,S2501_C03_014M,S2501_C03_014MA,S2501_C03_015E,S2501_C03_015EA,S2501_C03_015M,S2501_C03_015MA,S2501_C03_016E,S2501_C03_016EA,S2501_C03_016M,S2501_C03_016MA,S2501_C03_017E,S2501_C03_017EA,S2501_C03_017M,S2501_C03_017MA,S2501_C03_018E,S2501_C03_018EA,S2501_C03_018M,S2501_C03_018MA,S2501_C03_019E,S2501_C03_019EA,S2501_C03_019M,S2501_C03_019MA,S2501_C03_020E,S2501_C03_020EA,S2501_C03_020M,S2501_C03_020MA,S2501_C03_021E,S2501_C03_021EA,S2501_C03_021M,S2501_C03_021MA,S2501_C03_022E,S2501_C03_022EA,S2501_C03_022M,S2501_C03_022MA,S2501_C03_023E,S2501_C03_023EA,S2501_C03_023M,S2501_C03_023MA,S2501_C03_024E,S2501_C03_024EA,S2501_C03_024M,S2501_C03_024MA,S2501_C03_025E,S2501_C03_025EA,S2501_C03_025M,S2501_C03_025MA,S2501_C03_026E,S2501_C03_026EA,S2501_C03_026M,S2501_C03_026MA,S2501_C03_027E,S2501_C03_027EA,S2501_C03_027M,S2501_C03_027MA,S2501_C03_028E,S2501_C03_028EA,S2501_C03_028M,S2501_C03_028MA,S2501_C03_029E,S2501_C03_029EA,S2501_C03_029M,S2501_C03_029MA,S2501_C03_030E,S2501_C03_030EA,S2501_C03_030M,S2501_C03_030MA,S2501_C03_031E,S2501_C03_031EA,S2501_C03_031M,S2501_C03_031MA,S2501_C03_032E,S2501_C03_032EA,S2501_C03_032M,S2501_C03_032MA,S2501_C03_033E,S2501_C03_033EA,S2501_C03_033M,S2501_C03_033MA,S2501_C03_034E,S2501_C03_034EA,S2501_C03_034M,S2501_C03_034MA,S2501_C03_035E,S2501_C03_035EA,S2501_C03_035M,S2501_C03_035MA,S2501_C03_036E,S2501_C03_036EA,S2501_C03_036M,S2501_C03_036MA,S2501_C03_037E,S2501_C03_037EA,S2501_C03_037M,S2501_C03_037MA,S2501_C03_038E,S2501_C03_038EA,S2501_C03_038M,S2501_C03_038MA,S2501_C04_001E,S2501_C04_001EA,S2501_C04_001M,S2501_C04_001MA,S2501_C04_002E,S2501_C04_002EA,S2501_C04_002M,S2501_C04_002MA,S2501_C04_003E,S2501_C04_003EA,S2501_C04_003M,S2501_C04_003MA,S2501_C04_004E,S2501_C04_004EA,S2501_C04_004M,S2501_C04_004MA,S2501_C04_005E,S2501_C04_005EA,S2501_C04_005M,S2501_C04_005MA,S2501_C04_006E,S2501_C04_006EA,S2501_C04_006M,S2501_C04_006MA,S2501_C04_007E,S2501_C04_007EA,S2501_C04_007M,S2501_C04_007MA,S2501_C04_008E,S2501_C04_008EA,S2501_C04_008M,S2501_C04_008MA,S2501_C04_009E,S2501_C04_009EA,S2501_C04_009M,S2501_C04_009MA,S2501_C04_010E,S2501_C04_010EA,S2501_C04_010M,S2501_C04_010MA,S2501_C04_011E,S2501_C04_011EA,S2501_C04_011M,S2501_C04_011MA,S2501_C04_012E,S2501_C04_012EA,S2501_C04_012M,S2501_C04_012MA,S2501_C04_013E,S2501_C04_013EA,S2501_C04_013M,S2501_C04_013MA,S2501_C04_014E,S2501_C04_014EA,S2501_C04_014M,S2501_C04_014MA,S2501_C04_015E,S2501_C04_015EA,S2501_C04_015M,S2501_C04_015MA,S2501_C04_016E,S2501_C04_016EA,S2501_C04_016M,S2501_C04_016MA,S2501_C04_017E,S2501_C04_017EA,S2501_C04_017M,S2501_C04_017MA,S2501_C04_018E,S2501_C04_018EA,S2501_C04_018M,S2501_C04_018MA,S2501_C04_019E,S2501_C04_019EA,S2501_C04_019M,S2501_C04_019MA,S2501_C04_020E,S2501_C04_020EA,S2501_C04_020M,S2501_C04_020MA,S2501_C04_021E,S2501_C04_021EA,S2501_C04_021M,S2501_C04_021MA,S2501_C04_022E,S2501_C04_022EA,S2501_C04_022M,S2501_C04_022MA,S2501_C04_023E,S2501_C04_023EA,S2501_C04_023M,S2501_C04_023MA,S2501_C04_024E,S2501_C04_024EA,S2501_C04_024M,S2501_C04_024MA,S2501_C04_025E,S2501_C04_025EA,S2501_C04_025M,S2501_C04_025MA,S2501_C04_026E,S2501_C04_026EA,S2501_C04_026M,S2501_C04_026MA,S2501_C04_027E,S2501_C04_027EA,S2501_C04_027M,S2501_C04_027MA,S2501_C04_028E,S2501_C04_028EA,S2501_C04_028M,S2501_C04_028MA,S2501_C04_029E,S2501_C04_029EA,S2501_C04_029M,S2501_C04_029MA,S2501_C04_030E,S2501_C04_030EA,S2501_C04_030M,S2501_C04_030MA,S2501_C04_031E,S2501_C04_031EA,S2501_C04_031M,S2501_C04_031MA,S2501_C04_032E,S2501_C04_032EA,S2501_C04_032M,S2501_C04_032MA,S2501_C04_033E,S2501_C04_033EA,S2501_C04_033M,S2501_C04_033MA,S2501_C04_034E,S2501_C04_034EA,S2501_C04_034M,S2501_C04_034MA,S2501_C04_035E,S2501_C04_035EA,S2501_C04_035M,S2501_C04_035MA,S2501_C04_036E,S2501_C04_036EA,S2501_C04_036M,S2501_C04_036MA,S2501_C04_037E,S2501_C04_037EA,S2501_C04_037M,S2501_C04_037MA,S2501_C04_038E,S2501_C04_038EA,S2501_C04_038M,S2501_C04_038MA,S2501_C05_001E,S2501_C05_001EA,S2501_C05_001M,S2501_C05_001MA,S2501_C05_002E,S2501_C05_002EA,S2501_C05_002M,S2501_C05_002MA,S2501_C05_003E,S2501_C05_003EA,S2501_C05_003M,S2501_C05_003MA,S2501_C05_004E,S2501_C05_004EA,S2501_C05_004M,S2501_C05_004MA,S2501_C05_005E,S2501_C05_005EA,S2501_C05_005M,S2501_C05_005MA,S2501_C05_006E,S2501_C05_006EA,S2501_C05_006M,S2501_C05_006MA,S2501_C05_007E,S2501_C05_007EA,S2501_C05_007M,S2501_C05_007MA,S2501_C05_008E,S2501_C05_008EA,S2501_C05_008M,S2501_C05_008MA,S2501_C05_009E,S2501_C05_009EA,S2501_C05_009M,S2501_C05_009MA,S2501_C05_010E,S2501_C05_010EA,S2501_C05_010M,S2501_C05_010MA,S2501_C05_011E,S2501_C05_011EA,S2501_C05_011M,S2501_C05_011MA,S2501_C05_012E,S2501_C05_012EA,S2501_C05_012M,S2501_C05_012MA,S2501_C05_013E,S2501_C05_013EA,S2501_C05_013M,S2501_C05_013MA,S2501_C05_014E,S2501_C05_014EA,S2501_C05_014M,S2501_C05_014MA,S2501_C05_015E,S2501_C05_015EA,S2501_C05_015M,S2501_C05_015MA,S2501_C05_016E,S2501_C05_016EA,S2501_C05_016M,S2501_C05_016MA,S2501_C05_017E,S2501_C05_017EA,S2501_C05_017M,S2501_C05_017MA,S2501_C05_018E,S2501_C05_018EA,S2501_C05_018M,S2501_C05_018MA,S2501_C05_019E,S2501_C05_019EA,S2501_C05_019M,S2501_C05_019MA,S2501_C05_020E,S2501_C05_020EA,S2501_C05_020M,S2501_C05_020MA,S2501_C05_021E,S2501_C05_021EA,S2501_C05_021M,S2501_C05_021MA,S2501_C05_022E,S2501_C05_022EA,S2501_C05_022M,S2501_C05_022MA,S2501_C05_023E,S2501_C05_023EA,S2501_C05_023M,S2501_C05_023MA,S2501_C05_024E,S2501_C05_024EA,S2501_C05_024M,S2501_C05_024MA,S2501_C05_025E,S2501_C05_025EA,S2501_C05_025M,S2501_C05_025MA,S2501_C05_026E,S2501_C05_026EA,S2501_C05_026M,S2501_C05_026MA,S2501_C05_027E,S2501_C05_027EA,S2501_C05_027M,S2501_C05_027MA,S2501_C05_028E,S2501_C05_028EA,S2501_C05_028M,S2501_C05_028MA,S2501_C05_029E,S2501_C05_029EA,S2501_C05_029M,S2501_C05_029MA,S2501_C05_030E,S2501_C05_030EA,S2501_C05_030M,S2501_C05_030MA,S2501_C05_031E,S2501_C05_031EA,S2501_C05_031M,S2501_C05_031MA,S2501_C05_032E,S2501_C05_032EA,S2501_C05_032M,S2501_C05_032MA,S2501_C05_033E,S2501_C05_033EA,S2501_C05_033M,S2501_C05_033MA,S2501_C05_034E,S2501_C05_034EA,S2501_C05_034M,S2501_C05_034MA,S2501_C05_035E,S2501_C05_035EA,S2501_C05_035M,S2501_C05_035MA,S2501_C05_036E,S2501_C05_036EA,S2501_C05_036M,S2501_C05_036MA,S2501_C05_037E,S2501_C05_037EA,S2501_C05_037M,S2501_C05_037MA,S2501_C05_038E,S2501_C05_038EA,S2501_C05_038M,S2501_C05_038MA,S2501_C06_001E,S2501_C06_001EA,S2501_C06_001M,S2501_C06_001MA,S2501_C06_002E,S2501_C06_002EA,S2501_C06_002M,S2501_C06_002MA,S2501_C06_003E,S2501_C06_003EA,S2501_C06_003M,S2501_C06_003MA,S2501_C06_004E,S2501_C06_004EA,S2501_C06_004M,S2501_C06_004MA,S2501_C06_005E,S2501_C06_005EA,S2501_C06_005M,S2501_C06_005MA,S2501_C06_006E,S2501_C06_006EA,S2501_C06_006M,S2501_C06_006MA,S2501_C06_007E,S2501_C06_007EA,S2501_C06_007M,S2501_C06_007MA,S2501_C06_008E,S2501_C06_008EA,S2501_C06_008M,S2501_C06_008MA,S2501_C06_009E,S2501_C06_009EA,S2501_C06_009M,S2501_C06_009MA,S2501_C06_010E,S2501_C06_010EA,S2501_C06_010M,S2501_C06_010MA,S2501_C06_011E,S2501_C06_011EA,S2501_C06_011M,S2501_C06_011MA,S2501_C06_012E,S2501_C06_012EA,S2501_C06_012M,S2501_C06_012MA,S2501_C06_013E,S2501_C06_013EA,S2501_C06_013M,S2501_C06_013MA,S2501_C06_014E,S2501_C06_014EA,S2501_C06_014M,S2501_C06_014MA,S2501_C06_015E,S2501_C06_015EA,S2501_C06_015M,S2501_C06_015MA,S2501_C06_016E,S2501_C06_016EA,S2501_C06_016M,S2501_C06_016MA,S2501_C06_017E,S2501_C06_017EA,S2501_C06_017M,S2501_C06_017MA,S2501_C06_018E,S2501_C06_018EA,S2501_C06_018M,S2501_C06_018MA,S2501_C06_019E,S2501_C06_019EA,S2501_C06_019M,S2501_C06_019MA,S2501_C06_020E,S2501_C06_020EA,S2501_C06_020M,S2501_C06_020MA,S2501_C06_021E,S2501_C06_021EA,S2501_C06_021M,S2501_C06_021MA,S2501_C06_022E,S2501_C06_022EA,S2501_C06_022M,S2501_C06_022MA,S2501_C06_023E,S2501_C06_023EA,S2501_C06_023M,S2501_C06_023MA,S2501_C06_024E,S2501_C06_024EA,S2501_C06_024M,S2501_C06_024MA,S2501_C06_025E,S2501_C06_025EA,S2501_C06_025M,S2501_C06_025MA,S2501_C06_026E,S2501_C06_026EA,S2501_C06_026M,S2501_C06_026MA,S2501_C06_027E,S2501_C06_027EA,S2501_C06_027M,S2501_C06_027MA,S2501_C06_028E,S2501_C06_028EA,S2501_C06_028M,S2501_C06_028MA,S2501_C06_029E,S2501_C06_029EA,S2501_C06_029M,S2501_C06_029MA,S2501_C06_030E,S2501_C06_030EA,S2501_C06_030M,S2501_C06_030MA,S2501_C06_031E,S2501_C06_031EA,S2501_C06_031M,S2501_C06_031MA,S2501_C06_032E,S2501_C06_032EA,S2501_C06_032M,S2501_C06_032MA,S2501_C06_033E,S2501_C06_033EA,S2501_C06_033M,S2501_C06_033MA,S2501_C06_034E,S2501_C06_034EA,S2501_C06_034M,S2501_C06_034MA,S2501_C06_035E,S2501_C06_035EA,S2501_C06_035M,S2501_C06_035MA,S2501_C06_036E,S2501_C06_036EA,S2501_C06_036M,S2501_C06_036MA,S2501_C06_037E,S2501_C06_037EA,S2501_C06_037M,S2501_C06_037MA,S2501_C06_038E,S2501_C06_038EA,S2501_C06_038M,S2501_C06_038MA,ucgid
0,860Z200US10001,ZCTA5 10001,15097,None,796,None,8305,None,857,None,4423,None,610,None,1437,None,386,None,932,None,322,None,14495,None,786,None,225,None,102,None,377,None,188,None,4715,None,650,None,3291,None,544,None,709,None,250,None,1960,None,472,None,622,None,166,None,1424,None,379,None,365,None,244,None,155,None,189,None,162,None,119,None,48,None,76,None,1059,None,305,None,86,None,74,None,737,None,275,None,236,None,136,None,10382,None,864,None,8305,None,857,None,3175,None,546,None,3561,None,590,None,1569,None,366,None,2077,None,359,None,1428,None,308,None,585,None,224,None,64,None,50,None,1986,None,434,None,1742,None,423,None,742,None,294,None,254,None,204,None,746,None,232,None,244,None,102,None,13111,None,813,None,15097,None,796,None,55.0,None,4.5,None,29.3,None,3.9,None,9.5,None,2.5,None,6.2,None,2.2,None,96.0,None,1.4,None,1.5,None,0.7,None,2.5,None,1.2,None,31.2,None,4.1,None,21.8,None,3.6,None,4.7,None,1.6,None,13.0,None,3.1,None,4.1,None,1.1,None,9.4,None,2.4,None,2.4,None,1.6,None,1.0,None,1.2,None,1.1,None,0.8,None,0.3,None,0.5,None,7.0,None,1.9,None,0.6,None,0.5,None,4.9,None,1.8,None,1.6,None,0.9,None,68.8,None,4.1,None,55.0,None,4.5,None,21.0,None,3.1,None,23.6,None,3.9,None,10.4,None,2.3,None,13.8,None,2.4,None,9.5,None,2.1,None,3.9,None,1.4,None,0.4,None,0.3,None,13.2,None,2.8,None,11.5,None,2.7,None,4.9,None,1.9,None,1.7,None,1.4,None,4.9,None,1.6,None,1.6,None,0.7,None,86.8,None,2.8,None,3570,None,565,None,1709,None,436,None,933,None,295,None,653,None,281,None,275,None,189,None,3404,None,546,None,55,None,55,None,111,None,122,None,1623,None,436,None,1116,None,350,None,45,None,67,None,851,None,297,None,220,None,111,None,507,None,254,None,29,None,50,None,0,None,25,None,29,None,50,None,0,None,25,None,478,None,250,None,7,None,12,None,276,None,215,None,195,None,131,None,1947,None,483,None,1709,None,436,None,234,None,225,None,773,None,296,None,702,None,202,None,238,None,160,None,58,None,78,None,163,None,134,None,17,None,28,None,844,None,312,None,778,None,309,None,309,None,217,None,75,None,94,None,394,None,193,None,66,None,55,None,2726,None,496,None,3570,None,565,None,47.9,None,9.8,None,26.1,None,6.4,None,18.3,None,7.5,None,7.7,None,5.3,None,95.4,None,3.5,None,1.5,None,1.6,None,3.1,None,3.3,None,45.5,None,10.3,None,31.3,None,9.3,None,1.3,None,1.9,None,23.8,None,8.2,None,6.2,None,3.0,None,14.2,None,6.5,None,0.8,None,1.4,None,0.0,None,1.1,None,0.8,None,1.4,None,0.0,None,1.1,None,13.4,None,6.4,None,0.2,None,0.3,None,7.7,None,5.6,None,5.5,None,3.7,None,54.5,None,10.3,None,47.9,None,9.8,None,6.6,None,5.9,None,21.7,None,7.5,None,19.7,None,6.2,None,6.7,None,4.3,None,1.6,None,2.2,None,4.6,None,3.7,None,0.5,None,0.8,None,23.6,None,7.8,None,21.8,None,7.7,None,8.7,None,5.8,None,2.1,None,2.6,None,11.0,None,5.2,None,1.8,None,1.6,None,76.4,None,7.8,None,11527,None,741,None,6596,None,705,None,3490,None,522,None,784,None,274,None,657,None,306,None,11091,None,721,None,170,None,111,None,266,None,122,None,3092,None,534,None,2175,None,432,None,664,None,244,None,1109,None,343,None,402,None,158,None,917,None,297,None,336,None,248,None,155,None,189,None,133,None,116,None,48,None,76,None,581,None,183,None,79,None,74,None,461,None,175,None,41,None,37,None,8435,None,724,None,6596,None,705,None,2941,None,486,None,2788,None,537,None,867,None,263,None,1839,None,321,None,1370,None,293,None,422,None,199,None,47,None,42,None,1142,None,382,None,964,None,343,None,433,None,233,None,179,None,183,None,352,None,161,None,178,None,94,None,10385,None,705,None,11527,None,741,None,57.2,None,4.6,None,30.3,None,4.3,None,6.8,None,2.3,None,5.7,None,2.7,None,96.2,None,1.5,None,1.5,None,0.9,None,2.3,None,1.1,None,26.8,None,4.3,None,18.9,None,3.6,None,5.8,None,2.1,None,9.6,None,2.9,None,3.5,None,1.4,None,8.0,None,2.5,None,2.9,None,2.1,None,1.3,None,1.6,None,1.2,None,1.0,None,0.4,None,0.7,None,5.0,None,1.5,None,0.7,None,0.6,None,4.0,None,1.5,None,0.4,None,0.3,None,73.2,None,4.3,None,57.2,None,4.6,None,25.5,None,3.7,None,24.2,None,4.5,None,7.5,None,2.2,None,16.0,None,2.8,None,11.9,None,2.6,None,3.7,None,1.7,None,0.4,None,0.4,None,9.9,None,3.1,None,8.4,None,2.8,None,3.8,None,1.9,None,1.6,None,1.6,None,3.1,None,1.4,None,1.5,None,0.8,None,90.1,None,3.1,None,860Z200US10001

In [ ]:
'''
S2501_C01_001E = housing units
S2501_C01_002E = 1-person
S2501_C01_003E = 2-person
S2501_C01_004E = 3-person
S2501_C01_005E = 4-person or more
'''

In [ ]:
def process_house_response(response, year):
    df = pd.DataFrame(response.json()[1:], columns=response.json()[0])
    df = df[['ucgid', 'S2501_C01_001E','S2501_C01_002E','S2501_C01_003E','S2501_C01_004E', 'S2501_C01_005E']]
    df['year'] = str(year)
    return df[['ucgid', 'year', 'S2501_C01_001E','S2501_C01_002E','S2501_C01_003E','S2501_C01_004E', 'S2501_C01_005E']]

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S2501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2023 = process_house_response(response, 2023)
print(df_house_2023.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  860Z200US10020  2023              0              0              0
1  860Z200US10103  2023              0              0              0
2  860Z200US10110  2023              0              0              0
3  860Z200US10111  2023              0              0              0
4  860Z200US10112  2023              0              0              0

  S2501_C01_004E S2501_C01_005E
0              0              0
1              0              0
2              0              0
3              0              0
4              0              0

In [ ]:
url = "https://api.census.gov/data/2022/acs/acs5/subject?get=group(S2501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2022 = process_house_response(response, 2022)
print(df_house_2022.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  860Z200US10001  2022          14375           8274           4003
1  860Z200US10002  2022          36028          16146          11737
2  860Z200US10003  2022          24987          13298           8143
3  860Z200US10004  2022           2123            795            673
4  860Z200US10005  2022           4881           2553           1523

  S2501_C01_004E S2501_C01_005E
0           1277            821
1           4543           3602
2           2237           1309
3            397            258
4            469            336

In [ ]:
url = "https://api.census.gov/data/2021/acs/acs5/subject?get=group(S2501)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2021 = process_house_response(response, 2021)
print(df_house_2021.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  860Z200US10020  2021              0              0              0
1  860Z200US10103  2021              0              0              0
2  860Z200US10110  2021              0              0              0
3  860Z200US10111  2021              0              0              0
4  860Z200US10112  2021              0              0              0

  S2501_C01_004E S2501_C01_005E
0              0              0
1              0              0
2              0              0
3              0              0
4              0              0

In [ ]:
url = "https://api.census.gov/data/2020/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2020 = process_house_response(response, 2020)
print(df_house_2020.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10001  2020          13311           7077           3913
1  8600000US10002  2020          33790          14399          10578
2  8600000US10003  2020          25158          13204           8396
3  8600000US10004  2020           1822            762            760
4  8600000US10005  2020           4649           2297           1567

  S2501_C01_004E S2501_C01_005E
0           1325            996
1           4802           4011
2           2156           1402
3            221             79
4            347            438

In [ ]:
url = "https://api.census.gov/data/2019/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2019 = process_house_response(response, 2019)
print(df_house_2019.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10001  2019          12997           7026           3975
1  8600000US10002  2019          33459          14174          10367
2  8600000US10003  2019          26043          14621           8270
3  8600000US10004  2019           1777            811            569
4  8600000US10005  2019           4363           1811           1753

  S2501_C01_004E S2501_C01_005E
0           1248            748
1           4771           4147
2           1887           1265
3            294            103
4            379            420

In [ ]:
url = "https://api.census.gov/data/2018/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2018 = process_house_response(response, 2018)
print(df_house_2018.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10001  2018          12431           6710           3897
1  8600000US10002  2018          33540          14319          10041
2  8600000US10003  2018          26124          14377           8265
3  8600000US10004  2018           1659            794            524
4  8600000US10005  2018           4374           1674           1816

  S2501_C01_004E S2501_C01_005E
0           1072            752
1           4908           4272
2           1999           1483
3            238            103
4            557            327

In [ ]:
url = "https://api.census.gov/data/2017/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2017 = process_house_response(response, 2017)
print(df_house_2017.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10020  2017              0              0              0
1  8600000US10103  2017              0              0              0
2  8600000US10110  2017              0              0              0
3  8600000US10111  2017              0              0              0
4  8600000US10112  2017              0              0              0

  S2501_C01_004E S2501_C01_005E
0              0              0
1              0              0
2              0              0
3              0              0
4              0              0

In [ ]:
'''
23-17val
16-13pct
'''

'\n23-17val\n16-13pct\n'

In [ ]:
url = "https://api.census.gov/data/2016/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2016 = process_house_response(response, 2016)
print(df_house_2016.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10020  2016              0   -666666666.0   -666666666.0
1  8600000US10103  2016              0   -666666666.0   -666666666.0
2  8600000US10110  2016              0   -666666666.0   -666666666.0
3  8600000US10111  2016              0   -666666666.0   -666666666.0
4  8600000US10112  2016              0   -666666666.0   -666666666.0

  S2501_C01_004E S2501_C01_005E
0   -666666666.0   -666666666.0
1   -666666666.0   -666666666.0
2   -666666666.0   -666666666.0
3   -666666666.0   -666666666.0
4   -666666666.0   -666666666.0

In [ ]:
url = "https://api.census.gov/data/2015/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2015 = process_house_response(response, 2015)
print(df_house_2015.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10020  2015              0   -666666666.0   -666666666.0
1  8600000US10103  2015              0   -666666666.0   -666666666.0
2  8600000US10110  2015              0   -666666666.0   -666666666.0
3  8600000US10111  2015              0   -666666666.0   -666666666.0
4  8600000US10112  2015              0   -666666666.0   -666666666.0

  S2501_C01_004E S2501_C01_005E
0   -666666666.0   -666666666.0
1   -666666666.0   -666666666.0
2   -666666666.0   -666666666.0
3   -666666666.0   -666666666.0
4   -666666666.0   -666666666.0

In [ ]:
url = "https://api.census.gov/data/2014/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2014 = process_house_response(response, 2014)
print(df_house_2014.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10001  2014          11169           54.0           28.6
1  8600000US10002  2014          32550           39.6           29.9
2  8600000US10003  2014          27564           56.1           30.9
3  8600000US10004  2014           1580           52.5           30.1
4  8600000US10005  2014           4100           51.0           33.3

  S2501_C01_004E S2501_C01_005E
0           10.4            7.0
1           14.9           15.7
2            8.2            4.8
3            6.9           10.5
4           11.2            4.5

In [ ]:
url = "https://api.census.gov/data/2013/acs/acs5/subject?get=group(S2501)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_house_2013 = process_house_response(response, 2013)
print(df_house_2013.head())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  8600000US10001  2013          11024           54.8           29.7
1  8600000US10002  2013          32467           38.7           30.3
2  8600000US10003  2013          27505           55.7           31.7
3  8600000US10004  2013           1430           53.3           25.5
4  8600000US10005  2013           3725           52.7           34.9

  S2501_C01_004E S2501_C01_005E
0            8.8            6.6
1           13.9           17.1
2            8.3            4.4
3           11.0           10.1
4            7.0            5.4

In [ ]:
  dfs = [df_house_2023, df_house_2022, df_house_2021, df_house_2020,
       df_house_2019, df_house_2018, df_house_2017]

# Concatenate the DataFrames vertically (row-wise)
merged_df_housesize = pd.concat(dfs, ignore_index=True)

print(merged_df_housesize.head())
print(merged_df_housesize.tail())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  860Z200US10020  2023              0              0              0
1  860Z200US10103  2023              0              0              0
2  860Z200US10110  2023              0              0              0
3  860Z200US10111  2023              0              0              0
4  860Z200US10112  2023              0              0              0

  S2501_C01_004E S2501_C01_005E
0              0              0
1              0              0
2              0              0
3              0              0
4              0              0
               ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
1487  8600000US11106  2017          17127           6138           6263
1488  8600000US11003  2017          12106           1608           2540
1489  8600000US11214  2017          31945           7549           8323
1490  8600000US11232  2017           8808           1656           2589
1491  8600000US11411  2017           6052           1166           1693

     S2501_C01_004E S2501_C01_005E
1487           2373           2353
1488           2206           5752
1489           6122           9951
1490           1673           2890
1491           1066           2127

In [ ]:
# First, convert all columns to numeric (just in case some are strings)
merged_df_housesize = merged_df_housesize.apply(pd.to_numeric, errors='ignore')

# Store total column separately
total_col = 'S2501_C01_001E'

# Columns to calculate percent for (exclude 'ucgid', 'year', and the total column itself)
percent_cols = [col for col in merged_df_housesize.columns
                if col not in ['ucgid', 'year', total_col]]

# Create percent columns
for col in percent_cols:
    pct_col = col + '_pct'
    merged_df_housesize[pct_col] = (merged_df_housesize[col] / merged_df_housesize[total_col]) * 100

In [ ]:
# Keep total column and all percentage columns
cols_to_keep = ['S2501_C01_001E'] + [col for col in merged_df_housesize.columns if col.endswith('_pct')]

# Also keep 'ucgid' and 'year' for context
cols_to_keep = ['ucgid', 'year'] + cols_to_keep

# Subset the DataFrame
merged_df_housesize = merged_df_housesize[cols_to_keep]

# Optional: reset index
merged_df_housesize = merged_df_housesize.reset_index(drop=True)

merged_df_housesize.columns = [
    col.replace('_pct', '') if col.endswith('_pct') else col
    for col in merged_df_housesize.columns
]

In [ ]:
dfs = [merged_df_housesize, df_house_2016, df_house_2015, df_house_2014, df_house_2013]

# Concatenate the DataFrames vertically (row-wise)
merged_df_housesize_pct = pd.concat(dfs, ignore_index=True)

print(merged_df_housesize_pct.head())
print(merged_df_housesize_pct.tail())

            ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
0  860Z200US10020  2023              0            NaN            NaN
1  860Z200US10103  2023              0            NaN            NaN
2  860Z200US10110  2023              0            NaN            NaN
3  860Z200US10111  2023              0            NaN            NaN
4  860Z200US10112  2023              0            NaN            NaN

  S2501_C01_004E S2501_C01_005E
0            NaN            NaN
1            NaN            NaN
2            NaN            NaN
3            NaN            NaN
4            NaN            NaN
               ucgid  year S2501_C01_001E S2501_C01_002E S2501_C01_003E  \
2343  8600000US11691  2013          18942           29.1           22.4
2344  8600000US11692  2013           5974           26.4           23.1
2345  8600000US11693  2013           4518           31.6           30.1
2346  8600000US11694  2013           8190           32.5           28.0
2347  8600000US11697  2013           1701           28.9           37.2

     S2501_C01_004E S2501_C01_005E
2343           15.2           33.2
2344           23.1           27.3
2345           18.3           19.9
2346           17.7           21.8
2347           11.9           22.0

In [ ]:
# prompt: from merged_df_housesize_pct I want to see 2023 860Z200US10002

# Assuming 'merged_df_housesize_pct' is already defined as in your provided code.

# Filter the DataFrame
result = merged_df_housesize_pct[(merged_df_housesize_pct['year'] == 2023) & (merged_df_housesize_pct['ucgid'] == '860Z200US10002')]

# Print or use the result
result

,ucgid,year,S2501_C01_001E,S2501_C01_002E,S2501_C01_003E,S2501_C01_004E,S2501_C01_005E
31,860Z200US10002,2023,35771,44.222974,33.211261,12.521316,10.044449

In [ ]:
for df in [merged_df_housesize_pct]:
    df['zcta'] = df['ucgid'].str[-5:]
    df['merge_key'] = df['year'].astype(str) + "_" + df['zcta']

In [ ]:
merged_df_housesize_pct = merged_df_housesize_pct.rename(columns={
    'S2501_C01_001E': 'housing_units',
    'S2501_C01_002E': 'pct_1_person',
    'S2501_C01_003E': 'pct_2_person',
    'S2501_C01_004E': 'pct_3_person',
    'S2501_C01_005E': 'pct_4_or_more_person'
})

In [ ]:
merged_df_housesize_pct

,ucgid,year,housing_units,pct_1_person,pct_2_person,pct_3_person,pct_4_or_more_person,zcta,merge_key
0,860Z200US10020,2023,0,NaN,NaN,NaN,NaN,10020,2023_10020
1,860Z200US10103,2023,0,NaN,NaN,NaN,NaN,10103,2023_10103
2,860Z200US10110,2023,0,NaN,NaN,NaN,NaN,10110,2023_10110
3,860Z200US10111,2023,0,NaN,NaN,NaN,NaN,10111,2023_10111
4,860Z200US10112,2023,0,NaN,NaN,NaN,NaN,10112,2023_10112
...,...,...,...,...,...,...,...,...,...
2343,8600000US11691,2013,18942,29.1,22.4,15.2,33.2,11691,2013_11691
2344,8600000US11692,2013,5974,26.4,23.1,23.1,27.3,11692,2013_11692
2345,8600000US11693,2013,4518,31.6,30.1,18.3,19.9,11693,2013_11693
2346,8600000US11694,2013,8190,32.5,28.0,17.7,21.8,11694,2013_11694
2347,8600000US11697,2013,1701,28.9,37.2,11.9,22.0,11697,2013_11697

# AGE

In [ ]:

url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S0101)&ucgid=860Z200US10001"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_test = json_to_dataframe(response)
df_test.head()

,GEO_ID,NAME,S0101_C01_001E,S0101_C01_001EA,S0101_C01_001M,S0101_C01_001MA,S0101_C01_002E,S0101_C01_002EA,S0101_C01_002M,S0101_C01_002MA,S0101_C01_003E,S0101_C01_003EA,S0101_C01_003M,S0101_C01_003MA,S0101_C01_004E,S0101_C01_004EA,S0101_C01_004M,S0101_C01_004MA,S0101_C01_005E,S0101_C01_005EA,S0101_C01_005M,S0101_C01_005MA,S0101_C01_006E,S0101_C01_006EA,S0101_C01_006M,S0101_C01_006MA,S0101_C01_007E,S0101_C01_007EA,S0101_C01_007M,S0101_C01_007MA,S0101_C01_008E,S0101_C01_008EA,S0101_C01_008M,S0101_C01_008MA,S0101_C01_009E,S0101_C01_009EA,S0101_C01_009M,S0101_C01_009MA,S0101_C01_010E,S0101_C01_010EA,S0101_C01_010M,S0101_C01_010MA,S0101_C01_011E,S0101_C01_011EA,S0101_C01_011M,S0101_C01_011MA,S0101_C01_012E,S0101_C01_012EA,S0101_C01_012M,S0101_C01_012MA,S0101_C01_013E,S0101_C01_013EA,S0101_C01_013M,S0101_C01_013MA,S0101_C01_014E,S0101_C01_014EA,S0101_C01_014M,S0101_C01_014MA,S0101_C01_015E,S0101_C01_015EA,S0101_C01_015M,S0101_C01_015MA,S0101_C01_016E,S0101_C01_016EA,S0101_C01_016M,S0101_C01_016MA,S0101_C01_017E,S0101_C01_017EA,S0101_C01_017M,S0101_C01_017MA,S0101_C01_018E,S0101_C01_018EA,S0101_C01_018M,S0101_C01_018MA,S0101_C01_019E,S0101_C01_019EA,S0101_C01_019M,S0101_C01_019MA,S0101_C01_020E,S0101_C01_020EA,S0101_C01_020M,S0101_C01_020MA,S0101_C01_021E,S0101_C01_021EA,S0101_C01_021M,S0101_C01_021MA,S0101_C01_022E,S0101_C01_022EA,S0101_C01_022M,S0101_C01_022MA,S0101_C01_023E,S0101_C01_023EA,S0101_C01_023M,S0101_C01_023MA,S0101_C01_024E,S0101_C01_024EA,S0101_C01_024M,S0101_C01_024MA,S0101_C01_025E,S0101_C01_025EA,S0101_C01_025M,S0101_C01_025MA,S0101_C01_026E,S0101_C01_026EA,S0101_C01_026M,S0101_C01_026MA,S0101_C01_027E,S0101_C01_027EA,S0101_C01_027M,S0101_C01_027MA,S0101_C01_028E,S0101_C01_028EA,S0101_C01_028M,S0101_C01_028MA,S0101_C01_029E,S0101_C01_029EA,S0101_C01_029M,S0101_C01_029MA,S0101_C01_030E,S0101_C01_030EA,S0101_C01_030M,S0101_C01_030MA,S0101_C01_031E,S0101_C01_031EA,S0101_C01_031M,S0101_C01_031MA,S0101_C01_032E,S0101_C01_032EA,S0101_C01_032M,S0101_C01_032MA,S0101_C01_033E,S0101_C01_033EA,S0101_C01_033M,S0101_C01_033MA,S0101_C01_034E,S0101_C01_034EA,S0101_C01_034M,S0101_C01_034MA,S0101_C01_035E,S0101_C01_035EA,S0101_C01_035M,S0101_C01_035MA,S0101_C01_036E,S0101_C01_036EA,S0101_C01_036M,S0101_C01_036MA,S0101_C01_037E,S0101_C01_037EA,S0101_C01_037M,S0101_C01_037MA,S0101_C01_038E,S0101_C01_038EA,S0101_C01_038M,S0101_C01_038MA,S0101_C02_001E,S0101_C02_001EA,S0101_C02_001M,S0101_C02_001MA,S0101_C02_002E,S0101_C02_002EA,S0101_C02_002M,S0101_C02_002MA,S0101_C02_003E,S0101_C02_003EA,S0101_C02_003M,S0101_C02_003MA,S0101_C02_004E,S0101_C02_004EA,S0101_C02_004M,S0101_C02_004MA,S0101_C02_005E,S0101_C02_005EA,S0101_C02_005M,S0101_C02_005MA,S0101_C02_006E,S0101_C02_006EA,S0101_C02_006M,S0101_C02_006MA,S0101_C02_007E,S0101_C02_007EA,S0101_C02_007M,S0101_C02_007MA,S0101_C02_008E,S0101_C02_008EA,S0101_C02_008M,S0101_C02_008MA,S0101_C02_009E,S0101_C02_009EA,S0101_C02_009M,S0101_C02_009MA,S0101_C02_010E,S0101_C02_010EA,S0101_C02_010M,S0101_C02_010MA,S0101_C02_011E,S0101_C02_011EA,S0101_C02_011M,S0101_C02_011MA,S0101_C02_012E,S0101_C02_012EA,S0101_C02_012M,S0101_C02_012MA,S0101_C02_013E,S0101_C02_013EA,S0101_C02_013M,S0101_C02_013MA,S0101_C02_014E,S0101_C02_014EA,S0101_C02_014M,S0101_C02_014MA,S0101_C02_015E,S0101_C02_015EA,S0101_C02_015M,S0101_C02_015MA,S0101_C02_016E,S0101_C02_016EA,S0101_C02_016M,S0101_C02_016MA,S0101_C02_017E,S0101_C02_017EA,S0101_C02_017M,S0101_C02_017MA,S0101_C02_018E,S0101_C02_018EA,S0101_C02_018M,S0101_C02_018MA,S0101_C02_019E,S0101_C02_019EA,S0101_C02_019M,S0101_C02_019MA,S0101_C02_020E,S0101_C02_020EA,S0101_C02_020M,S0101_C02_020MA,S0101_C02_021E,S0101_C02_021EA,S0101_C02_021M,S0101_C02_021MA,S0101_C02_022E,S0101_C02_022EA,S0101_C02_022M,S0101_C02_022MA,S0101_C02_023E,S0101_C02_023EA,S0101_C02_023M,S0101_C02_023MA,S0101_C02_024E,S0101_C02_024EA,S0101_C02_024M,S0101_C02_024MA,S0101_C02_025E,S0101_C02_025EA,S0101_C02_025M,S0101_C02_025MA,S0101_C02_026E,S0101_C02_026EA,S0101_C02_026M,S0101_C02_026MA,S0101_C02_027E,S0101_C02_027EA,S0101_C02_027M,S0101_C02_027MA,S0101_C02_028E,S0101_C02_028EA,S0101_C02_028M,S0101_C02_028MA,S0101_C02_029E,S0101_C02_029EA,S0101_C02_029M,S0101_C02_029MA,S0101_C02_030E,S0101_C02_030EA,S0101_C02_030M,S0101_C02_030MA,S0101_C02_031E,S0101_C02_031EA,S0101_C02_031M,S0101_C02_031MA,S0101_C02_032E,S0101_C02_032EA,S0101_C02_032M,S0101_C02_032MA,S0101_C02_033E,S0101_C02_033EA,S0101_C02_033M,S0101_C02_033MA,S0101_C02_034E,S0101_C02_034EA,S0101_C02_034M,S0101_C02_034MA,S0101_C02_035E,S0101_C02_035EA,S0101_C02_035M,S0101_C02_035MA,S0101_C02_036E,S0101_C02_036EA,S0101_C02_036M,S0101_C02_036MA,S0101_C02_037E,S0101_C02_037EA,S0101_C02_037M,S0101_C02_037MA,S0101_C02_038E,S0101_C02_038EA,S0101_C02_038M,S0101_C02_038MA,S0101_C03_001E,S0101_C03_001EA,S0101_C03_001M,S0101_C03_001MA,S0101_C03_002E,S0101_C03_002EA,S0101_C03_002M,S0101_C03_002MA,S0101_C03_003E,S0101_C03_003EA,S0101_C03_003M,S0101_C03_003MA,S0101_C03_004E,S0101_C03_004EA,S0101_C03_004M,S0101_C03_004MA,S0101_C03_005E,S0101_C03_005EA,S0101_C03_005M,S0101_C03_005MA,S0101_C03_006E,S0101_C03_006EA,S0101_C03_006M,S0101_C03_006MA,S0101_C03_007E,S0101_C03_007EA,S0101_C03_007M,S0101_C03_007MA,S0101_C03_008E,S0101_C03_008EA,S0101_C03_008M,S0101_C03_008MA,S0101_C03_009E,S0101_C03_009EA,S0101_C03_009M,S0101_C03_009MA,S0101_C03_010E,S0101_C03_010EA,S0101_C03_010M,S0101_C03_010MA,S0101_C03_011E,S0101_C03_011EA,S0101_C03_011M,S0101_C03_011MA,S0101_C03_012E,S0101_C03_012EA,S0101_C03_012M,S0101_C03_012MA,S0101_C03_013E,S0101_C03_013EA,S0101_C03_013M,S0101_C03_013MA,S0101_C03_014E,S0101_C03_014EA,S0101_C03_014M,S0101_C03_014MA,S0101_C03_015E,S0101_C03_015EA,S0101_C03_015M,S0101_C03_015MA,S0101_C03_016E,S0101_C03_016EA,S0101_C03_016M,S0101_C03_016MA,S0101_C03_017E,S0101_C03_017EA,S0101_C03_017M,S0101_C03_017MA,S0101_C03_018E,S0101_C03_018EA,S0101_C03_018M,S0101_C03_018MA,S0101_C03_019E,S0101_C03_019EA,S0101_C03_019M,S0101_C03_019MA,S0101_C03_020E,S0101_C03_020EA,S0101_C03_020M,S0101_C03_020MA,S0101_C03_021E,S0101_C03_021EA,S0101_C03_021M,S0101_C03_021MA,S0101_C03_022E,S0101_C03_022EA,S0101_C03_022M,S0101_C03_022MA,S0101_C03_023E,S0101_C03_023EA,S0101_C03_023M,S0101_C03_023MA,S0101_C03_024E,S0101_C03_024EA,S0101_C03_024M,S0101_C03_024MA,S0101_C03_025E,S0101_C03_025EA,S0101_C03_025M,S0101_C03_025MA,S0101_C03_026E,S0101_C03_026EA,S0101_C03_026M,S0101_C03_026MA,S0101_C03_027E,S0101_C03_027EA,S0101_C03_027M,S0101_C03_027MA,S0101_C03_028E,S0101_C03_028EA,S0101_C03_028M,S0101_C03_028MA,S0101_C03_029E,S0101_C03_029EA,S0101_C03_029M,S0101_C03_029MA,S0101_C03_030E,S0101_C03_030EA,S0101_C03_030M,S0101_C03_030MA,S0101_C03_031E,S0101_C03_031EA,S0101_C03_031M,S0101_C03_031MA,S0101_C03_032E,S0101_C03_032EA,S0101_C03_032M,S0101_C03_032MA,S0101_C03_033E,S0101_C03_033EA,S0101_C03_033M,S0101_C03_033MA,S0101_C03_034E,S0101_C03_034EA,S0101_C03_034M,S0101_C03_034MA,S0101_C03_035E,S0101_C03_035EA,S0101_C03_035M,S0101_C03_035MA,S0101_C03_036E,S0101_C03_036EA,S0101_C03_036M,S0101_C03_036MA,S0101_C03_037E,S0101_C03_037EA,S0101_C03_037M,S0101_C03_037MA,S0101_C03_038E,S0101_C03_038EA,S0101_C03_038M,S0101_C03_038MA,S0101_C04_001E,S0101_C04_001EA,S0101_C04_001M,S0101_C04_001MA,S0101_C04_002E,S0101_C04_002EA,S0101_C04_002M,S0101_C04_002MA,S0101_C04_003E,S0101_C04_003EA,S0101_C04_003M,S0101_C04_003MA,S0101_C04_004E,S0101_C04_004EA,S0101_C04_004M,S0101_C04_004MA,S0101_C04_005E,S0101_C04_005EA,S0101_C04_005M,S0101_C04_005MA,S0101_C04_006E,S0101_C04_006EA,S0101_C04_006M,S0101_C04_006MA,S0101_C04_007E,S0101_C04_007EA,S0101_C04_007M,S0101_C04_007MA,S0101_C04_008E,S0101_C04_008EA,S0101_C04_008M,S0101_C04_008MA,S0101_C04_009E,S0101_C04_009EA,S0101_C04_009M,S0101_C04_009MA,S0101_C04_010E,S0101_C04_010EA,S0101_C04_010M,S0101_C04_010MA,S0101_C04_011E,S0101_C04_011EA,S0101_C04_011M,S0101_C04_011MA,S0101_C04_012E,S0101_C04_012EA,S0101_C04_012M,S0101_C04_012MA,S0101_C04_013E,S0101_C04_013EA,S0101_C04_013M,S0101_C04_013MA,S0101_C04_014E,S0101_C04_014EA,S0101_C04_014M,S0101_C04_014MA,S0101_C04_015E,S0101_C04_015EA,S0101_C04_015M,S0101_C04_015MA,S0101_C04_016E,S0101_C04_016EA,S0101_C04_016M,S0101_C04_016MA,S0101_C04_017E,S0101_C04_017EA,S0101_C04_017M,S0101_C04_017MA,S0101_C04_018E,S0101_C04_018EA,S0101_C04_018M,S0101_C04_018MA,S0101_C04_019E,S0101_C04_019EA,S0101_C04_019M,S0101_C04_019MA,S0101_C04_020E,S0101_C04_020EA,S0101_C04_020M,S0101_C04_020MA,S0101_C04_021E,S0101_C04_021EA,S0101_C04_021M,S0101_C04_021MA,S0101_C04_022E,S0101_C04_022EA,S0101_C04_022M,S0101_C04_022MA,S0101_C04_023E,S0101_C04_023EA,S0101_C04_023M,S0101_C04_023MA,S0101_C04_024E,S0101_C04_024EA,S0101_C04_024M,S0101_C04_024MA,S0101_C04_025E,S0101_C04_025EA,S0101_C04_025M,S0101_C04_025MA,S0101_C04_026E,S0101_C04_026EA,S0101_C04_026M,S0101_C04_026MA,S0101_C04_027E,S0101_C04_027EA,S0101_C04_027M,S0101_C04_027MA,S0101_C04_028E,S0101_C04_028EA,S0101_C04_028M,S0101_C04_028MA,S0101_C04_029E,S0101_C04_029EA,S0101_C04_029M,S0101_C04_029MA,S0101_C04_030E,S0101_C04_030EA,S0101_C04_030M,S0101_C04_030MA,S0101_C04_031E,S0101_C04_031EA,S0101_C04_031M,S0101_C04_031MA,S0101_C04_032E,S0101_C04_032EA,S0101_C04_032M,S0101_C04_032MA,S0101_C04_033E,S0101_C04_033EA,S0101_C04_033M,S0101_C04_033MA,S0101_C04_034E,S0101_C04_034EA,S0101_C04_034M,S0101_C04_034MA,S0101_C04_035E,S0101_C04_035EA,S0101_C04_035M,S0101_C04_035MA,S0101_C04_036E,S0101_C04_036EA,S0101_C04_036M,S0101_C04_036MA,S0101_C04_037E,S0101_C04_037EA,S0101_C04_037M,S0101_C04_037MA,S0101_C04_038E,S0101_C04_038EA,S0101_C04_038M,S0101_C04_038MA,S0101_C05_001E,S0101_C05_001EA,S0101_C05_001M,S0101_C05_001MA,S0101_C05_002E,S0101_C05_002EA,S0101_C05_002M,S0101_C05_002MA,S0101_C05_003E,S0101_C05_003EA,S0101_C05_003M,S0101_C05_003MA,S0101_C05_004E,S0101_C05_004EA,S0101_C05_004M,S0101_C05_004MA,S0101_C05_005E,S0101_C05_005EA,S0101_C05_005M,S0101_C05_005MA,S0101_C05_006E,S0101_C05_006EA,S0101_C05_006M,S0101_C05_006MA,S0101_C05_007E,S0101_C05_007EA,S0101_C05_007M,S0101_C05_007MA,S0101_C05_008E,S0101_C05_008EA,S0101_C05_008M,S0101_C05_008MA,S0101_C05_009E,S0101_C05_009EA,S0101_C05_009M,S0101_C05_009MA,S0101_C05_010E,S0101_C05_010EA,S0101_C05_010M,S0101_C05_010MA,S0101_C05_011E,S0101_C05_011EA,S0101_C05_011M,S0101_C05_011MA,S0101_C05_012E,S0101_C05_012EA,S0101_C05_012M,S0101_C05_012MA,S0101_C05_013E,S0101_C05_013EA,S0101_C05_013M,S0101_C05_013MA,S0101_C05_014E,S0101_C05_014EA,S0101_C05_014M,S0101_C05_014MA,S0101_C05_015E,S0101_C05_015EA,S0101_C05_015M,S0101_C05_015MA,S0101_C05_016E,S0101_C05_016EA,S0101_C05_016M,S0101_C05_016MA,S0101_C05_017E,S0101_C05_017EA,S0101_C05_017M,S0101_C05_017MA,S0101_C05_018E,S0101_C05_018EA,S0101_C05_018M,S0101_C05_018MA,S0101_C05_019E,S0101_C05_019EA,S0101_C05_019M,S0101_C05_019MA,S0101_C05_020E,S0101_C05_020EA,S0101_C05_020M,S0101_C05_020MA,S0101_C05_021E,S0101_C05_021EA,S0101_C05_021M,S0101_C05_021MA,S0101_C05_022E,S0101_C05_022EA,S0101_C05_022M,S0101_C05_022MA,S0101_C05_023E,S0101_C05_023EA,S0101_C05_023M,S0101_C05_023MA,S0101_C05_024E,S0101_C05_024EA,S0101_C05_024M,S0101_C05_024MA,S0101_C05_025E,S0101_C05_025EA,S0101_C05_025M,S0101_C05_025MA,S0101_C05_026E,S0101_C05_026EA,S0101_C05_026M,S0101_C05_026MA,S0101_C05_027E,S0101_C05_027EA,S0101_C05_027M,S0101_C05_027MA,S0101_C05_028E,S0101_C05_028EA,S0101_C05_028M,S0101_C05_028MA,S0101_C05_029E,S0101_C05_029EA,S0101_C05_029M,S0101_C05_029MA,S0101_C05_030E,S0101_C05_030EA,S0101_C05_030M,S0101_C05_030MA,S0101_C05_031E,S0101_C05_031EA,S0101_C05_031M,S0101_C05_031MA,S0101_C05_032E,S0101_C05_032EA,S0101_C05_032M,S0101_C05_032MA,S0101_C05_033E,S0101_C05_033EA,S0101_C05_033M,S0101_C05_033MA,S0101_C05_034E,S0101_C05_034EA,S0101_C05_034M,S0101_C05_034MA,S0101_C05_035E,S0101_C05_035EA,S0101_C05_035M,S0101_C05_035MA,S0101_C05_036E,S0101_C05_036EA,S0101_C05_036M,S0101_C05_036MA,S0101_C05_037E,S0101_C05_037EA,S0101_C05_037M,S0101_C05_037MA,S0101_C05_038E,S0101_C05_038EA,S0101_C05_038M,S0101_C05_038MA,S0101_C06_001E,S0101_C06_001EA,S0101_C06_001M,S0101_C06_001MA,S0101_C06_002E,S0101_C06_002EA,S0101_C06_002M,S0101_C06_002MA,S0101_C06_003E,S0101_C06_003EA,S0101_C06_003M,S0101_C06_003MA,S0101_C06_004E,S0101_C06_004EA,S0101_C06_004M,S0101_C06_004MA,S0101_C06_005E,S0101_C06_005EA,S0101_C06_005M,S0101_C06_005MA,S0101_C06_006E,S0101_C06_006EA,S0101_C06_006M,S0101_C06_006MA,S0101_C06_007E,S0101_C06_007EA,S0101_C06_007M,S0101_C06_007MA,S0101_C06_008E,S0101_C06_008EA,S0101_C06_008M,S0101_C06_008MA,S0101_C06_009E,S0101_C06_009EA,S0101_C06_009M,S0101_C06_009MA,S0101_C06_010E,S0101_C06_010EA,S0101_C06_010M,S0101_C06_010MA,S0101_C06_011E,S0101_C06_011EA,S0101_C06_011M,S0101_C06_011MA,S0101_C06_012E,S0101_C06_012EA,S0101_C06_012M,S0101_C06_012MA,S0101_C06_013E,S0101_C06_013EA,S0101_C06_013M,S0101_C06_013MA,S0101_C06_014E,S0101_C06_014EA,S0101_C06_014M,S0101_C06_014MA,S0101_C06_015E,S0101_C06_015EA,S0101_C06_015M,S0101_C06_015MA,S0101_C06_016E,S0101_C06_016EA,S0101_C06_016M,S0101_C06_016MA,S0101_C06_017E,S0101_C06_017EA,S0101_C06_017M,S0101_C06_017MA,S0101_C06_018E,S0101_C06_018EA,S0101_C06_018M,S0101_C06_018MA,S0101_C06_019E,S0101_C06_019EA,S0101_C06_019M,S0101_C06_019MA,S0101_C06_020E,S0101_C06_020EA,S0101_C06_020M,S0101_C06_020MA,S0101_C06_021E,S0101_C06_021EA,S0101_C06_021M,S0101_C06_021MA,S0101_C06_022E,S0101_C06_022EA,S0101_C06_022M,S0101_C06_022MA,S0101_C06_023E,S0101_C06_023EA,S0101_C06_023M,S0101_C06_023MA,S0101_C06_024E,S0101_C06_024EA,S0101_C06_024M,S0101_C06_024MA,S0101_C06_025E,S0101_C06_025EA,S0101_C06_025M,S0101_C06_025MA,S0101_C06_026E,S0101_C06_026EA,S0101_C06_026M,S0101_C06_026MA,S0101_C06_027E,S0101_C06_027EA,S0101_C06_027M,S0101_C06_027MA,S0101_C06_028E,S0101_C06_028EA,S0101_C06_028M,S0101_C06_028MA,S0101_C06_029E,S0101_C06_029EA,S0101_C06_029M,S0101_C06_029MA,S0101_C06_030E,S0101_C06_030EA,S0101_C06_030M,S0101_C06_030MA,S0101_C06_031E,S0101_C06_031EA,S0101_C06_031M,S0101_C06_031MA,S0101_C06_032E,S0101_C06_032EA,S0101_C06_032M,S0101_C06_032MA,S0101_C06_033E,S0101_C06_033EA,S0101_C06_033M,S0101_C06_033MA,S0101_C06_034E,S0101_C06_034EA,S0101_C06_034M,S0101_C06_034MA,S0101_C06_035E,S0101_C06_035EA,S0101_C06_035M,S0101_C06_035MA,S0101_C06_036E,S0101_C06_036EA,S0101_C06_036M,S0101_C06_036MA,S0101_C06_037E,S0101_C06_037EA,S0101_C06_037M,S0101_C06_037MA,S0101_C06_038E,S0101_C06_038EA,S0101_C06_038M,S0101_C06_038MA,ucgid
0,860Z200US10001,ZCTA5 10001,29079,None,1790,None,1173,None,403,None,889,None,508,None,907,None,396,None,1302,None,241,None,2084,None,412,None,3993,None,640,None,4172,None,695,None,2697,None,668,None,1975,None,544,None,1741,None,435,None,1604,None,347,None,1625,None,348,None,1361,None,431,None,1150,None,273,None,1083,None,301,None,600,None,182,None,258,None,175,None,465,None,247,None,1796,None,677,None,353,None,163,None,3322,None,724,None,3033,None,389,None,16223,None,1307,None,25900,None,1482,None,25757,None,1495,None,24492,None,1493,None,4917,None,700,None,4169,None,608,None,3556,None,526,None,1323,None,361,None,35.0,None,1.0,None,93.7,None,12.2,None,31.0,None,4.6,None,16.0,None,2.8,None,15.0,None,3.2,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),4.0,None,1.3,None,3.1,None,1.7,None,3.1,None,1.3,None,4.5,None,0.9,None,7.2,None,1.4,None,13.7,None,2.1,None,14.3,None,2.0,None,9.3,None,2.1,None,6.8,None,1.8,None,6.0,None,1.5,None,5.5,None,1.2,None,5.6,None,1.2,None,4.7,None,1.5,None,4.0,None,1.0,None,3.7,None,1.1,None,2.1,None,0.6,None,0.9,None,0.6,None,1.6,None,0.8,None,6.2,None,2.3,None,1.2,None,0.6,None,11.4,None,2.2,None,10.4,None,1.3,None,55.8,None,2.5,None,89.1,None,2.1,None,88.6,None,2.2,None,84.2,None,2.2,None,16.9,None,2.4,None,14.3,None,2.1,None,12.2,None,1.8,None,4.5,None,1.2,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),0.0,None,-888888888.0,(X),1.8,None,-888888888.0,(X),14069,None,1231,None,675,None,324,None,529,None,414,None,398,None,169,None,390,None,127,None,798,None,257,None,1642,None,441,None,2384,None,507,None,1425,None,387,None,897,None,414,None,826,None,288,None,909,None,259,None,953,None,327,None,658,None,238,None,569,None,232,None,580,None,200,None,200,None,82,None,109,None,99,None,127,None,139,None,927,None,479,None,180,None,105,None,1782,None,527,None,1008,None,275,None,7536,None,881,None,12343,None,998,None,12287,None,1000,None,12024,None,1001,None,2243,None,425,None,1916,None,401,None,1585,None,328,None,436,None,196,None,35.6,None,1.7,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),4.8,None,2.2,None,3.8,None,2.9,None,2.8,None,1.2,None,2.8,None,0.9,None,5.7,None,1.8,None,11.7,None,3.0,None,16.9,None,3.0,None,10.1,None,2.7,None,6.4,None,2.8,None,5.9,None,2.0,None,6.5,None,1.9,None,6.8,None,2.3,None,4.7,None,1.6,None,4.0,None,1.6,None,4.1,None,1.5,None,1.4,None,0.6,None,0.8,None,0.7,None,0.9,None,1.0,None,6.6,None,3.2,None,1.3,None,0.7,None,12.7,None,3.2,None,7.2,None,1.9,None,53.6,None,3.6,None,87.7,None,3.2,None,87.3,None,3.2,None,85.5,None,3.1,None,15.9,None,2.9,None,13.6,None,2.7,None,11.3,None,2.3,None,3.1,None,1.4,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),15010,None,1357,None,498,None,244,None,360,None,226,None,509,None,323,None,912,None,200,None,1286,None,318,None,2351,None,461,None,1788,None,377,None,1272,None,449,None,1078,None,287,None,915,None,349,None,695,None,234,None,672,None,209,None,703,None,266,None,581,None,185,None,503,None,186,None,400,None,160,None,149,None,94,None,338,None,199,None,869,None,413,None,173,None,137,None,1540,None,485,None,2025,None,315,None,8687,None,843,None,13557,None,1127,None,13470,None,1144,None,12468,None,1133,None,2674,None,448,None,2253,None,406,None,1971,None,378,None,887,None,263,None,34.3,None,1.7,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),3.3,None,1.5,None,2.4,None,1.4,None,3.4,None,2.1,None,6.1,None,1.5,None,8.6,None,2.0,None,15.7,None,2.9,None,11.9,None,2.2,None,8.5,None,2.8,None,7.2,None,1.9,None,6.1,None,2.2,None,4.6,None,1.6,None,4.5,None,1.3,None,4.7,None,1.7,None,3.9,None,1.2,None,3.4,None,1.3,None,2.7,None,1.1,None,1.0,None,0.6,None,2.3,None,1.3,None,5.8,None,2.6,None,1.2,None,1.0,None,10.3,None,2.8,None,13.5,None,2.1,None,57.9,None,3.4,None,90.3,None,2.7,None,89.7,None,2.8,None,83.1,None,2.8,None,17.8,None,2.9,None,15.0,None,2.6,None,13.1,None,2.5,None,5.9,None,1.7,None,-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),-888888888,(X),860Z200US10001

In [ ]:
'''
S0101_C01_001E = total population
S0101_C01_002E = Under 5 years
S0101_C01_003E = 5 to 9
S0101_C01_004E = 10 to 14
S0101_C01_005E = 15 to 19
S0101_C01_006E = 20 to 24
S0101_C01_007E = 25 to 34
S0101_C01_008E = 35 to 39
S0101_C01_009E = 40 to 44
S0101_C01_010E = 45 to 49
S0101_C01_011E = 50 to 54
S0101_C01_012E = 55 to 59
S0101_C01_013E = 60 to 64
S0101_C01_014E = 65 to 69
S0101_C01_015E = 70 to 74
S0101_C01_016E = 75 to 79
S0101_C01_017E = 80 to 84
S0101_C01_018E = over 85

In [ ]:
S0101_C01_001E
S0101_C01_002E
S0101_C01_003E
S0101_C01_004E
S0101_C01_005E
S0101_C01_006E
S0101_C01_007E
S0101_C01_008E
S0101_C01_009E
S0101_C01_010E
S0101_C01_011E
S0101_C01_012E
S0101_C01_013E
S0101_C01_014E
S0101_C01_015E
S0101_C01_016E
S0101_C01_017E
S0101_C01_018E

In [ ]:
def process_age_response(response, year):
    df = pd.DataFrame(response.json()[1:], columns=response.json()[0])
    df = df[['ucgid',
             'S0101_C01_001E','S0101_C01_002E','S0101_C01_003E','S0101_C01_004E','S0101_C01_005E',
             'S0101_C01_006E','S0101_C01_007E','S0101_C01_008E','S0101_C01_009E','S0101_C01_010E',
             'S0101_C01_011E','S0101_C01_012E','S0101_C01_013E','S0101_C01_014E','S0101_C01_015E',
             'S0101_C01_016E','S0101_C01_017E','S0101_C01_018E']]
    df['year'] = str(year)
    return df[['ucgid', 'year', 'S0101_C01_001E','S0101_C01_002E','S0101_C01_003E','S0101_C01_004E','S0101_C01_005E',
             'S0101_C01_006E','S0101_C01_007E','S0101_C01_008E','S0101_C01_009E','S0101_C01_010E',
             'S0101_C01_011E','S0101_C01_012E','S0101_C01_013E','S0101_C01_014E','S0101_C01_015E',
             'S0101_C01_016E','S0101_C01_017E','S0101_C01_018E']]

In [ ]:
url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S0101)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2023 = process_age_response(response, 2023)
print(df_age_2023.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  860Z200US10001  2023          29079           1173            889
1  860Z200US10002  2023          75517           2259           3268
2  860Z200US10003  2023          53825           1399            999
3  860Z200US10004  2023           3875            364            284
4  860Z200US10005  2023           9238            356            168

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            907           1302           2084           3993           4172
1           3051           2724           4797           7173           5944
2            926           7281           6676           7119           5838
3             73             91             53            570            708
4            319             56           1014           2272           1304

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           2697           1975           1741           1604           1625
1           5349           5147           4267           4511           5651
2           3112           3115           2052           2525           2087
3            529            239            298             90            267
4           1103            632            475            699            348

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1361           1150           1083            600            258
1           4108           4945           5034           2646           2124
2           2413           2831           2081           1583            812
3            132            114              4             22              7
4            131            157            204              0              0

In [ ]:
url = "https://api.census.gov/data/2022/acs/acs5/subject?get=group(S0101)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2022 = process_age_response(response, 2022)
print(df_age_2022.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  860Z200US10001  2022          27004            744            784
1  860Z200US10002  2022          76518           2142           3046
2  860Z200US10003  2022          53877           1440           1034
3  860Z200US10004  2022           4579            433            182
4  860Z200US10005  2022           8801            484            204

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            942           1035           2296           3806           3588
1           3198           2652           4528           6988           6278
2            953           7013           6344           7100           6427
3            161            108            109            601            724
4            229             53            989           2604           1144

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           2524           1702           1903           1704           1225
1           5157           4962           4822           4410           6106
2           3221           2907           1988           2698           2350
3            490            241            313            549            279
4            945            685            351            652            218

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1323            933            815            616            488
1           4548           4815           4748           2531           2793
2           2274           2793           1854           1646            779
3            199            173              2             15              0
4             85             92             66              0              0

In [ ]:
url = "https://api.census.gov/data/2021/acs/acs5/subject?get=group(S0101)&ucgid=860Z200US10001,860Z200US10002,860Z200US10003,860Z200US10004,860Z200US10005,860Z200US10006,860Z200US10007,860Z200US10009,860Z200US10010,860Z200US10011,860Z200US10012,860Z200US10013,860Z200US10014,860Z200US10016,860Z200US10017,860Z200US10018,860Z200US10019,860Z200US10020,860Z200US10021,860Z200US10022,860Z200US10023,860Z200US10024,860Z200US10025,860Z200US10026,860Z200US10027,860Z200US10028,860Z200US10029,860Z200US10030,860Z200US10031,860Z200US10032,860Z200US10033,860Z200US10034,860Z200US10035,860Z200US10036,860Z200US10037,860Z200US10038,860Z200US10039,860Z200US10040,860Z200US10044,860Z200US10065,860Z200US10069,860Z200US10075,860Z200US10103,860Z200US10110,860Z200US10111,860Z200US10112,860Z200US10115,860Z200US10119,860Z200US10128,860Z200US10152,860Z200US10153,860Z200US10154,860Z200US10162,860Z200US10165,860Z200US10167,860Z200US10168,860Z200US10169,860Z200US10170,860Z200US10171,860Z200US10172,860Z200US10173,860Z200US10174,860Z200US10177,860Z200US10199,860Z200US10271,860Z200US10278,860Z200US10279,860Z200US10280,860Z200US10282,860Z200US10301,860Z200US10302,860Z200US10303,860Z200US10304,860Z200US10305,860Z200US10306,860Z200US10307,860Z200US10308,860Z200US10309,860Z200US10310,860Z200US10311,860Z200US10312,860Z200US10314,860Z200US10451,860Z200US10452,860Z200US10453,860Z200US10454,860Z200US10455,860Z200US10456,860Z200US10457,860Z200US10458,860Z200US10459,860Z200US10460,860Z200US10461,860Z200US10462,860Z200US10463,860Z200US10464,860Z200US10465,860Z200US10466,860Z200US10467,860Z200US10468,860Z200US10469,860Z200US10470,860Z200US10471,860Z200US10472,860Z200US10473,860Z200US10474,860Z200US10475,860Z200US11001,860Z200US11003,860Z200US11004,860Z200US11005,860Z200US11040,860Z200US11101,860Z200US11102,860Z200US11103,860Z200US11104,860Z200US11105,860Z200US11106,860Z200US11109,860Z200US11201,860Z200US11203,860Z200US11204,860Z200US11205,860Z200US11206,860Z200US11207,860Z200US11208,860Z200US11209,860Z200US11210,860Z200US11211,860Z200US11212,860Z200US11213,860Z200US11214,860Z200US11215,860Z200US11216,860Z200US11217,860Z200US11218,860Z200US11219,860Z200US11220,860Z200US11221,860Z200US11222,860Z200US11223,860Z200US11224,860Z200US11225,860Z200US11226,860Z200US11228,860Z200US11229,860Z200US11230,860Z200US11231,860Z200US11232,860Z200US11233,860Z200US11234,860Z200US11235,860Z200US11236,860Z200US11237,860Z200US11238,860Z200US11239,860Z200US11351,860Z200US11354,860Z200US11355,860Z200US11356,860Z200US11357,860Z200US11358,860Z200US11359,860Z200US11360,860Z200US11361,860Z200US11362,860Z200US11363,860Z200US11364,860Z200US11365,860Z200US11366,860Z200US11367,860Z200US11368,860Z200US11369,860Z200US11370,860Z200US11371,860Z200US11372,860Z200US11373,860Z200US11374,860Z200US11375,860Z200US11377,860Z200US11378,860Z200US11379,860Z200US11385,860Z200US11411,860Z200US11412,860Z200US11413,860Z200US11414,860Z200US11415,860Z200US11416,860Z200US11417,860Z200US11418,860Z200US11419,860Z200US11420,860Z200US11421,860Z200US11422,860Z200US11423,860Z200US11424,860Z200US11425,860Z200US11426,860Z200US11427,860Z200US11428,860Z200US11429,860Z200US11430,860Z200US11432,860Z200US11433,860Z200US11434,860Z200US11435,860Z200US11436,860Z200US11451,860Z200US11691,860Z200US11692,860Z200US11693,860Z200US11694,860Z200US11697,860Z200US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2021 = process_age_response(response, 2021)
print(df_age_2021.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  860Z200US10001  2021          26966           1004           1012
1  860Z200US10002  2021          76807           2461           3061
2  860Z200US10003  2021          54447           1452            924
3  860Z200US10004  2021           4795            615            147
4  860Z200US10005  2021           8637            502            235

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            829            879           1946           3615           3862
1           3337           2555           4646           7565           6291
2            865           7320           6297           7443           6326
3            176            119            114            605            756
4            198             81            792           2407           1252

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           2455           1934           1830           1646           1200
1           4864           4785           5066           4345           5797
2           3199           3016           2137           2670           2439
3            534            173            465            439            217
4            897            766            561            490            255

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1459            802            736            583            469
1           4486           5069           4410           2384           2814
2           2660           2858           1906           1456            639
3            179            159             65             32              0
4            115             59             27              0              0

In [ ]:
url = "https://api.census.gov/data/2020/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2020 = process_age_response(response, 2020)
print(df_age_2020.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2020          25026            866            667
1  8600000US10002  2020          74363           2241           3023
2  8600000US10003  2020          54671           1549            819
3  8600000US10004  2020           3310            108             53
4  8600000US10005  2020           8664            479            196

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            995           1050           1898           3156           3457
1           3203           2361           4593           7069           5949
2            865           7218           5809           8086           7332
3             48            116             86            725            306
4            145            138           1008           2223           1476

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           2064           1885           1658           1547           1109
1           4421           4514           4787           4355           5204
2           3512           2702           1838           2664           2525
3            270            159            208            416            262
4            834            826            415            398            338

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1510            734            687            737            389
1           4992           5005           3849           2512           2908
2           2828           2416           1556           1422            711
3            275            162             52             29              0
4             96             17             51             24              0

In [ ]:
url = "https://api.census.gov/data/2019/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2019 = process_age_response(response, 2019)
print(df_age_2019.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2019          24117            696            376
1  8600000US10002  2019          74479           2516           2614
2  8600000US10003  2019          53977           1421            890
3  8600000US10004  2019           3335            173             78
4  8600000US10005  2019           8701            564            277

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            735           1215           2043           3275           2807
1           2850           2597           4556           7406           5959
2            549           7501           5717           7545           5867
3             86             75             86            468            409
4             91            230           1090           1955           1479

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           1873           1490           1658           1630           1246
1           4964           4369           5281           4189           4841
2           4133           2730           2459           2440           2482
3            467            170            182            522            197
4            984            799            477            295            333

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1583            912            803            802            394
1           5406           4475           3802           2611           3015
2           3028           2485           1745           1354            739
3            221             60             62             33              0
4             34              7             56             30              0

In [ ]:
url = "https://api.census.gov/data/2018/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2018 = process_age_response(response, 2018)
print(df_age_2018.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2018          22924            472            526
1  8600000US10002  2018          74993           2637           2640
2  8600000US10003  2018          54682           1767            926
3  8600000US10004  2018           3028            125             51
4  8600000US10005  2018           8831            522            302

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            712           1161           2068           3096           2714
1           2824           2969           4763           7593           6171
2            670           7496           5587           7896           5922
3            117             80            108            412            374
4            176            199           1046           2101           1407

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           1555           1664           1562           1416           1153
1           4566           4476           5492           4792           4882
2           4651           2927           2620           2284           2683
3            392            179            172            466            137
4           1095            826            494            237            279

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1425            990            603            925            423
1           5378           4159           3552           2467           2658
2           2820           2032           1408           1319            815
3            187             75             92             33              0
4             35              8             76             28              0

In [ ]:
url = "https://api.census.gov/data/2017/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2017 = process_age_response(response, 2017)
print(df_age_2017.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2017          23947            622            893
1  8600000US10002  2017          77925           2827           2907
2  8600000US10003  2017          55035           1846            797
3  8600000US10004  2017           2990            100             83
4  8600000US10005  2017           8680            401            268

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            832           1237           2524           2935           2747
1           3007           3209           5037           8004           6601
2            593           7423           5037           8382           6007
3            111            135            152            412            454
4            126            244           1238           1949           1364

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           1823           1682           1596           1320           1348
1           5552           4586           5656           4944           4582
2           4860           3274           2601           2208           2405
3            367            240            163            240            183
4           1363            623            451            189            242

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1437           1031            607            789            284
1           5276           3989           3760           2876           2317
2           3223           2153           1447           1015            812
3            152             83             81             29              5
4             43              7            130             42              0

In [ ]:
url = "https://api.census.gov/data/2016/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2016 = process_age_response(response, 2016)
print(df_age_2016.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2016          23332            2.1            3.8
1  8600000US10002  2016          78096            3.6            4.1
2  8600000US10003  2016          56767            3.1            1.4
3  8600000US10004  2016           3044            2.8            3.4
4  8600000US10005  2016           8710            4.1            3.0

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            3.8            4.8           11.0           11.6           10.6
1            4.0            4.6            6.5           10.2            8.2
2            1.1           13.4            9.7           15.0           12.1
3            4.1            5.6            7.1           15.2           13.9
4            1.8            2.1           14.1           27.3           14.7

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0            8.2            8.5            6.6            5.9            6.4
1            7.2            6.4            7.6            6.4            5.6
2            8.1            6.1            4.7            4.4            4.3
3           11.8            6.3            4.9            7.6            5.6
4           14.6            6.9            4.6            2.4            2.5

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0            4.8            4.4            2.2            2.9            1.5
1            7.3            4.4            4.5            3.3            2.7
2            5.7            3.9            2.2            1.8            1.2
3            6.2            3.1            1.9            0.1            0.3
4            0.2            0.0            1.1            0.5            0.0

In [ ]:
url = "https://api.census.gov/data/2015/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2015 = process_age_response(response, 2015)
print(df_age_2015.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2015          23537            2.4            4.6
1  8600000US10002  2015          80736            3.8            3.9
2  8600000US10003  2015          57112            2.7            1.6
3  8600000US10004  2015           3221            3.9            3.1
4  8600000US10005  2015           8131            3.7            3.1

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            3.8            4.5           11.8           11.2           10.0
1            4.5            4.9            6.6            9.8            7.4
2            1.3           12.8           10.0           15.6           11.6
3            5.0            7.0            7.9           14.4           12.2
4            1.7            1.0           13.5           29.6           15.8

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0            9.6            7.0            6.3            5.6            7.0
1            7.8            7.1            7.7            6.2            5.8
2            7.6            6.1            5.5            4.6            5.2
3           11.3            6.5            3.3            8.7            5.2
4           13.1            7.8            4.5            3.3            1.4

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0            4.4            4.4            2.2            2.7            1.5
1            6.6            4.1            4.3            3.4            3.0
2            5.1            3.8            2.1            2.0            1.0
3            6.1            3.4            1.7            0.1            0.2
4            0.5            0.3            0.8            0.0            0.0

In [ ]:
url = "https://api.census.gov/data/2014/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2014 = process_age_response(response, 2014)
print(df_age_2014.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2014          22767            2.8            4.1
1  8600000US10002  2014          79894            4.0            4.0
2  8600000US10003  2014          57068            2.9            1.3
3  8600000US10004  2014           3024            3.5            3.0
4  8600000US10005  2014           7570            3.4            2.2

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            3.0            5.0           13.3           12.4           10.8
1            4.4            4.9            6.5            8.7            8.5
2            1.7           10.8           11.2           16.0           11.9
3            3.5            5.4            9.3           13.9           14.6
4            2.3            0.2           13.2           35.7           15.5

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0            9.3            6.3            5.8            5.2            7.3
1            7.6            7.1            7.4            6.7            6.2
2            7.6            6.5            4.6            5.3            5.1
3            8.9            7.7            6.9            6.4            3.7
4            9.4            8.4            4.9            2.2            1.1

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0            4.1            3.4            1.8            2.3            1.8
1            6.7            4.1            3.9            3.7            2.8
2            4.7            4.1            1.8            2.0            1.3
3            6.5            4.2            1.8            0.4            0.3
4            0.5            0.3            0.6            0.0            0.0

In [ ]:
url = "https://api.census.gov/data/2013/acs/acs5/subject?get=group(S0101)&ucgid=8600000US10001,8600000US10002,8600000US10003,8600000US10004,8600000US10005,8600000US10006,8600000US10007,8600000US10009,8600000US10010,8600000US10011,8600000US10012,8600000US10013,8600000US10014,8600000US10016,8600000US10017,8600000US10018,8600000US10019,8600000US10020,8600000US10021,8600000US10022,8600000US10023,8600000US10024,8600000US10025,8600000US10026,8600000US10027,8600000US10028,8600000US10029,8600000US10030,8600000US10031,8600000US10032,8600000US10033,8600000US10034,8600000US10035,8600000US10036,8600000US10037,8600000US10038,8600000US10039,8600000US10040,8600000US10044,8600000US10065,8600000US10069,8600000US10075,8600000US10103,8600000US10110,8600000US10111,8600000US10112,8600000US10115,8600000US10119,8600000US10128,8600000US10152,8600000US10153,8600000US10154,8600000US10162,8600000US10165,8600000US10167,8600000US10168,8600000US10169,8600000US10170,8600000US10171,8600000US10172,8600000US10173,8600000US10174,8600000US10177,8600000US10199,8600000US10271,8600000US10278,8600000US10279,8600000US10280,8600000US10282,8600000US10301,8600000US10302,8600000US10303,8600000US10304,8600000US10305,8600000US10306,8600000US10307,8600000US10308,8600000US10309,8600000US10310,8600000US10311,8600000US10312,8600000US10314,8600000US10451,8600000US10452,8600000US10453,8600000US10454,8600000US10455,8600000US10456,8600000US10457,8600000US10458,8600000US10459,8600000US10460,8600000US10461,8600000US10462,8600000US10463,8600000US10464,8600000US10465,8600000US10466,8600000US10467,8600000US10468,8600000US10469,8600000US10470,8600000US10471,8600000US10472,8600000US10473,8600000US10474,8600000US10475,8600000US11001,8600000US11003,8600000US11004,8600000US11005,8600000US11040,8600000US11101,8600000US11102,8600000US11103,8600000US11104,8600000US11105,8600000US11106,8600000US11109,8600000US11201,8600000US11203,8600000US11204,8600000US11205,8600000US11206,8600000US11207,8600000US11208,8600000US11209,8600000US11210,8600000US11211,8600000US11212,8600000US11213,8600000US11214,8600000US11215,8600000US11216,8600000US11217,8600000US11218,8600000US11219,8600000US11220,8600000US11221,8600000US11222,8600000US11223,8600000US11224,8600000US11225,8600000US11226,8600000US11228,8600000US11229,8600000US11230,8600000US11231,8600000US11232,8600000US11233,8600000US11234,8600000US11235,8600000US11236,8600000US11237,8600000US11238,8600000US11239,8600000US11351,8600000US11354,8600000US11355,8600000US11356,8600000US11357,8600000US11358,8600000US11359,8600000US11360,8600000US11361,8600000US11362,8600000US11363,8600000US11364,8600000US11365,8600000US11366,8600000US11367,8600000US11368,8600000US11369,8600000US11370,8600000US11371,8600000US11372,8600000US11373,8600000US11374,8600000US11375,8600000US11377,8600000US11378,8600000US11379,8600000US11385,8600000US11411,8600000US11412,8600000US11413,8600000US11414,8600000US11415,8600000US11416,8600000US11417,8600000US11418,8600000US11419,8600000US11420,8600000US11421,8600000US11422,8600000US11423,8600000US11424,8600000US11425,8600000US11426,8600000US11427,8600000US11428,8600000US11429,8600000US11430,8600000US11432,8600000US11433,8600000US11434,8600000US11435,8600000US11436,8600000US11451,8600000US11691,8600000US11692,8600000US11693,8600000US11694,8600000US11697,8600000US99999"\
    .format(census_api_key)

response = requests.request("GET", url)

In [ ]:
df_age_2013 = process_age_response(response, 2013)
print(df_age_2013.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  8600000US10001  2013          21966            3.3            3.1
1  8600000US10002  2013          82191            3.8            4.3
2  8600000US10003  2013          57310            2.8            1.3
3  8600000US10004  2013           2807            4.2            3.7
4  8600000US10005  2013           6822            3.6            1.6

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            2.3            6.0           13.0           13.1            9.9
1            4.7            4.7            6.5            9.0            9.1
2            1.4           11.2           11.0           16.4           12.1
3            2.6            4.2           10.9           13.3           16.2
4            1.2            0.6           13.9           36.1           17.6

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0            8.6            7.2            5.6            5.7            7.1
1            8.3            6.7            6.7            6.1            6.1
2            7.3            6.5            4.8            5.5            5.0
3            9.3            8.4            6.7            6.4            3.3
4            9.1            7.8            5.0            1.1            1.3

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0            4.4            3.1            2.1            1.7            2.3
1            6.4            4.1            4.1            3.8            2.8
2            4.8            3.9            1.9            1.9            1.2
3            7.3            2.9            0.0            0.3            0.3
4            0.8            0.3            0.0            0.0            0.0

In [ ]:
  dfs = [df_age_2023, df_age_2022, df_age_2021, df_age_2020,
       df_age_2019, df_age_2018, df_age_2017]

# Concatenate the DataFrames vertically (row-wise)
merged_df_age = pd.concat(dfs, ignore_index=True)

print(merged_df_age.head())
print(merged_df_age.tail())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  860Z200US10001  2023          29079           1173            889
1  860Z200US10002  2023          75517           2259           3268
2  860Z200US10003  2023          53825           1399            999
3  860Z200US10004  2023           3875            364            284
4  860Z200US10005  2023           9238            356            168

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0            907           1302           2084           3993           4172
1           3051           2724           4797           7173           5944
2            926           7281           6676           7119           5838
3             73             91             53            570            708
4            319             56           1014           2272           1304

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0           2697           1975           1741           1604           1625
1           5349           5147           4267           4511           5651
2           3112           3115           2052           2525           2087
3            529            239            298             90            267
4           1103            632            475            699            348

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0           1361           1150           1083            600            258
1           4108           4945           5034           2646           2124
2           2413           2831           2081           1583            812
3            132            114              4             22              7
4            131            157            204              0              0
               ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
1487  8600000US11691  2017          65356           7040           5959
1488  8600000US11692  2017          20242           1463           1743
1489  8600000US11693  2017          12709           1080            941
1490  8600000US11694  2017          21003           1237            784
1491  8600000US11697  2017           3702            193            206

     S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E  \
1487           4339           4022           4403           5053
1488           1616           1494           1256           1273
1489            654            645            897            788
1490           1218           1116            761            958
1491            267            219            218            174

     S0101_C01_008E S0101_C01_009E S0101_C01_010E S0101_C01_011E  \
1487           4178           4363           2714           3645
1488           1585           1277           1160           1420
1489            631            873            857           1023
1490           1455           1056            958           1289
1491             94            145            158            241

     S0101_C01_012E S0101_C01_013E S0101_C01_014E S0101_C01_015E  \
1487           3830           3992           3411           2510
1488           1384           1337           1024            872
1489           1066            837            809            620
1490           2004           2066           1608           1417
1491            341            246            307            224

     S0101_C01_016E S0101_C01_017E S0101_C01_018E
1487           1804           1580           1348
1488            440            437            206
1489            545            206            198
1490           1001            817            461
1491            196            118            206

In [ ]:
# First, convert all columns to numeric (just in case some are strings)
merged_df_age = merged_df_age.apply(pd.to_numeric, errors='ignore')

# Store total column separately
total_col = 'S0101_C01_001E'

# Columns to calculate percent for (exclude 'ucgid', 'year', and the total column itself)
percent_cols = [col for col in merged_df_age.columns
                if col not in ['ucgid', 'year', total_col]]

# Create percent columns
for col in percent_cols:
    pct_col = col + '_pct'
    merged_df_age[pct_col] = (merged_df_age[col] / merged_df_age[total_col]) * 100

In [ ]:
# Keep total column and all percentage columns
cols_to_keep = ['S0101_C01_001E'] + [col for col in merged_df_age.columns if col.endswith('_pct')]

# Also keep 'ucgid' and 'year' for context
cols_to_keep = ['ucgid', 'year'] + cols_to_keep

# Subset the DataFrame
merged_df_age = merged_df_age[cols_to_keep]

# Optional: reset index
merged_df_age = merged_df_age.reset_index(drop=True)

merged_df_age.columns = [
    col.replace('_pct', '') if col.endswith('_pct') else col
    for col in merged_df_age.columns
]

In [ ]:
dfs = [merged_df_age, df_age_2016, df_age_2015, df_age_2014, df_age_2013]

# Concatenate the DataFrames vertically (row-wise)
merged_df_age_pct = pd.concat(dfs, ignore_index=True)

print(merged_df_age_pct.head())

            ucgid  year S0101_C01_001E S0101_C01_002E S0101_C01_003E  \
0  860Z200US10001  2023          29079       4.033839       3.057189
1  860Z200US10002  2023          75517       2.991379       4.327502
2  860Z200US10003  2023          53825       2.599164       1.856015
3  860Z200US10004  2023           3875       9.393548       7.329032
4  860Z200US10005  2023           9238       3.853648       1.818575

  S0101_C01_004E S0101_C01_005E S0101_C01_006E S0101_C01_007E S0101_C01_008E  \
0       3.119089       4.477458       7.166684      13.731559      14.347123
1        4.04015       3.607135       6.352212       9.498524       7.871075
2        1.72039      13.527171      12.403158      13.226196      10.846261
3       1.883871       2.348387       1.367742      14.709677      18.270968
4       3.453128       0.606192      10.976402      24.594068      14.115609

  S0101_C01_009E S0101_C01_010E S0101_C01_011E S0101_C01_012E S0101_C01_013E  \
0       9.274734       6.791843       5.987138       5.516008       5.588225
1       7.083173       6.815684       5.650383       5.973489       7.483083
2         5.7817       5.787274       3.812355       4.691129        3.87738
3      13.651613       6.167742       7.690323       2.322581       6.890323
4      11.939814       6.841308       5.141806       7.566573       3.767049

  S0101_C01_014E S0101_C01_015E S0101_C01_016E S0101_C01_017E S0101_C01_018E
0       4.680354       3.954744       3.724337       2.063345       0.887238
1       5.439835       6.548194       6.666049       3.503847       2.812612
2       4.483047       5.259638       3.866233       2.941013       1.508593
3       3.406452       2.941935       0.103226       0.567742       0.180645
4       1.418056       1.699502        2.20827            0.0            0.0

In [ ]:
# Create grouped columns
merged_df_age_pct['pct_children_teens_5-19'] = (
    merged_df_age_pct[['S0101_C01_003E', 'S0101_C01_004E', 'S0101_C01_005E']].astype(float).sum(axis=1)
)

merged_df_age_pct['pct_young_adults_20-34'] = (
    merged_df_age_pct[['S0101_C01_006E', 'S0101_C01_007E']].astype(float).sum(axis=1)
)

merged_df_age_pct['pct_middle_aged_35-59'] = (
    merged_df_age_pct[['S0101_C01_008E', 'S0101_C01_009E', 'S0101_C01_010E',
                       'S0101_C01_011E', 'S0101_C01_012E']].astype(float).sum(axis=1)
)

merged_df_age_pct['pct_older_adults_60+'] = (
    merged_df_age_pct[['S0101_C01_013E', 'S0101_C01_014E', 'S0101_C01_015E',
                       'S0101_C01_016E', 'S0101_C01_017E', 'S0101_C01_018E']].astype(float).sum(axis=1)
)

# Keep only relevant columns
final_df = merged_df_age_pct[[
    'ucgid', 'year', 'S0101_C01_001E',  # total population
    'pct_children_teens_5-19', 'pct_young_adults_20-34',
    'pct_middle_aged_35-59', 'pct_older_adults_60+'
]]

final_df_age = final_df.rename(columns={'S0101_C01_001E': 'total_population'})

In [ ]:
for df in [final_df_age]:
    df['zcta'] = df['ucgid'].str[-5:]
    df['merge_key'] = df['year'].astype(str) + "_" + df['zcta']

In [ ]:
final_df_age

,ucgid,year,total_population,pct_children_teens_5-19,pct_young_adults_20-34,pct_middle_aged_35-59,pct_older_adults_60+,zcta,merge_key
0,860Z200US10001,2023,29079,10.653736,20.898243,41.916847,20.898243,10001,2023_10001
1,860Z200US10002,2023,75517,11.974787,15.850736,33.393805,32.453620,10002,2023_10002
2,860Z200US10003,2023,53825,17.103576,25.629354,30.918718,21.935903,10003,2023_10003
3,860Z200US10004,2023,3875,11.561290,16.077419,48.103226,14.090323,10004,2023_10004
4,860Z200US10005,2023,9238,5.877896,35.570470,45.605109,9.092877,10005,2023_10005
...,...,...,...,...,...,...,...,...,...
2343,8600000US11691,2013,61091,21.800000,15.600000,29.600000,20.500000,11691,2013_11691
2344,8600000US11692,2013,17674,22.000000,13.800000,34.700000,20.700000,11692,2013_11692
2345,8600000US11693,2013,11335,19.700000,12.100000,38.500000,23.100000,11693,2013_11693
2346,8600000US11694,2013,21725,19.100000,9.000000,35.100000,29.100000,11694,2013_11694
2347,8600000US11697,2013,4223,19.400000,7.100000,25.900000,39.300000,11697,2013_11697

In [ ]:
merged_df_housesize_pct

,ucgid,year,housing_units,pct_1_person,pct_2_person,pct_3_person,pct_4_or_more_person,zcta,merge_key
0,860Z200US10020,2023,0,NaN,NaN,NaN,NaN,10020,2023_10020
1,860Z200US10103,2023,0,NaN,NaN,NaN,NaN,10103,2023_10103
2,860Z200US10110,2023,0,NaN,NaN,NaN,NaN,10110,2023_10110
3,860Z200US10111,2023,0,NaN,NaN,NaN,NaN,10111,2023_10111
4,860Z200US10112,2023,0,NaN,NaN,NaN,NaN,10112,2023_10112
...,...,...,...,...,...,...,...,...,...
2343,8600000US11691,2013,18942,29.1,22.4,15.2,33.2,11691,2013_11691
2344,8600000US11692,2013,5974,26.4,23.1,23.1,27.3,11692,2013_11692
2345,8600000US11693,2013,4518,31.6,30.1,18.3,19.9,11693,2013_11693
2346,8600000US11694,2013,8190,32.5,28.0,17.7,21.8,11694,2013_11694
2347,8600000US11697,2013,1701,28.9,37.2,11.9,22.0,11697,2013_11697

In [ ]:
merged_age_housesize = final_df_age.merge(
    merged_df_housesize_pct,
    on='merge_key',
    suffixes=('_age', '_housesize')
)

# Drop duplicate columns coming from merge
merged_age_housesize = merged_age_housesize[[
    'merge_key', 'zcta_age', 'year_age', 'total_population',
    'pct_children_teens_5-19', 'pct_young_adults_20-34', 'pct_middle_aged_35-59', 'pct_older_adults_60+',
    'housing_units', 'pct_1_person', 'pct_2_person', 'pct_3_person', 'pct_4_or_more_person'
]].rename(columns={
    'zcta_age': 'zcta',
    'year_age': 'year'
})

In [ ]:
merged_age_housesize

,merge_key,zcta,year,total_population,pct_children_teens_5-19,pct_young_adults_20-34,pct_middle_aged_35-59,pct_older_adults_60+,housing_units,pct_1_person,pct_2_person,pct_3_person,pct_4_or_more_person
0,2023_10001,10001,2023,29079,10.653736,20.898243,41.916847,20.898243,15097,55.010929,29.297211,9.518447,6.173412
1,2023_10002,10002,2023,75517,11.974787,15.850736,33.393805,32.453620,35771,44.222974,33.211261,12.521316,10.044449
2,2023_10003,10003,2023,53825,17.103576,25.629354,30.918718,21.935903,25080,53.337321,32.149123,10.07177,4.441786
3,2023_10004,10004,2023,3875,11.561290,16.077419,48.103226,14.090323,1775,40.338028,30.366197,15.71831,13.577465
4,2023_10005,10005,2023,9238,5.877896,35.570470,45.605109,9.092877,5156,53.316524,31.40031,7.059736,8.223429
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,2013_11691,11691,2013,61091,21.800000,15.600000,29.600000,20.500000,18942,29.1,22.4,15.2,33.2
2344,2013_11692,11692,2013,17674,22.000000,13.800000,34.700000,20.700000,5974,26.4,23.1,23.1,27.3
2345,2013_11693,11693,2013,11335,19.700000,12.100000,38.500000,23.100000,4518,31.6,30.1,18.3,19.9
2346,2013_11694,11694,2013,21725,19.100000,9.000000,35.100000,29.100000,8190,32.5,28.0,17.7,21.8
2347,2013_11697,11697,2013,4223,19.400000,7.100000,25.900000,39.300000,1701,28.9,37.2,11.9,22.0

In [ ]:
# prompt: read ACS_clean_income_rent_eductiona.csv from current google drive

import pandas as pd
ACS_1 = pd.read_csv('/content/drive/MyDrive/MLC_Final_Project/Data/ACS Data/ACS_clean_income_rent_eductiona.csv')

In [ ]:
ACS_1.head()

,zcta,year,number_of_households,household_median_income_1yr,household_mean_income_1yr,number_of_rent_home,median_rent,number_of_owned_home,median_home_value,population_25_and_over,less_than_9th_grade,9th_to_12th_grade,high_school_graduate,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree
0,10001,2023,15097,123393,205444,11399,3024,3570,793000,22724,2.112304,5.034325,8.638444,9.514170,3.199261,41.471572,30.029924
1,10002,2023,35771,46525,93314,28916,1207,6660,808500,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064
2,10003,2023,25080,153750,248577,16196,2772,8701,1137000,36544,2.982706,1.313485,4.802430,6.170644,2.531195,44.729641,37.469899
3,10004,2023,1775,220592,309645,1145,3501,630,1866400,3010,0.531561,0.365449,1.661130,6.378738,0.166113,42.624585,48.272425
4,10005,2023,5156,211810,279387,4276,3501,880,1387200,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485

In [ ]:
# Create 'merge_key' in ACS_1 DataFrame
ACS_1['merge_key'] = ACS_1['year'].astype(str) + "_" + ACS_1['zcta'].astype(str)

ACS_1.head()

,zcta,year,number_of_households,household_median_income_1yr,household_mean_income_1yr,number_of_rent_home,median_rent,number_of_owned_home,median_home_value,population_25_and_over,less_than_9th_grade,9th_to_12th_grade,high_school_graduate,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree,merge_key
0,10001,2023,15097,123393,205444,11399,3024,3570,793000,22724,2.112304,5.034325,8.638444,9.514170,3.199261,41.471572,30.029924,2023_10001
1,10002,2023,35771,46525,93314,28916,1207,6660,808500,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064,2023_10002
2,10003,2023,25080,153750,248577,16196,2772,8701,1137000,36544,2.982706,1.313485,4.802430,6.170644,2.531195,44.729641,37.469899,2023_10003
3,10004,2023,1775,220592,309645,1145,3501,630,1866400,3010,0.531561,0.365449,1.661130,6.378738,0.166113,42.624585,48.272425,2023_10004
4,10005,2023,5156,211810,279387,4276,3501,880,1387200,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485,2023_10005

In [ ]:
acs_full = ACS_1.merge(
    merged_age_housesize,
    on='merge_key',
    suffixes=('_acs', '_demo')
)

# Drop the duplicated zcta and year from the right dataframe (merged_age_housesize)
acs_full = acs_full.drop(columns=['zcta_demo', 'year_demo'])

# (Optional) Rename for consistency if needed
acs_full = acs_full.rename(columns={
    'zcta_acs': 'zcta',
    'year_acs': 'year'
})

In [ ]:
acs_full

,zcta,year,number_of_households,household_median_income_1yr,household_mean_income_1yr,number_of_rent_home,median_rent,number_of_owned_home,median_home_value,population_25_and_over,less_than_9th_grade,9th_to_12th_grade,high_school_graduate,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree,merge_key,total_population,pct_children_teens_5-19,pct_young_adults_20-34,pct_middle_aged_35-59,pct_older_adults_60+,housing_units,pct_1_person,pct_2_person,pct_3_person,pct_4_or_more_person
0,10001,2023,15097,123393,205444,11399,3024,3570,793000,22724,2.112304,5.034325,8.638444,9.514170,3.199261,41.471572,30.029924,2023_10001,29079,10.653736,20.898243,41.916847,20.898243,15097,55.010929,29.297211,9.518447,6.173412
1,10002,2023,35771,46525,93314,28916,1207,6660,808500,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064,2023_10002,75517,11.974787,15.850736,33.393805,32.453620,35771,44.222974,33.211261,12.521316,10.044449
2,10003,2023,25080,153750,248577,16196,2772,8701,1137000,36544,2.982706,1.313485,4.802430,6.170644,2.531195,44.729641,37.469899,2023_10003,53825,17.103576,25.629354,30.918718,21.935903,25080,53.337321,32.149123,10.07177,4.441786
3,10004,2023,1775,220592,309645,1145,3501,630,1866400,3010,0.531561,0.365449,1.661130,6.378738,0.166113,42.624585,48.272425,2023_10004,3875,11.561290,16.077419,48.103226,14.090323,1775,40.338028,30.366197,15.71831,13.577465
4,10005,2023,5156,211810,279387,4276,3501,880,1387200,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485,2023_10005,9238,5.877896,35.570470,45.605109,9.092877,5156,53.316524,31.40031,7.059736,8.223429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,11691,2013,18942,39409,56640,13955,1012,4825,448200,35984,12.500000,14.400000,28.300000,16.900000,6.400000,13.500000,8.000000,2013_11691,61091,21.800000,15.600000,29.600000,20.500000,18942,29.1,22.4,15.2,33.2
2344,11692,2013,5974,43354,60455,3918,875,2000,355800,11102,10.700000,13.600000,28.700000,19.900000,7.800000,13.000000,6.200000,2013_11692,17674,22.000000,13.800000,34.700000,20.700000,5974,26.4,23.1,23.1,27.3
2345,11693,2013,4518,50570,60995,2419,831,1992,323100,7664,3.400000,15.500000,30.200000,19.500000,7.400000,17.200000,6.600000,2013_11693,11335,19.700000,12.100000,38.500000,23.100000,4518,31.6,30.1,18.3,19.9
2346,11694,2013,8190,76944,93633,3494,1161,4570,623200,15705,5.100000,6.900000,22.700000,19.200000,8.400000,19.800000,17.700000,2013_11694,21725,19.100000,9.000000,35.100000,29.100000,8190,32.5,28.0,17.7,21.8
2347,11697,2013,1701,87636,100542,52,908,1649,525600,3085,1.800000,3.700000,27.400000,16.100000,6.800000,24.900000,19.300000,2013_11697,4223,19.400000,7.100000,25.900000,39.300000,1701,28.9,37.2,11.9,22.0

In [ ]:
# List of key columns to appear first
key_columns = ['zcta', 'year', 'merge_key']

# Get the rest of the columns
other_columns = [col for col in acs_full.columns if col not in key_columns]

# Reorder the DataFrame
acs_full = acs_full[key_columns + other_columns]

In [ ]:
acs_full

,zcta,year,merge_key,number_of_households,household_median_income_1yr,household_mean_income_1yr,number_of_rent_home,median_rent,number_of_owned_home,median_home_value,population_25_and_over,less_than_9th_grade,9th_to_12th_grade,high_school_graduate,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree,total_population,pct_children_teens_5-19,pct_young_adults_20-34,pct_middle_aged_35-59,pct_older_adults_60+,housing_units,pct_1_person,pct_2_person,pct_3_person,pct_4_or_more_person
0,10001,2023,2023_10001,15097,123393,205444,11399,3024,3570,793000,22724,2.112304,5.034325,8.638444,9.514170,3.199261,41.471572,30.029924,29079,10.653736,20.898243,41.916847,20.898243,15097,55.010929,29.297211,9.518447,6.173412
1,10002,2023,2023_10002,35771,46525,93314,28916,1207,6660,808500,59418,13.788751,15.215928,17.723585,10.347033,3.970177,26.542462,12.412064,75517,11.974787,15.850736,33.393805,32.453620,35771,44.222974,33.211261,12.521316,10.044449
2,10003,2023,2023_10003,25080,153750,248577,16196,2772,8701,1137000,36544,2.982706,1.313485,4.802430,6.170644,2.531195,44.729641,37.469899,53825,17.103576,25.629354,30.918718,21.935903,25080,53.337321,32.149123,10.07177,4.441786
3,10004,2023,2023_10004,1775,220592,309645,1145,3501,630,1866400,3010,0.531561,0.365449,1.661130,6.378738,0.166113,42.624585,48.272425,3875,11.561290,16.077419,48.103226,14.090323,1775,40.338028,30.366197,15.71831,13.577465
4,10005,2023,2023_10005,5156,211810,279387,4276,3501,880,1387200,7325,0.887372,1.665529,5.870307,6.484642,0.832765,50.552901,33.706485,9238,5.877896,35.570470,45.605109,9.092877,5156,53.316524,31.40031,7.059736,8.223429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,11691,2013,2013_11691,18942,39409,56640,13955,1012,4825,448200,35984,12.500000,14.400000,28.300000,16.900000,6.400000,13.500000,8.000000,61091,21.800000,15.600000,29.600000,20.500000,18942,29.1,22.4,15.2,33.2
2344,11692,2013,2013_11692,5974,43354,60455,3918,875,2000,355800,11102,10.700000,13.600000,28.700000,19.900000,7.800000,13.000000,6.200000,17674,22.000000,13.800000,34.700000,20.700000,5974,26.4,23.1,23.1,27.3
2345,11693,2013,2013_11693,4518,50570,60995,2419,831,1992,323100,7664,3.400000,15.500000,30.200000,19.500000,7.400000,17.200000,6.600000,11335,19.700000,12.100000,38.500000,23.100000,4518,31.6,30.1,18.3,19.9
2346,11694,2013,2013_11694,8190,76944,93633,3494,1161,4570,623200,15705,5.100000,6.900000,22.700000,19.200000,8.400000,19.800000,17.700000,21725,19.100000,9.000000,35.100000,29.100000,8190,32.5,28.0,17.7,21.8
2347,11697,2013,2013_11697,1701,87636,100542,52,908,1649,525600,3085,1.800000,3.700000,27.400000,16.100000,6.800000,24.900000,19.300000,4223,19.400000,7.100000,25.900000,39.300000,1701,28.9,37.2,11.9,22.0

In [ ]:
acs_full.to_csv('ACS_update.csv', index=False)